### ISSUE TITLE
!! Major Cipher issue !!

### ISSUE THREAD

**Issue by KoljaWindeler** [KoljaWindeler/ytube_music_player#100]
Hi everyone, I'm writing this because I get multiple bug reports via all channels I can think of, even my wife complained in person :D. YouTube changed the way how the streaming data are pushed to the client and this results in major issues at the moment.

As of now the decoding way works like this:

**Init**  
1. create a PyTube instance
2. feed a YouTube (! not YouTube music) page to PyTube to load the javascript and parse the decipher algorithm  

**For every song**  
1. Request the streaming data (Url + ciphered signature) via ytubemusicapi
2. Let PyTube decipher the signature 
3. Join url + sig and push that to the player 
4. if the procedure above fails (which it never did), push the videoId to PyTube and see if it can find the link

Usually step 4 never ran. It's more like a backup ... it works, but not for all songs and it is also a lot slower.
After youtube changed the backend the streamingData for step 1 above were no longer present (https://github.com/KoljaWindeler/ytube_music_player/issues/97). sigma67 (author of the fabulous backend) fixed this quickly, but the newly presented streamingData work 'differently' .. at least the usual way to decipher them isn't working anymore. 

So with release https://github.com/KoljaWindeler/ytube_music_player/tree/20210517b01 every request uses step 4. Some video/music links are NOT decodable this way. the player will accept up to 3 fails in a row before giving up. I've seen on my setup that the player has to skip quite a few songs and sometime even stops completely (after 3 fails). 

Currently that's where we are. I'm very unhappy and keep working on a solution but this could take some time. Any help is appreciated. 
Kolja

**Comment by KoljaWindeler** [comment]
jep

**Comment by DravenSA** [comment]
Is there any error codes we can send, or is it all generic at this moment?

**Comment by slankes** [comment]
As the production version is completly broken now (at least for me) - what do you think about promoting your beta to "stable". I'd say that it cannot get worse ...

**Comment by KoljaWindeler** [comment]
some good news ahead of time but it looks like the issue is fixed. I'm just waiting for sigma to publish a new release. I've verified here with the git-master and its working just fine .. just a little more patience :D

**Comment by KoljaWindeler** [comment]
Fixed with https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20200519.01

**Comment by KoljaWindeler** [comment]
Currently it's broken again .. working on it

**Comment by KoljaWindeler** [comment]
Seems to be working now
