### ISSUE TITLE
New version stopped working

### ISSUE THREAD

**Issue by Yonny24** [KoljaWindeler/ytube_music_player#101]
Hi there.  Just updated your new patch via HACS and just can't get any playback now(sound). Restarted a few times.

Receiving python errors.

` Logger: pychromecast.controllers
Source: /usr/local/lib/python3.8/site-packages/pychromecast/controllers/media.py:364
First occurred: 9:21:12 PM (1 occurrences)
Last logged: 9:21:12 PM
STOP command requested but no session is active.`

`Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py:652
First occurred: 9:21:41 PM (1 occurrences)
Last logged: 9:21:41 PM
[piria(192.168.1.138):8009] Error communicating with socket, resetting connection`

Any ideas

**Comment by Yonny24** [comment]
Seems to be related with chromecast integration I think.

**Comment by Yonny24** [comment]
Seems to be an issue with a connection to the media player. It's on and connected to the  LAN but in developer tools it says state 'OFF' hmmm odd

**Comment by Yonny24** [comment]
` Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1564
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 10:10:38 PM (1 occurrences)
Last logged: 10:10:38 PM
============= ytube_music_player Integration Error ================`

**Comment by KoljaWindeler** [comment]
Please open a ticket at the chromecast integration, that has nothing to do with my code

**Comment by Yonny24** [comment]
Unfortunately haven't found the root cause yet. I enabled logging for this integration and this appeared:

Does this shed any light on the issue?
Thanks!

`

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:162
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 11:00:25 AM (7 occurrences)
Last logged: 11:00:25 AM

    [S] async_check_api
    [E] async_check_api
    [S] async_update_remote_player(Input / current )
    [E] async_update_remote_player no change
    [E] (fail) async_prepare_play

`
