### ISSUE TITLE
Integrated Login with YouTube

### ISSUE THREAD

**Issue by chicagoandy** [KoljaWindeler/ytube_music_player#103]
To state the obvious enhancement request, 

This would be more awesome if we could automatically login via the Youtube API.  https://developers.google.com/youtube/v3/getting-started

**Comment by KoljaWindeler** [comment]
https://github.com/sigma67/ytmusicapi/issues/10

Hi, something like this is already in the works ..

**Comment by KoljaWindeler** [comment]
Done for quite some time now
