### ISSUE TITLE
Add Support for Media_Source

### ISSUE THREAD

**Issue by stboch** [KoljaWindeler/ytube_music_player#106]
**Describe the solution you'd like**
Add support for Media_Source Similar to be separate from MediaBrowser
https://www.home-assistant.io/integrations/media_source 
This will allow you to use the YTmusic content directly in home-assistant across all media_players 

**Additional context**
I tried to adapt the work myself, but struggled with my python skills to get it to work with the existing layout of the class design, someone with more python experience my be more successful with less effort. 
Example of someone elses app used to build the BrowseMediaSource model
 https://github.com/music-assistant/hass-integration/blob/master/custom_components/music_assistant/media_source.py

**Comment by KoljaWindeler** [comment]
I don't this is possible .. it seems to be purely folder/file based ..
