### ISSUE TITLE
Error on play music

### ISSUE THREAD

**Issue by gyenesadam** [KoljaWindeler/ytube_music_player#110]
Hi!

I got the following error, when I wan't to "turn on" media player.

yTubeMediaPlayer error
You have no playlist entity_id in your config, or that entity_id is not in homeassistant. I don't know what to play and will exit. Either use the media_browser or add the playlist dropdown_

I followed the next steps:

1. Install the extension from HACS.
2. In Integrations menu, I setup the ytube music. (Paste the cookie, setup the output))
3. Put a media player into my lovelace.

After theese steps, I can't play anything from my playlist.

Sorry, I am very starter, I working on it from weeks, but I can't solve it. Can you help me??

+1. I try to install mini media player.

1. download and copy the  *.js to the www folders (into root).
2. In Lovelace panels-> Resources tab I insert:
/local/mini-media-player-bundle.js?v=1.12.1       JavaScript

Unfortunately I can't use this.

Of course i try to estart my HA.

Thanks a lot!
![1](https://user-images.githubusercontent.com/77073590/125490567-a0ed3807-eba9-4556-a6e3-f2f74910351a.png)
![2](https://user-images.githubusercontent.com/77073590/125490574-c4f9c639-b705-4514-8a0d-36d62a6bf9c5.png)
![3](https://user-images.githubusercontent.com/77073590/125490576-b9ff647a-2653-4630-8f89-273d2d8110f7.png)
![4](https://user-images.githubusercontent.com/77073590/125490578-ba96e312-1333-4e12-8133-5b2b7ad48ac6.png)
![5](https://user-images.githubusercontent.com/77073590/125490580-dfabae67-7f45-4114-820e-39b496a7f45c.png)
![6](https://user-images.githubusercontent.com/77073590/125490581-ca802b68-c331-4476-8d9a-c09f2ca757c7.png)
![7](https://user-images.githubusercontent.com/77073590/125490585-2546d97a-9679-4fcb-a065-cd75f379b43d.png)

**Comment by KoljaWindeler** [comment]
1st item here https://github.com/KoljaWindeler/ytube_music_player#faq

**Comment by KoljaWindeler** [comment]
This is likely a problem with the output speaker ... You are using your phone correct? What kind of integration are you using for that? Browser_mod?

**Comment by gyenesadam** [comment]
No, I using Fully kiosk Browser on my phone, and it's integration for use it as output player

**Comment by KoljaWindeler** [comment]
Could you enable the debug mode (see readme) and click one of those actions like pause and copy the log to this issue? 

And maybe also pause the playback on your phone. We might get extra information that way.

**Comment by gyenesadam** [comment]
Of course, I send as soon as possible!
