### ISSUE TITLE
Help - no playlist entity_id

### ISSUE THREAD

**Issue by tripplehelix** [KoljaWindeler/ytube_music_player#112]
Sorry this isn't a bug on your end but was hoping to get some help. I am encountering the error:

"You have no playlist entity_id in your config, or that entity_id is not in homeassistant. I don't know what to play and will exit. Either use the media_browser or add the playlist dropdown"

What does this mean? The integration used to work but has since broke, I'm guessing formatting in the config somewhere has changed but I can't find the issue.

**Comment by tripplehelix** [comment]
The HACS install isn't asking for information so I also can't input my cookie

**Comment by tripplehelix** [comment]
I'm an idiot... ignore this

**Comment by tripplehelix** [comment]
Ok I've fully reinstalled but getting the same error.... where does it want this information?

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player#faq
1st item

**Comment by tripplehelix** [comment]
I sat and stared at that for ages... Sorry!

**Comment by KoljaWindeler** [comment]
No worries
