### ISSUE TITLE
Next track not working

### ISSUE THREAD

**Issue by tgooro** [KoljaWindeler/ytube_music_player#115]
I am using this with a lot of media players I have in my home assistant configuration including google speakers and Bose speakers. Firstly the add undoes not work with Bose speakers. It does work on google speakers but intermittently, however next track does not respond at all. Every time I tap next track, it keeps playing the first track. Though the media player displays next song but the player only plays the first song.

Also, I made the changes to proxy path and url but it is still not working on Bose.

Thanks

**Comment by KoljaWindeler** [comment]
Hmm that's too bad. Sadly there is only very little I can do here. I've heard somewhere (in the forum?) That the Bose part should work ... Maybe ask there for input. 

Google mini / Chromecast work fine here. What device do you use exactly ? Playing the same song can be a issue of buffering. Did that happen with the proxy enabled? If so: delete the integration, set it up again without the proxy and test on your Google device please.

**Comment by tgooro** [comment]
Thanks mate. Do you have the link to the forum where they discuss Bose part, if you may already know.

I am using google mini and google home speakers. Will try your suggestion.

**Comment by KoljaWindeler** [comment]
Hmm no, it was actual your request about the Bose just in a different ticket... Sorry. 

You COULD also enable debug (see readme) and try playing a song on the Bose ... And post the log

**Comment by KoljaWindeler** [comment]
Did you read this: https://www.home-assistant.io/integrations/soundtouch/

Https is not supported, http is ... Did you pay attention to that detail?

**Comment by tgooro** [comment]
I removed the integration and set it again without the proxy details and the google cast started working correctly. If I put that in, the Bose speakers still do not work.

**Comment by KoljaWindeler** [comment]
Could you specify what you mean by "that" ?
I thing there is very little I can do. You should probably open a ticket at the Bose integration

**Comment by tgooro** [comment]
What I mean is that when I add the integration it works fine on my google speakers but doesn't work on Bose. Once I added the proxy details, the next track button stopped working on google speakers but the Bose still wouldn't work.

**Comment by KoljaWindeler** [comment]
I see. I don't have a Bose speaker so it is tricky to help there. Sorry mate. As suggested try to ask the developer of that integration to help out. I'll close this here as there is nothing I can do to help as far as I can see.
