### ISSUE TITLE
Issue with proper configuration

### ISSUE THREAD

**Issue by IT-freak-Jake** [KoljaWindeler/ytube_music_player#117]
Hi, after configuration I can't play anything from the integration, media player can't see actually played track but it can see playlists from YT music, even my privates.

In logs, I'm getting those errors (I have checked "show all debug as ERROR in the log"):

ERROR 1:

[S] async_update
[S] async_get_cipher [E]
[S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 0.18.0 [E]

ERROR 2:

[E] async_update_selects
[S] async_update_playmode
[E] async_update_playmode 2
[E] async_startup
[E] async_update

**Comment by KoljaWindeler** [comment]
Hmm those aren't errors. That just the E from End ... When I leave the function. 

What happens when you select a playlist on the media_browser (!) ... And what shows up in the log

**Comment by refaelsommer** [comment]
I also have same issue, it worked on Friday, but today not working, I go into the library and open playlists then choose a playlist tap play, also a few times and nothing happens, the player is just staying gray not playing.
In the logs of the HA there is nothing. Is there another log to check?

**Comment by KoljaWindeler** [comment]
actually i thing those are two different issues ... your issue seem to be that you don't have a player selected
**async_update_remote_player(Input / current )** .. I've seen this before and still wonder how this is possible :D 

don't you have an output player defined? Or is your player (chromecast / mpd / .. ) maybe offline ?

**Comment by IT-freak-Jake** [comment]
After selecting a playlist nothing is happening.
Log output after choosing a playlist:

First:

[S] async_check_api [E]
[S] async_update_remote_player(Input / current )

Second:

async_browse_media
[S] play_media, media_type: playlist, media_id: PLBcgDRZxgPbz5fvOQ5TY890Xbs_V1bj7B
[S] async_prepare_play
no change [E]
[E] (fail) async_prepare_play

**Comment by KoljaWindeler** [comment]
If you go back to configuration -> integration -> ytube_music_player -> click configuration, does it show you a player? Is there something selected?

**Comment by IT-freak-Jake** [comment]
Yes, I have selected my Google home speaker

**Comment by KoljaWindeler** [comment]
Could you try to reselect you speaker.
One fairly new way would be: media_browser -> (choose player -> ytube_music_player) -> playback device -> your speaker

And then again in the media_browser -> playlist or whatever -> play

**Comment by IT-freak-Jake** [comment]
I did it and nothing changed :/

**Comment by KoljaWindeler** [comment]
Could you copy the debug log into this ticket ? The part that shows when you select the output device

**Comment by IT-freak-Jake** [comment]
First log:
[S] async_check_api [E]
[S] async_update_remote_player(Input / current )

Second log:
async_browse_media
[S] play_media, media_type: speakers, media_id: jackob_s_room
[S] async_prepare_play
no change [E]
[E] (fail) async_prepare_play

**Comment by KoljaWindeler** [comment]
That's what you see when you select another speaker in the media browser?

**Comment by IT-freak-Jake** [comment]
I have the same logs for choosing the same speaker as default and another one. The only difference is media_id

**Comment by KoljaWindeler** [comment]
hmm very strange ... i don't know how to help. the logs look very different for me, e.g. like this: 

2021-07-26T10:25:11.535541193Z 2021-07-26 12:25:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(bm_8e5f874f_8dfcb60f)
2021-07-26T10:25:11.535611574Z 2021-07-26 12:25:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.bm_8e5f874f_8dfcb60f/ current media_player.bm_8e5f874f_8dfcb60f) 
2021-07-26T10:25:11.535628179Z 2021-07-26 12:25:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player]  no change [E]
2021-07-26T10:25:11.535636017Z 2021-07-26 12:25:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.bm_8e5f874f_8dfcb60f as player
2021-07-26T10:25:11.535642525Z 2021-07-26 12:25:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack passed
2021-07-26T10:25:11.535648994Z 2021-07-26 12:25:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source

**Comment by IT-freak-Jake** [comment]
I'm using an Nginx proxy. Can it be a problem?

**Comment by KoljaWindeler** [comment]
I don't thing so. Could you enable debug (in the configuration of the integration) and paste in a complete log?

**Comment by IT-freak-Jake** [comment]
This is what I'm getting after HA restart:

Log 1:
[S] async_update [E]
[S] async_get_cipher [E]
[S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 0.18.0 [E]

Log 2:
- no playlist select field, exit
[E] async_update_selects
[S] async_update_playmode
[E] async_update_playmode 2
[E] async_startup

**Comment by KoljaWindeler** [comment]
That's strange. There should be way more info.

**Comment by IT-freak-Jake** [comment]
I've only enabled "Show all debug output as ERROR in the log". Should I do something more?

**Comment by KoljaWindeler** [comment]
Well ... I'd expect something like this:

```
[custom_components.ytube_music_player.media_player] Config via Storage/UI
[custom_components.ytube_music_player.media_player] YtubeMediaPlayer config: 
[custom_components.ytube_music_player.media_player] - Header path: /config/.storage/ytube_header.json
[custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist
[custom_components.ytube_music_player.media_player] - mediaplayer: input_select.ytube_music_player_speakers
[custom_components.ytube_music_player.media_player] - source: input_select.ytube_music_player_source
[custom_components.ytube_music_player.media_player] - speakerlist: ['media_player.keller_2']
[custom_components.ytube_music_player.media_player] - playModes: input_select.ytube_music_player_playmode
[custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous
[custom_components.ytube_music_player.media_player] - shuffle: True
[custom_components.ytube_music_player.media_player] - shuffle_mode: 1
[custom_components.ytube_music_player.media_player] - like_in_name: False
[custom_components.ytube_music_player.media_player] - track_limit: 25
[custom_components.ytube_music_player.media_player] - legacy_radio: True

[custom_components.ytube_music_player.media_player] [S] async_update [E]
[custom_components.ytube_music_player.media_player] [S] async_startup
[custom_components.ytube_music_player.media_player] [S] async_get_cipher [E]
[custom_components.ytube_music_player.const] - login without brand ID
[custom_components.ytube_music_player.media_player] [S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 0.18.0 [E]
[custom_components.ytube_music_player.media_player] [S] async_update_selects
[custom_components.ytube_music_player.media_player] - playmode: input_select.ytube_music_player_playmode not found
[custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous not found
[custom_components.ytube_music_player.media_player] - Adding 13 player to the dropdown
[custom_components.ytube_music_player.media_player] [S] async_update_playlists
[custom_components.ytube_music_player.media_player] [S] async_select_source_helper
[custom_components.ytube_music_player.media_player] Translated friendly name Keller 2 to entity id keller_2
[custom_components.ytube_music_player.media_player] [E] async_select_source_helper
[custom_components.ytube_music_player.media_player] [S] async_select_source(keller_2)
[custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.keller_2/ current )  [E]
[custom_components.ytube_music_player.media_player] - Choosing media_player.keller_2 as player
[custom_components.ytube_music_player.media_player] - untrack passed
[custom_components.ytube_music_player.media_player] [E] async_select_source
[custom_components.ytube_music_player.media_player]  - 32 Playlists loaded
[custom_components.ytube_music_player.media_player] - untrack resub
[custom_components.ytube_music_player.media_player] [E] async_update_playlists
[custom_components.ytube_music_player.media_player] [E] async_update_selects
[custom_components.ytube_music_player.media_player] [S] async_update_playmode
[custom_components.ytube_music_player.media_player] [E] async_update_playmode 2
[custom_components.ytube_music_player.media_player] [E] async_startup
```

**Comment by KoljaWindeler** [comment]
Just to be 100%: those like don't show up on your setup, correct?

**Comment by IT-freak-Jake** [comment]
I'm so sorry, my bad. I was looking into logs in the configuration, not in the supervisor. 😅

Full log after server restart:

[custom_components.ytube_music_player.media_player] YtubeMediaPlayer config: 
[custom_components.ytube_music_player.media_player] - Header path: /config/.storage/ytube_header.json
[custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist
[custom_components.ytube_music_player.media_player] - mediaplayer: input_select.ytube_music_player_speakers
[custom_components.ytube_music_player.media_player] - source: input_select.ytube_music_player_source
[custom_components.ytube_music_player.media_player] - speakerlist: ['media_player.jacob_s_room']
[custom_components.ytube_music_player.media_player] - playModes: input_select.ytube_music_player_playmode
[custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous
[custom_components.ytube_music_player.media_player] - shuffle: True
[custom_components.ytube_music_player.media_player] - shuffle_mode: 1
[custom_components.ytube_music_player.media_player] - like_in_name: False
[custom_components.ytube_music_player.media_player] - track_limit: 25
[custom_components.ytube_music_player.media_player] - legacy_radio: True
[custom_components.ytube_music_player.media_player] [S] async_update [E]

[custom_components.ytube_music_player.media_player] [S] async_startup
[custom_components.ytube_music_player.media_player] [S] async_get_cipher [E]
[custom_components.ytube_music_player.media_player] [S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 0.18.0 [E]
[custom_components.ytube_music_player.media_player] [S] async_update_selects
[custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist not found
[custom_components.ytube_music_player.media_player] - playmode: input_select.ytube_music_player_playmode not found
[custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous not found
[custom_components.ytube_music_player.media_player] - mediaPlayer: input_select.ytube_music_player_speakers not found
[custom_components.ytube_music_player.media_player] - Source: input_select.ytube_music_player_source not found
[custom_components.ytube_music_player.media_player] - Drop down for media player not found
[custom_components.ytube_music_player.media_player] [S] async_update_playlists
[custom_components.ytube_music_player.media_player] - no playlist select field, exit
[custom_components.ytube_music_player.media_player] [E] async_update_selects
[custom_components.ytube_music_player.media_player] [S] async_update_playmode
[custom_components.ytube_music_player.media_player] [E] async_update_playmode 2
[custom_components.ytube_music_player.media_player] [E] async_startup

**Comment by KoljaWindeler** [comment]
Ok and what do you see there once you select a playlist from the media browser?

**Comment by IT-freak-Jake** [comment]
[custom_components.ytube_music_player.media_player] async_browse_media
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] async_browse_media
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: PLBcgDRZxgPbz5fvOQ5TY890Xbs_V1bj7B
[custom_components.ytube_music_player.media_player] [S] async_prepare_play
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current ) 
[custom_components.ytube_music_player.media_player]  no change [E]
[custom_components.ytube_music_player.media_player] [E] (fail) async_prepare_play

**Comment by KoljaWindeler** [comment]
Hmm I'll try some thing tonight (like not having a player drop-down) ... Not sure what's the issue

**Comment by IT-freak-Jake** [comment]
I can't play TTS from my HA with a standard URL (Only IP address). I have to set my HA IP address + :8123 as the base URL to make it work. Can it be related?

**Comment by KoljaWindeler** [comment]
I don't think so. Somehow the integration looses the information about what player it should play on .... 

Could you change(!) The media player via the media_browser and upload the log?

**Comment by IT-freak-Jake** [comment]
After changing speaker:

[custom_components.ytube_music_player.media_player] async_browse_media
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] async_browse_media
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] [S] play_media, media_type: speakers, media_id: googlehome6807
[custom_components.ytube_music_player.media_player] [S] async_prepare_play
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current ) 
[custom_components.ytube_music_player.media_player]  no change [E]
[custom_components.ytube_music_player.media_player] [E] (fail) async_prepare_play

After "playing" a playlist:

[custom_components.ytube_music_player.media_player] async_browse_media
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] async_browse_media
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: PLBcgDRZxgPbz5fvOQ5TY890Xbs_V1bj7B
[custom_components.ytube_music_player.media_player] [S] async_prepare_play
[custom_components.ytube_music_player.media_player] [S] async_check_api [E]
[custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current ) 
[custom_components.ytube_music_player.media_player]  no change [E]
[custom_components.ytube_music_player.media_player] [E] (fail) async_prepare_play

**Comment by KoljaWindeler** [comment]
Hmm .. I'll test tonight (in ~3h) to see what else could cause this behavior ..

**Comment by IT-freak-Jake** [comment]
Ok, I'll wait. Thank you

**Comment by KoljaWindeler** [comment]
Please try updating (you have to enable beta releases in HACS, if you haven't done that already (remove integration and reinstall will offer the beta checkbox))
https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210727.01

**Comment by IT-freak-Jake** [comment]
Now everything is working. Thank you. I owe you a beer 😉

**Comment by KoljaWindeler** [comment]
great and thanks for the beer! glad that is now working
