### ISSUE TITLE
bad cover artwork quality

### ISSUE THREAD

**Issue by Drauboss** [KoljaWindeler/ytube_music_player#119]
For whatever reason the Cover artwork quality is bad. Tried to restart, clear cache but it doesnt helped

![Screenshot 2021-07-27 142949](https://user-images.githubusercontent.com/70546597/127153879-3de29353-4b22-477e-a534-f8a02008ca72.png)

**Comment by KoljaWindeler** [comment]
Agreed. 
The current logic is just to take the last available thumbnail but that's not necessarily the best quality. I'll have a look

**Comment by KoljaWindeler** [comment]
Please test https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210727.02 and provide feedback

**Comment by KoljaWindeler** [comment]
![image](https://user-images.githubusercontent.com/471314/127207893-2446c909-7ba8-4230-a1b7-817e4c09b991.png)

**Comment by Drauboss** [comment]
sadly its still not working for me

**Comment by KoljaWindeler** [comment]
aber du hast schon geupdated und neugestartet oder? 
Ich koennte zwar etwas debug einbauen aber wahrscheinlich wird das wenig bringen .. ist das bei allen Tracks so schlecht oder nur bei dem?

**Comment by Drauboss** [comment]
ja geupdatet und neugestartet und auch cache gecleared. Habe grade herausgefunden dass die qualität nur schlecht ist wenn ich als source playlist eintelle. Bei source: playlist radio sind die cover gut
![with playlist radio](https://user-images.githubusercontent.com/70546597/127212079-ec18f727-b010-490f-b760-d7e583ae87bd.png)
![with playlist](https://user-images.githubusercontent.com/70546597/127212084-5e752eef-5227-430c-8077-e9a679a16fb2.png)

**Comment by KoljaWindeler** [comment]
Tatsache ... das ja merkwuerdig .. moment

**Comment by KoljaWindeler** [comment]
ok, versuch nochmal bitte. Gibt eine neue beta version.
Ich kann nicht sagen warum es so ist, aber die get_playlist gibt nur ein thumbnail zurueck. 
Allerdings lade ich NACHDEM der playback startet noch die lyrics, in dem call bekomme ich mehrere auch bessere bilder. ich ersetze das nun nachträglich wenn ein besseres bild da ist (was bei mir zu 90% meiner Tests der Fall war) .. du bekommst also erst ein schlechtes Bild und so nach 1-2sec ein besseres .. zumindest meistens

**Comment by Drauboss** [comment]
Perfekt funktioniert. Danke dir. Echt nice Integration.
