### ISSUE TITLE
Question about changing the source player

### ISSUE THREAD

**Issue by IT-freak-Jake** [KoljaWindeler/ytube_music_player#120]
Is there a way to change the source player? I would like to change the source player from my phone to the ytube_media_player when I'm playing music from my phone on my google speaker without interrupting the music. Is it possible?

**Comment by stboch** [comment]
Let me see if I understand correctly the flow, you listening to music from your phone casting to your Google speaker. But you want to transition the media play from your phone casting to ytMusic casting?

**Comment by KoljaWindeler** [comment]
That's how I understood it as well. Homeassistent would need to know what song you're playing and which position you're at.  Also maybe what playlist etc.. 

Your Google home would have to switch between Google's native ytube_music_app and the "cast" app that Homeassistent uses, load the song and jump to the correct position without interruption.

In short: no, that's not that easy. I'll close this as I don't thing that this feature can even be implemented. Please re-open if you had a different workflow in mind.
