### ISSUE TITLE
Getting ytube_music_player.search results from automation level

### ISSUE THREAD

**Issue by IT-freak-Jake** [KoljaWindeler/ytube_music_player#124]
Hi, I would like to be able to get ytube_music_player.search results from node-red. What I'm trying to do is getting the playlist name from google home speaker while playing YT music cast from my phone, calling the ytube_music_player.search service, and get links to the searched playlists/tracks, then get one of those links and play it on ytube_music_player.

Could you make a separate entity that provides information about search results, or make it some other way that I can get this info from the automation level?

**Comment by KoljaWindeler** [comment]
Not a bad idea. I'm trying to figure out how to create connected sensors.. haven't done that before.

**Comment by IT-freak-Jake** [comment]
I would love to see this possibility in your already great integration. I've made a Node-RED subflow for resuming music on speakers after the TTS message and this thing would help me a lot with resuming music from YT when it's cast from other devices than ytube music player integration. If you would like to check my subflow here is a link
https://flows.nodered.org/flow/d0f137bc6323fd8200b8221cea22d713

**Comment by KoljaWindeler** [comment]
Please test https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20211206.01
