### ISSUE TITLE
Documentation Update to indicate that Google Chrome should be used.

### ISSUE THREAD

**Issue by thomb** [KoljaWindeler/ytube_music_player#127]
**Is your feature request related to a problem? Please describe.**
The documentation should be updated o indicate that the copy request header step should be done in Chrome. 

I was attempting to use Firefox, I was careful to follow the steps each time I tried, and failed to get the header in the correct format. The headers were validated correctly,  but the login failed.

Using Chrome worked like a shot.

**Describe the solution you'd like**
Minor documentation update to indicate that Google Chrome is the supported browser for this step. I have not tested, but this might just be isolated to Firefox.

**Comment by KoljaWindeler** [comment]
Thanks, done
