### ISSUE TITLE
Unable to complete setup

### ISSUE THREAD

**Issue by salsaman** [KoljaWindeler/ytube_music_player#136]
I followed the instructions referred to in the integration setup window, and obtained cookie data from a browser window. However when I paste this in to the setup, I get an error "Something with your cookie wasn't right. Format and fields are ok but the login failed". I have a YT music subscription and the cookie data was copied verbatim from the request headers in a logged in session.

The cookie data begins with "VISITOR_INFO1_LIVE=...:" and then contains several other pieces of data separated with ";" ending with "__Secure-3PSIDCC=...".

**Comment by salsaman** [comment]
Checking the logs, I discovered this:

2021-09-26 15:34:59 ERROR (MainThread) [custom_components.ytube_music_player.config_flow] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/config_flow.py", line 188, in async_check_data
YTMusic.setup(filepath = user_input[CONF_HEADER_PATH], headers_raw = c)
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 156, in setup
return setup(filepath, headers_raw)
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/setup.py", line 36, in setup
raise Exception(
Exception: The following entries are missing in your headers: cookie, x-goog-authuser. Please try a different request (such as /browse) and make sure you are logged in.

However, that field does exist in the cookie text, ie:
"x-goog-authuser": "0",

**Comment by KoljaWindeler** [comment]
It might help to use a chrome incognito session. 
Sadly there is nothing I can do about it.

**Comment by salsaman** [comment]
I see the same thing even after logging in from an incognito window.

Is it not possible to use an application password, or to set up oauth cloud access using client_id, client_secret ? The Google Nest integration uses something like this.

**Comment by KoljaWindeler** [comment]
Appears to be not possible .. please read https://github.com/sigma67/ytmusicapi/issues/10
