### ISSUE TITLE
Default sorting of songs in the playlist 

### ISSUE THREAD

**Issue by info-path** [KoljaWindeler/ytube_music_player#141]
Hello, this plugin works like charm for me but each playlist is sorted alphabetically not as it was created. Is there a way to keep the original songs order?

**Comment by KoljaWindeler** [comment]
Hi, I'm trying to figure out where I'm sorting .. the only thing I was able to find is the media_browser .. is that your point?

**Comment by info-path** [comment]
I don't think any app can sort songs. But they all display playlists chronologically as they were created. This add-on displays songs in the playlist sorted alphabetically by author. I would like the songs to be displayed in the order in which they were created.

**Comment by KoljaWindeler** [comment]
Please test https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20211206.01

**Comment by info-path** [comment]
Hey Kolja, I downloaded and replaced custom components with last beta version, removed cache, restarted HA but all ytm playlists are still sorted alphabetically

**Comment by KoljaWindeler** [comment]
have you disabled the sorting in the integration configuration menu?

**Comment by info-path** [comment]
No, I forgot... Now I deactivated "Sort results in the media browser" in the settings and my playlist is displayed correctly !!!! Wow, the playlist is displayed as it was created. Thank You for your hard work!

**Comment by KoljaWindeler** [comment]
Perfect
