### ISSUE TITLE
Casting to Airplay/HomeKit devices doesn't work

### ISSUE THREAD

**Issue by bobloadmire** [KoljaWindeler/ytube_music_player#143]
If I select an Airplay/homekit device such as an LG TV, TCL TV, or Roku device, all 3 devices have not responded to the airplay connection attempt. Chromecast devices work flawlessly. I haven't seen anything in the documentation about configuring for Airplay/homekit specifically.

**Comment by KoljaWindeler** [comment]
closed due to inactivity
