### ISSUE TITLE
Is it possible to use snapcast with this without going through MPD first? I.e: Stream the Music directly to a Pipe?

### ISSUE THREAD

**Issue by almostserious** [KoljaWindeler/ytube_music_player#147]
Would be great if I could use this similar to librespot by just piping the output so Snapcast can read it and redistribute to the speakers across the home

Haven't found a mention of this yet anywhere, and thought ill ask the experts here.

**Comment by KoljaWindeler** [comment]
This integration only figures out the mp3 url and passes that to the remote player .. therefore it can't pipe audio.
