### ISSUE TITLE
Pause, Stop not working...

### ISSUE THREAD

**Issue by gyenesadam** [KoljaWindeler/ytube_music_player#148]
Hello!

Sorry for my stupid question.

I'v got a tablet with Fully Kiosk browser & a fully kiosk integration in HA. In HA there is a mini media player and ayoutube music.
The Fully generated media player entity works perfectly, (with youtube music) I can set volume, start songs, change songs, but I unable to Pause or Stop them.

Where can I find a problem, what can I do? Could you or anybody help me?

Sorry, i am really amateur, but I want to learn and make something.

Thank's your help!

**Comment by KoljaWindeler** [comment]
Hi, sorry for the delay, please enable debug output, run a song and stop it. After that copy the log output to this ticket 
https://github.com/KoljaWindeler/ytube_music_player#debug-information

**Comment by KoljaWindeler** [comment]
closed due to inactivity, please comment if the problem still exists
