### ISSUE TITLE
Error on boot

### ISSUE THREAD

**Issue by elRadix** [KoljaWindeler/ytube_music_player#15]
Can you pls check why I am receiving this error:

```
Logger: homeassistant.components.media_player
Source: custom_components/ytube_music_player/media_player.py:74
Integration: Media player (documentation, issues)
First occurred: 8:57:39 PM (1 occurrences)
Last logged: 8:57:39 PM

Error while setting up ytube_music_player platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_

platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 43, in setup_platform
    add_entities([yTubeMusicComponent(hass, config)], True)
  File "/config/custom_components/ytube_music_player/media_player.py", line 74, in __init__
    self._api = YTMusic(config.get(CONF_HEADER_PATH, default_header_file))
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__
    self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie
    return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'
```

## System Health

version | 1.0.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.81
arch | x86_64
timezone | Europe/Brussels

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | HassOS 4.19
-- | --
update_channel | beta
supervisor_version | 2020.12.4
docker_version | 19.03.12
disk_total | 19.0 GB
disk_used | 10.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (8.6.0), AppDaemon 4 (0.3.2), WireGuard (0.4.0), Mosquitto broker (5.1), Home Assistant Google Drive Backup (0.102.0), SSH & Web Terminal (7.8.0), Visual Studio Code (2.9.1), API Consumer (0.101), Check Home Assistant configuration (3.6.0), TasmoBackup (1.04.02), chrony (1.1.2), JupyterLab Lite (0.3.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | storage
views | 18
resources | 27

</details>

**Comment by stboch** [comment]
Do you have it configured for both in yaml and in config_flow AKA the UI?

**Comment by elRadix** [comment]
yes both

**Comment by KoljaWindeler** [comment]
Looks like your cookies isn't complete

**Comment by stboch** [comment]
Drop 1 of them (just comment out the YAML) see if that does it

**Comment by elRadix** [comment]
what do you mean @stboch

**Comment by KoljaWindeler** [comment]
Well there is no real config flie entry. It will only generate the header file. You CAN delete that afterwards but it won't have an effect. Your cookie misses the 3papi... Field

**Comment by elRadix** [comment]
I have followed the guide and copied the cookie data as instructed

**Comment by elRadix** [comment]
@KoljaWindeler I copied the header data into a text file and searched for 3papi and I dont have that.

**Comment by elRadix** [comment]
Works now, had to search manually in all headers for the word 3PAPISID and then copied the associated header.
Thank you both of you for your quick response, I am closing this topic.
