### ISSUE TITLE
Randomly selecting a song from a list

### ISSUE THREAD

**Issue by danielccm** [KoljaWindeler/ytube_music_player#151]
I just added this integration, looks awesome! Thanks for the work.

I would add a feature that would play a random song from a given list, never the same one twice. Is that even possible? I'm no programmer...

**Comment by KoljaWindeler** [comment]
Hi, have a look at 
"What is Shuffle vs Random vs Shuffle Random"
At the faq https://github.com/KoljaWindeler/ytube_music_player#faq

**Comment by danielccm** [comment]
Nice! Thanks!
