### ISSUE TITLE
INTREGRATION CAN'T ADD

### ISSUE THREAD

**Issue by fabHAgithub** [KoljaWindeler/ytube_music_player#152]
**addition of integration does not leave this page, it appears a little ball rotating forever and at the end appears: error**

![image](https://user-images.githubusercontent.com/85220859/143670288-ea913f09-fa28-48f3-9179-a24890bfe863.png)

**Comment by KoljaWindeler** [comment]
What's in the log?

**Comment by fabHAgithub** [comment]
> What's in the log?

I don't no what happened, but now thats ok I can paste the codes. Thanks for the attenton. :)
