### ISSUE TITLE
mini-media-player resets playback time indicator on volume change

### ISSUE THREAD

**Issue by lukaszwawrzyk** [KoljaWindeler/ytube_music_player#153]
Hi :)
I am really happy with this integration. I am using since I got nest mini instead of my custom samsung tv youtube playing.
I observed couple of small usability issues.

1. I see that when I change the volume, the current playback/seek status resets to 0:00 and doesn't show the true information. This happens to card linked to media_player.ytube. The card linked to media_player.nest_mini shows fine.

2. Can the communication between nest mini and ytube be somehow bidirectional? When I pause nest mini with my hand or voice, ytube keeps increasing playback time going to infinity. After like 30 min, when I want to resume it, touching doesn't work, playing/pausing in ytube doesn't work either (I think even if I paused it in ytube in the first place). I need to switch track and then it reconnects to nest and starts playback.

3. A little feature request, can you add a service to remove video from playlist? I have a special button to both like the video and store it on a special playlist, but I can't undo this. I know that there is an automatic playlist for liked videos, but this won't work for my use case.

**Comment by KoljaWindeler** [comment]
Hi @lukaszwawrzyk 
i've tried to reproduce your observation of 1.) but it works fine here .. i can set the volume and nothing happens to the progress bar .. I thing this is more a bug at the mini-media-player (if at all)

2. could you enable logging (see readme) and post the log around the time you press "pause" on the nest-mini?
30min might be some sort of timeout on the next mini .. please pause the playback and check the log if you see some state chagnes

3. makes sense .. I'll add that to the to-do list .. yes.
JKW

**Comment by KoljaWindeler** [comment]
Please test https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20211206.01

**Comment by lukaszwawrzyk** [comment]
Thanks, will do!

1. It happens with standard media card for me as well: https://photos.app.goo.gl/mmbBXEdEdk7QmsEK8 I recorded a reproduction. I need to allow song play for like half of its time, then change the volume, and it seeks back to 0 (music continues, but the bar changes). If I just start the song, seek to the middle manually and then change volume, the progress goes back, but just a little.
2. I will check. It might be some timeout ineed. My current workaround is just to start a random playlist if there is nothing to resume.

**Comment by KoljaWindeler** [comment]
Interesting .. thanks for the video .. could you open another tab and watch the attributes of the player? 
especially media_duration and media_position. Those should be used by the mini-media-player. You are running version 1.15 of the mini-media-player, right?

**Comment by lukaszwawrzyk** [comment]
@KoljaWindeler I will work on collecting further debug information. For now I want to note, that the recording shows standard media card, so it is not even mini-media-player.

Also I tested new release. I had to delete integration and add it again, as it created second media_player entity when I changed config to enable sensor. After removing integration, restarting HA and adding integration again it works well. I updated my playlist and lyrics card and it works well with the sensor. I also can correctly keep my plalist in sync with like status thanks to delete from playlist feature which works flawlessly. Thanks!

**Comment by lukaszwawrzyk** [comment]
Ok, I recorded states. Top one is nest_mini and bottom one is youtube_music. Note the changing volume level. It changes media_position_updated_at in youtube_music. The media_position and media_duration are set at the beginning of playback and they don't change at all. I think that the lovelace card manages the progress and when update time changes, it takes the media_position again, but it was only set at the beginning of playback.
https://user-images.githubusercontent.com/10235198/145094974-6fb291d8-42f4-4be4-9b70-740cd634e441.mp4

**Comment by KoljaWindeler** [comment]
thanks, found it, fixed it https://github.com/KoljaWindeler/ytube_music_player/commit/5b4b87add84134357004d1628bfc1318c8741eb4
