### ISSUE TITLE
Error config flow message when trying to add integration

### ISSUE THREAD

**Issue by Quinnod345** [KoljaWindeler/ytube_music_player#159]
When trying to add the integration in home assistant, an error message appears, saying that there was an error with the confit flow. Is there a way that I can fix this? Or is this an error with the custom integration itself?

thanks

**Comment by KoljaWindeler** [comment]
Hi, what is written in the log when you try to add it?

**Comment by Yonny24** [comment]
oh sorry., I replied last night but looks like I forgot to hit send.

I see you pushed a new version out now. Just testing and it's looking better thanks!

**Comment by KoljaWindeler** [comment]
Great
