### ISSUE TITLE
Long term - Multiple Accounts

### ISSUE THREAD

**Issue by BramWarrick** [KoljaWindeler/ytube_music_player#16]
I don't believe this is currently a feature of the solution, but I'd like to have multiple accounts. This could be multiple ytube music player instances...  or whatever.

The use case is simple: she has a Nest mini in an area, I have a separate one elsewhere. We each have our own ytm accounts. I'd love to be able to play music for her with HA. I want that for me, too. Different music preferences, playlists, etc.

I know this won't be the near-term goal of the project, but if it can be part of a later version, I'd be a BIG fan.

**Comment by KoljaWindeler** [comment]
Hi, I tend to believe that this is already possible. You can create two header files and add the player twice with two sets of input selects. You'd have to link the file and input selects explicitly to the player but that's alright possible. Will try tomorrow and add some details here
Kolja

**Comment by KoljaWindeler** [comment]
Have a look at:
https://github.com/KoljaWindeler/ytube_music_player/blob/main/Multiple_accounts.md

I can't test two cookies as I only have one account. But I thing it should work. I'd suggest to create two yaml files in the package folder. Let me know if it worked

**Comment by KoljaWindeler** [comment]
Closing this due to no feedback
