### ISSUE TITLE
integration panel opens/lists songs then closes down but continues to play music

### ISSUE THREAD

**Issue by Yonny24** [KoljaWindeler/ytube_music_player#161]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
Starts playing on homeassisistant media player (DLNA Digital Media Renderer) - songs appear/panel opens initially but then it closes down but continues playing. Lose control of the ytube panel after this.

Also fails to play on sony srx player integration

Reloaded the cookie.

**Version**
Home Assistant 2021.12.0

**To Reproduce**
open media player, click on album and lay. View ytube panel player - closes down after 5 seconds.

**Additional context**

Debug lohgs:

`This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:211
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 6:22:22 PM (22 occurrences)
Last logged: 6:22:27 PM

- self decoded URL via cipher
[E] async_get_url
- forwarding url to player media_player.srs_x77
[E] async_get_track
[E] play_media

This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:201
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 6:22:24 PM (6 occurrences)
Last logged: 6:22:42 PM

[S] async_check_api [E]
[S] async_update_remote_player(Input / current media_player.srs_x77) [E]
[S] async_get_cipher [E]
[S] _tracks_to_attribute [E]
[S] async_sync_player ... media_player.srs_x77 [E]
`

![image](https://user-images.githubusercontent.com/64428686/145730364-18791db9-a26f-4625-a3db-f3459d3329b6.png)

Thanks

**Comment by KoljaWindeler** [comment]
Hi, thanks. Is there a little more of the log file? 
Also: Are you running the latest (beta) version?

**Comment by Yonny24** [comment]
HI.
Sorry, my HA logs are only showing this.

`This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:211
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 6:28:17 PM (64 occurrences)
Last logged: 10:11:52 PM

- using stream 6
- self decoded URL via cipher
[E] async_get_url
- forwarding url to player media_player.srs_x77
[E] async_get_track

This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:201
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 6:28:17 PM (20 occurrences)
Last logged: 10:11:57 PM

[S] async_check_api [E]
[S] async_update_remote_player(Input / current media_player.srs_x77) [E]
[S] _tracks_to_attribute [E]
[S] async_sync_player ... media_player.srs_x77: on -> on [E]
[S] async_sync_player ... media_player.srs_x77 [E]
`
Is this the version?

![image](https://user-images.githubusercontent.com/64428686/145737798-c4b5eec4-e093-4bb9-a4a0-8c5f2015cf20.png)

**Comment by KoljaWindeler** [comment]
please update to the latest release. that should be fixed. Please reopen if you still have issues after the update
