### ISSUE TITLE
i dont found integration ytube

### ISSUE THREAD

**Issue by jybi89** [KoljaWindeler/ytube_music_player#164]
Hi, thanks for your job :)

I can't find the YTUBE integration, do I need to add a resource?

thanks for your futur answer.
jybi89

**Comment by KoljaWindeler** [comment]
You can install it via HACS ..

**Comment by jybi89** [comment]
thx

ok, that's it, but then where do I put the cookie? in the video tutorial we added it in the integration, but today, where to put it?

**Comment by KoljaWindeler** [comment]
Nothing changed. So the step-by-step video should work as is. 
Just to mention it: 2021.12 has an issue with the Chromecast integration. I've downgrade for the meantime

**Comment by jybi89** [comment]
arf....

i d'ont found integration, am I forgetting something ...

https://user-images.githubusercontent.com/54111386/146754054-f4bd8935-1ccd-4100-bce5-5f42ab183ed2.mp4

![image](https://user-images.githubusercontent.com/54111386/146754282-7f57245b-0cfb-432d-8ec0-6435d4040f40.png)

**Comment by KoljaWindeler** [comment]
I think this isn't HACS .. please Google for and install HACS. It's a great addition to Homeassistent anyway

**Comment by jybi89** [comment]
HACS it's ok for me :

![5](https://user-images.githubusercontent.com/54111386/146756120-84d16ed1-dbd0-470e-b7f9-a69a94ad98e6.gif)

**Comment by KoljaWindeler** [comment]
Ah .. hm .. ok so you found and installed it but it still doesn't show up .. got you... Have you restarted Homeassistent? Fresher the browser window after that restart?

**Comment by jybi89** [comment]
OMG     .........  
I'm ashamed..........
it was enough to clear the cache

**Comment by KoljaWindeler** [comment]
;)
