### ISSUE TITLE
No Information at "total_tracks"

### ISSUE THREAD

**Issue by gentoair** [KoljaWindeler/ytube_music_player#165]
**Describe the bug**
I think "media_player.ytube_music_player", "total_tracks" doesn't work anymore. The List of the Tracks will be not shown also.

**Version**
20211213.01

**To Reproduce**
I am using this code:
`        content: >-
          {% if is_state('media_player.ytube_music_player','playing') %}Jetzt
          spielt Track {{ state_attr("media_player.ytube_music_player",
          "current_track")+1 }} von {{
          state_attr("media_player.ytube_music_player", "total_tracks") }}{%
          else %} **Jetzt spielt:** Musikanlage ist ausgeschaltet{% endif %} `

**Additional context**
![image](https://user-images.githubusercontent.com/73964422/147919634-05a2dd26-3b2b-49f6-b06e-e2b40ff13696.png)

**Comment by KoljaWindeler** [comment]
Please read 
https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20211206.01
