### ISSUE TITLE
Start playing when dropdown selection is made

### ISSUE THREAD

**Issue by Leo-Stanoev** [KoljaWindeler/ytube_music_player#169]
**Is your feature request related to a problem? Please describe.**
Hi, currently I have implemented the dropdown of the playlists, and they are populated and all, but when I click any of them nothing changes, not sure if intended or bug as I can't find any posts on it so far.

**Describe the solution you'd like**
Start playing a playlist once selected from dropdown or via call-service of a button.

**Describe alternatives you've considered**
 I thought about creating a "Play" button that would call the play service and pass in the contents of the playlist selector but I don't know the attribute to pass through e.g. "input_select.ytube_music_player_playlist. _contents or value _ etc.

**Additional context**
Thanks!

**Comment by KoljaWindeler** [comment]
Hi,. If you really want to use the drop-down you just have to "turn on" the player afterwards ... I'd highly recommend to use service calls and get rid of those ugly drop-downs  .. but hey .. up to you

**Comment by Leo-Stanoev** [comment]
I'd love to use a service call, right now I have one as a button but I would love to be able to easily select a new playlist and start playing immediately from front end, without having to go into the player's selector -> playlist -> specific playlist.

I'll look into creating a dropdown which does service calls on selection and I can pass the playlist IDs there but then I'd have to hardcode the IDs in there for the data. 

type: custom:button-card
name: play test
tap_action:
  action: call-service
  service: media_player.play_media
  service_data:
    entity_id: media_player.ytube_music_player
    media_content_id: PL0wqt_um4x0bsdViTJBmnl6KGMoSqxfZy
    media_content_type: playlist

**Comment by Leo-Stanoev** [comment]
Mostly what I mean is I'd like to get the whole list of playlist available and when I click on one it just starts playing it e.g. Rock

![image](https://user-images.githubusercontent.com/50144205/149562483-154aa593-aa7a-43c5-a1eb-6ad2566a63a9.png)

**Comment by Leo-Stanoev** [comment]
Can you tell me how to access the input_select.ytube_music_player_playlist 's state/value to get the id of the currently selected playlist please?

**Comment by KoljaWindeler** [comment]
I don't think that you can get it from the playlist dropdown .. what is the media_id once you've "turned on"

**Comment by Leo-Stanoev** [comment]
From what I've seen the input select doesn't have an id : c 

![image](https://user-images.githubusercontent.com/50144205/149565964-e21ce1d1-17b8-45fc-8f24-fe57322f5aa2.png)

media player on the other hand is working great, below is a playlist's id and type
![image](https://user-images.githubusercontent.com/50144205/149566059-0298770f-4bc7-412e-b26f-2d2dfc2601d4.png)

Do you think there is any way to pull the playlists' IDs similar to how you have them with the whole selection screen bit, but I want to pop them into an entities with a custom input select which I can actually pass through the playlist IDs.

If not this way, maybe another idea on easy playlist selection and play?

Thanks for helping btw!

**Comment by stboch** [comment]
here is my example.

```
alias: YTMusic Start
description: ''
mode: single
trigger:
  - platform: state
    entity_id: input_select.ytube_music_player_playlist
    for:
      hours: 0
      minutes: 0
      seconds: 2
condition: []
action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.ytube_music_player
```
