### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [KoljaWindeler/ytube_music_player#17]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by KoljaWindeler** [comment]
Honestly ... I think this is to advanced for this small integration, but thanks a lot for the help!

**Comment by KTibow** [comment]
I couldn't parse that. Would you mind answering the questions in the bullet points?

**Comment by KTibow** [comment]
@KoljaWindeler Sorry to bump, but should I close this issue, or create a PR?

**Comment by KoljaWindeler** [comment]
Hi, thank for your support. At this point I'm good without github actions. I'll close it.

**Comment by KoljaWindeler** [comment]
Hi, you've offered your help with github actions a while back ... I do have a use-case, but I'm not sure if that's possible.
I'd like to have an action that should make sure that the "version" attribute always is the same as the version that I'm releasing .. 

pseudo-code:
 before: release
 action: update "version" line in custom_components/ytube_music_player/manifest.json to match current tag and update file if not (or prevent the release) 

is something like this possible? and do you know how?

**Comment by KTibow** [comment]
Did you solve this, and if not, are you still interested? (Yes I know this is an old issue, I stopped checking my GitHub notifications for a bit)

**Comment by KoljaWindeler** [comment]
No, never solved it ... Not even sure if it's possible

**Comment by KTibow** [comment]
I must admit my GitHub Actions skills are a bit rusty, but from my understanding you can't edit the files in a release, because the release snapshots the files before a GitHub Action can get to them.
However, you can create a GitHub Action which will first edit the files, then release it on its own, and manually trigger it.
Would you be interested in that?
