### ISSUE TITLE
Clicking on album under albums produces error

### ISSUE THREAD

**Issue by Madj42** [KoljaWindeler/ytube_music_player#173]
This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:256
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 4:24:08 PM (3 occurrences)
Last logged: 4:24:19 PM

[S] async_check_api [E]

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/browse_media.py:145
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:55:15 PM (3 occurrences)
Last logged: 4:24:19 PM

[139744108759408] Error handling message: Unknown error
[139744116149456] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1168, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1966, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 145, in build_item_response
    thumbnail = item['thumbnails'][-1]['url']  # here to expose it also for the header
TypeError: 'NoneType' object is not subscriptable

**Describe the bug**
In the media browser, access ytube music, select albums, click on album art itself and it gives unknown error.  Clicking play button plays album just fine but when I want to see the tracks of the album like this, it errors.

**Version**
20220120.01

**To Reproduce**
See description.

**Additional context**

Thanks

**Comment by KoljaWindeler** [comment]
Hi, confirmed. I'll check what changed in the API. Thx

**Comment by KoljaWindeler** [comment]
Please check https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20220123.01

**Comment by Madj42** [comment]
Works great and you can close this.  One thing I noticed on the same front is that I don't have library artists in the media browser.  I have uploaded artists though.  Just wondering if this is also a bug.

**Comment by KoljaWindeler** [comment]
Not a bug, but for some reason missing in the API ..
