### ISSUE TITLE
Two media players after reinstallation of the integration

### ISSUE THREAD

**Issue by mfabiani53** [KoljaWindeler/ytube_music_player#174]
I reinstalled from scratch the integration from the UI and after all went succesfully, i noticed actually i have 2 media_player.ytube_music_player the second named media_player.ytube_music_player_2.
How to delete one of them and which one is correct?

![Schermata 2022-01-23 alle 12 48 13](https://user-images.githubusercontent.com/37701688/150676936-f3d4ca41-039b-4848-b034-60b2f563d4e3.png)

They are not editable so cannot delete or change the name...

![Schermata 2022-01-23 alle 12 57 50](https://user-images.githubusercontent.com/37701688/150677261-a5dc19e9-2d11-4861-a9ad-c0e17a37c1c4.png)

I am using the latest release from HACS

Thanks

**Comment by KoljaWindeler** [comment]
Honesti .. no idea ... I'd remove both or whichever  is shown in the integration menu ...

**Comment by mfabiani53** [comment]
How to remove them?

**Comment by mfabiani53** [comment]
Ok, reinstalled again the integration and now i have only 1 media_player....
