### ISSUE TITLE
problems casting youtube music from android to soundbar after using youtube integration.

### ISSUE THREAD

**Issue by Valerossi0** [KoljaWindeler/ytube_music_player#178]
Hello there.
As a beginning HA user i was able to integrate your youtube music player via hacs, and got it working with takeing the cookies via google developer tools in the browser. But because of my lack of knowledge it didnt workout for me as planned so i unistalled the repository. I used  the youtube music player with the standard media card, and my soundbar (chromecast integration) as playing device. However when i cast youtube music now to my soundbard nothing happens. i got connected, but it won't play the music. When i open google home i see that the soundbar is on, but it says no media selected. when i try to start to play via google home the soundbar is going to play the same playlist as integrated in HA. I can stream my youtube music to all speakers in the house, but not the soundbar anymore. It looks like something in HA still masters the soundbar, but i cant find it. I did reset the bar. resetted google home, and did a youtube music cookie wipe with developer tools. Still the same issue. i got connected to soundbar, but it wont play any. Maybe you got a idea what happened here and can help me figure out. Thanks you for your good work :) Greeting R-J

**Comment by KoljaWindeler** [comment]
Hi, sorry for the delay .. please raise a ticket at the integration owner of your soundbar .. i don't think that there is anything I can do
