### ISSUE TITLE
include "Albums" in input_select.ytube_music_player_source

### ISSUE THREAD

**Issue by jybi89** [KoljaWindeler/ytube_music_player#180]
Hi !
I read readme file, but i don't think that possible. Idealy, it should include "Albums" of YouTubeMusic in the input select : see my idea, is it possible soon? 

`
#############################################################
#############################################################
  ytube_music_player_source:
    name: Fonte
    icon: mdi:music-box-multiple
    options: # ne pas modifier
    - "Playlist Radio"
    - "Playlist"
    - "Albums"  <<<<<<<<-----------------------------|
  ytube_music_player_speakers:
    name: Auto Falantes
    icon: mdi:speaker
    options: # ne pas modifier
    - "loading"
  ytube_music_player_playlist:
    name: Playlist
    icon: mdi:playlist-music
    options: # ne pas modifier
    - "loading"
  ytube_music_player_playmode:
    name: Modo
    icon: mdi:playlist-music
    options: # ne pas modifier
    - "Shuffle"
    - "Random"
    - "Shuffle Random"
    - "Direct"
    `
    
![image](https://user-images.githubusercontent.com/54111386/152675660-d5ce4a48-3278-4bb0-854d-f3193cb6af25.png)

but input_select.ytube_music_player_playlist pin up (loaded) always my playlist and no loading my albums.

I use this card : 
`
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_select.ytube_music_player_speakers
        name: Sortie Audio
      - entity: input_select.ytube_music_player_source
        name: playlist / Radio
      - entity: input_select.ytube_music_player_playlist
    state_color: false
  - type: horizontal-stack
    cards:
      - type: button
        tap_action:
          action: toggle
        entity: media_player.ytube_music_player_recording
        name: Play !
        icon_height: 40px
      - type: button
        tap_action:
          action: toggle
        entity: input_boolean.ytube_music_player_playcontinuous
        name: Continue
        show_state: false
        show_icon: true
        icon_height: 40px
      - type: button
        entity: input_select.ytube_music_player_playmode
        show_state: true
        show_icon: true
        icon_height: 50px
        name: ' Mode'`

![image](https://user-images.githubusercontent.com/54111386/152675785-d67ce781-956e-4922-adcb-ab4d548c40ec.png)

sorry for my english ;)

**Comment by KoljaWindeler** [comment]
HI, no, that won't work and I won't implement that ... the reason is that I don't really like the dropdowns anyway.

There are way nicer options like the media_browser or the mini-media-player shortcut buttons .. or simple buttons 

... for example this here https://community.home-assistant.io/t/youtube-music-media-browser/226367/660?u=jkw is a nice dashboard with many options for my son to listen to "albums" (audiobooks in this case, but that's the same for YouTubeMusic)

**Comment by jybi89** [comment]
ok, thanks, then I will use Node Red and RFID tag ;)
