### ISSUE TITLE
Tracklist and lyrics stopped working

### ISSUE THREAD

**Issue by Shalobee** [KoljaWindeler/ytube_music_player#186]
**Describe the bug**
It appears the tracklist and lyrics no longer populate when using markdown cards.

**Version**
20220303.01

**To Reproduce**
start ytube with markdown lovelace ui with lyrics and tracklist setup.

**Additional context**
It worked a few months ago and after major home assistant update it seemed to stopped working.

Thanks

**Comment by picotrain77** [comment]
I had this issue also and recently fixed it my firstly redoing the config options of the integration and importantly selecting the "show advanced configuration" option and in the following advance options page, checking the box for
"Create sensor that provide extra information" as this is now where the track list and lyrics appear to come from.

You should then get a new entity called sensor.ytube_music_player_extra and if you look at attributes you will find the additional info you need for the markdown cards.

If you are using the markdown cards from here:
https://github.com/KoljaWindeler/ytube_music_player/blob/main/package/markdown.yaml
they are still referencing to the old entity attributes for track list and lyrics etc.

I just worked through the example yaml and replaced any state_attr references that no longer exist and replaced them with some of the new ones from the new sensor.ytube_music_player_extra.

HTH

**Comment by Shalobee** [comment]
This worked for me as well. After I worked through changing the sensor entities I also found I needed to get a new token for youtube music and everything started working again. Thanks for pointing me in the right direction.
