### ISSUE TITLE
Critical - Can't Remove default output devices and set new output device if it's removed from HA Devices

### ISSUE THREAD

**Issue by mkopnsrc** [KoljaWindeler/ytube_music_player#189]
*Enabling DEBUG Output in DevTools doesn't log below described issue*

**Describe the bug**
Can't seems to remove default output device from ytube_music_play Configuration if the selected output devices are completely removed from HA. Also If I try to select new default output device, it prevents from saving the config because non-existed device listed in config. Please see below screenshot error message in red and highlighted devices that were removed but still exists in config and can't be removed and no option to deselect or remove them.

![image](https://user-images.githubusercontent.com/2036998/162856248-b4631e9d-a9b7-4f45-9362-6cb0b315552e.png)

**Version**
Home Assistant: | 2022.4.2
HACS - Integration version: | 1.24.4
HACS - Frontend version: | 20220401183545
HACS - ytube_music_player version: | 20220303.01

**To Reproduce**
1. Go to 'HACS - add yTubeMediaPlayer integration' then 
2. Go to HA Configuration -> Devices & Services -> "+ Add Integration" -> search for "ytube_music_player" Select and Add integration
3. Go to HA Configuration -> Devices & Services -> 'ytube_music_player'  Configure
4. under "Select the default output device" -> select one of your media player -> then click submit
5. Lets say you remove the selected media player from your HA devices completely and now you select new default media player in 'ytube_music_player', you will be able to select new media player, however you won't be able remove previously selected media player and your new output device config can't be saved.

Thanks

**Comment by kariudo** [comment]
I ran into this same issue as well, for anyone else, the only reasonable workaround is to copy the cookie from the configuration screen, then delete the integration, and re-add it, pasting your cookie back in and selecting the new appropriate default player.

**Comment by Bruhildo** [comment]
Just deleted a media player entity and I am facing the same issue.

If at least we could avoid the dropdown list on the configure page, this could be resolve by just deleting the reference for teh deleted media player entity.

**Comment by KoljaWindeler** [comment]
please try with the latest version

**Comment by Bruhildo** [comment]
@KoljaWindeler Perfect. Working great now. Thanks a lot for the update and all good work on the integration.
