### ISSUE TITLE
Support join/unjoin for media_player

### ISSUE THREAD

**Issue by brnstd-dev** [KoljaWindeler/ytube_music_player#197]
**Is your feature request related to a problem? Please describe.**
Currently, we cannot stream audio to multiple speakers using this integration. If support for join/unjoin was added, this would allow users to take advantage of kalkih's mini-media-player speaker-group: https://github.com/kalkih/mini-media-player#speaker-group-object

**Comment by KoljaWindeler** [comment]
for some integration (like cast devices) you can create a group of speakers that appears as dedicated entity within homeassistant. using that entity as "remote_player" make all speaker in that group play simultaneously.
I guess that's about as far as this integration will go. I can't make sure that multiple speaker are in sync.
