### ISSUE TITLE
No module named 'integrationhelper'

### ISSUE THREAD

**Issue by dejan2101** [KoljaWindeler/ytube_music_player#2]
Hi, i'm trying to add new integration with config flow in HA and i'm getting this error, any idea what (if anything) i'm doing wrong?

Logger: homeassistant.config_entries
Source: config_entries.py:537
First occurred: 18:51:14 (2 occurrences)
Last logged: 19:00:55

Error occurred loading configuration flow for integration ytube_music_player: No module named 'integrationhelper'

**Comment by dejan2101** [comment]
nevermind, just updated and it works :)

**Comment by KoljaWindeler** [comment]
Hi, please update to the latest version and restart home assistant.

**Comment by KoljaWindeler** [comment]
;)
