### ISSUE TITLE
get_playlist playlist KeyError: 'contents'

### ISSUE THREAD

**Issue by lowgoz** [KoljaWindeler/ytube_music_player#20]
```
`Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:811
Integration: YouTube Music Player (documentation)
First occurred: 22:06:27 (1 occurrences)
Last logged: 22:06:27

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 406, in _update_playlists extra_info = self._api.get_playlist(playlistId=playlist['playlistId']) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 100, in get_playlist playlist['tracks'].extend(parse_playlist_items(results['contents'])) KeyError: 'contents'`
```

Seems like everything is set up correctly 
- HACS install worked normally
- grabbed cookie and all seems to be fine with the configflow
- config.yaml entered correctly
- Seeing speakers and input selects in the ytube entities that were created
- Im able to turn the ytube media player on and it speaks to my devices
- input_select.ytube_music_player_playlist is borked and stuck on "loading"

Any ideas?

**Comment by KoljaWindeler** [comment]
nope .. at least no what causes this .. if the playlist won't return the amount of track ('count' - field) I'll call the get_playlist method with that playlist ID. This fails but is out of my code space. I can create a hot fix by moving this line into the try/catch which should work around the issue and return a fix number of 25 for the failing playlist. But I'll also forward this ticket to the guys of ytmusicapi.
Thanks for reporting

**Comment by lowgoz** [comment]
@KoljaWindeler that worked! thank you!

**Comment by lowgoz** [comment]
Weird. Worked perfectly for 8 hours today then restarted home assistant and got this

`Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 396, in _update_playlists self._playlists = self._api.get_library_playlists(limit = 99) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 29, in get_library_playlists results = find_object_by_key(nav(response, SINGLE_COLUMN_TAB + SECTION_LIST), File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 148, in nav raise err File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 142, in nav root = root[k] KeyError: 'contents'`

Back to "loading" playlist status!

**Comment by simonmannsfeld** [comment]
@lowgoz I just want to point out something.

Short time before of your reported issue, many youtube and google servers were down. Can you proof that this was not the problem?

To your error: It seems like you do not have any playlist at your google account. Can you proof that you're not using a brand-account for youtube music?

**Comment by lowgoz** [comment]
@simonmannsfeld i pulled a new cookie from an incognito session and it seems to have resolved itself. 
Just using a normal google account and you're right - it might have been related to the outage. 
Very weird but looks resolved!
