### ISSUE TITLE
YTUBE and Raspiaudio

### ISSUE THREAD

**Issue by jybi89** [KoljaWindeler/ytube_music_player#201]
Hi, thanks for your job !
I use Google Home and Google Mini, it's OK, but : 

I use a Raspiaudio, is it compatible with YTube?

I can broadcast a radio or mp3 on my raspiaudio but YTube does not work on it.

It goes into Idle status instead of Playing.

Thanks for your answer :)

**Comment by MagicPelikan** [comment]
Hi jybi89, 

I have the same issue. 
Did you find any solution or workaround ?
Thank you!

**Comment by KoljaWindeler** [comment]
Hi, this can't be fixed on this end. This integration generates a url and forwards it to what ever player you use. 
That player has to be able to stream from a url. 

Google cast is, raspiaudio might not. If so please raise a ticket at raspiaudio to add streaming from url. 
Thanks
