### ISSUE TITLE
Can't pass setup first screen

### ISSUE THREAD

**Issue by HydrelioxGitHub** [KoljaWindeler/ytube_music_player#205]
I've watched the video, the setup text and the screens but i'm stuck at the first screen of the setup as HA is telling me a mandatory fill is empty. But I can't see any empty field.

Also, ticking advanced options does nothing 

![image](https://user-images.githubusercontent.com/15862735/182134053-37a2539e-b9bd-42ed-be1b-12bf13a896b6.png)

**Comment by VOIDREP** [comment]
same issue here
