### ISSUE TITLE
Multi instance

### ISSUE THREAD

**Issue by AviFix** [KoljaWindeler/ytube_music_player#206]
Hi

is there a way to play a different playlist via different speakers at the same time?

Thanks

**Comment by KoljaWindeler** [comment]
Yes simply create two instances of the yt music player

**Comment by AviFix** [comment]
Could you please show me an example?

**Comment by D-Bullock** [comment]
I'm also unsure how to create a second instance.

**Comment by KoljaWindeler** [comment]
Well simply add the integration twice. Same cookie data, different name

**Comment by D-Bullock** [comment]
Worked for me!

**Comment by AviFix** [comment]
Got it wotking

Thanks
