### ISSUE TITLE
Feature request: Unencrypted HTTP streaming

### ISSUE THREAD

**Issue by hacker1024** [KoljaWindeler/ytube_music_player#209]
Some old DLNA DMR renderers do not support HTTPS URLs. Attempting to play back HTTPS media results in an error like the following:

`docker-home-assistant-start[2116]: 2022-09-03 23:52:21.005 ERROR (MainThread) [homeassistant.components.dlna_dmr] Error during call async_play_media: UpnpActionResponseError('Error during async_call(), status: 500, upnp error: 716 (Resource not found)')`

If the Youtube Music API supports HTTP streaming, an option to use it would be great. If not, the songs could be proxied.

This is likely the cause of #187, as there's nothing else stopping DMR from working.

**Comment by KoljaWindeler** [comment]
please try https://github.com/KoljaWindeler/ytube_music_player?tab=readme-ov-file#method-2-owntone-server-as-proxy
