### ISSUE TITLE
Add support for MediaSource

### ISSUE THREAD

**Issue by dgtal1** [KoljaWindeler/ytube_music_player#21]
Hi,
The work you've done is great and I'm looking forward to it being developed further. 
One thing that I think would be very useful is to add MediaSource support, so one could browse YouTube music from a side panel or - even better - from any player which supports MediaSource (currently Chromecasts). The rationale behind is that one doesn't have to add another entity to the UI to browse files. For instance I'd love to be able to pick a YouTube music playlist directly from my Chromecast entity in the UI. That's what Media Source is all about.

I mean this thing here: https://github.com/home-assistant/core/tree/dev/homeassistant/components/media_source

Looks like Xbox and Netatmo integration added it so far, so not too many examples, but still something to explore.

Keep on doing the great work!

**Comment by stboch** [comment]
Being done as part of work for issue #14

**Comment by KoljaWindeler** [comment]
Closing as this is a duplicate
