### ISSUE TITLE
Musiccast device airplay

### ISSUE THREAD

**Issue by nitylouta** [KoljaWindeler/ytube_music_player#211]
Hello !
I integrated ytube on my HA (on my Ipad)
When I configure it, I can choose the main device for audio outut so I selected my "Ampli" device (created from Musiccast)
But when I stream music on the lovelace integration my "Ampli" choose the "Server" input to read the streaming.
So I have no sound.
Is there a way to modify this and get the stream go to "Ampli" but airplay input?

Thanks in advance

**Comment by KoljaWindeler** [comment]
please try https://github.com/KoljaWindeler/ytube_music_player?tab=readme-ov-file#method-2-owntone-server-as-proxy
