### ISSUE TITLE
Input Select - Name not showing for Playback Devices

### ISSUE THREAD

**Issue by abdalians** [KoljaWindeler/ytube_music_player#213]
When I try to select the playback device, I see alot of options but only some of them actually show the name of the device. 

**Version**
20220415

**To Reproduce**
1. Go to 'HA > Media > Playback Device'
2. See some devices without names and others with names
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/9934227/197019824-ea6d0c9c-315c-4cf1-a51b-b2262b899ae5.png">

Thanks

**Comment by KoljaWindeler** [comment]
is this still an issue? I guess this is a Homeassistant bug anyway
