### ISSUE TITLE
Sound laggy when using integration

### ISSUE THREAD

**Issue by flololan** [KoljaWindeler/ytube_music_player#216]
I installed the integration and have the media player like in the youtube video. I can select music and everything, so no problems there.
But when I select something ( no matter if a song or playlist) the playback will stutter HARD (like play the fraction of a second, 5 seconds nothing again a fraction of a second again nothing etc.)

**Version**
20220415

**To Reproduce**
1. Go to your dashboard with your media player
2. Click on media library
3. Select any song/playlist

**Additional context**
I am using a Chromecast as default player and Home Assistant runs on a Raspberry PI with HASSOS

Thanks

Logs:
![image](https://user-images.githubusercontent.com/12832544/198898964-0f5618f5-1a93-4a31-b33f-1e4265ce286a.png)

**Comment by KoljaWindeler** [comment]
I don't think that this is related to this integration. The integration will pass the URL to the media_player and the rest is up the it
