### ISSUE TITLE
Artist information missing when browsing album library

### ISSUE THREAD

**Issue by luvienm** [KoljaWindeler/ytube_music_player#218]
**Is your feature request related to a problem? Please describe.**
When using the media selector to browse library albums, only the album name displays, not the artist name.

**Describe the solution you'd like**
It would be valuable to be able to see the artist information

**Describe alternatives you've considered**
None

**Additional context**
Please see the screenshot which shows artist names missing
<img width="1168" alt="screenshot" src="https://user-images.githubusercontent.com/74087617/201337519-e43a785f-b74b-4be9-8fae-fb8957e5e74b.png">

Thank you.

**Comment by KoljaWindeler** [comment]
Done in https://github.com/KoljaWindeler/ytube_music_player/commit/687136e6f894b7dda11238fbcd9d1e1171506cda
