### ISSUE TITLE
Error on Youtube login

### ISSUE THREAD

**Issue by ngalatis** [KoljaWindeler/ytube_music_player#221]
Although I'm following the procedure described in the video I always get a 403 error:
`YouTube returned a 403 error, meaning that you login data are not longer valid. Please update the cookie`

Incognito browser, premium account, 2FA.

Funny enough I had setup the integration a few months ago but it was misbehaving so I removed it and installed again and now I have this issue.

HA log:
```
Logger: custom_components.ytube_music_player.const
Source: custom_components/ytube_music_player/const.py:331
Integration: yTubeMediaPlayer ([documentation](https://github.com/KoljaWindeler/ytube_music_player), [issues](https://github.com/KoljaWindeler/ytube_music_player/issues))
First occurred: 18:03:32 (5 occurrences)
Last logged: 18:22:03

The entered information has the correct format, but returned an error 403 (access forbidden). You don't have access with this data (anymore?). Please update the cookie
```

**Comment by ngalatis** [comment]
I solved the issue, posting what I did here in case someone has the same issue.

It turned out it was a IPv6 problem. Go to `Settings > System > Network` and disable the IPv6 interface. Restart.

**Comment by KoljaWindeler** [comment]
Thanks
