### ISSUE TITLE
Is still valid the initial setup to retrieve token?

### ISSUE THREAD

**Issue by jumping2000** [KoljaWindeler/ytube_music_player#223]
**Enable DEBUG Output**
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda> self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/config/.local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 27, in get_library_playlists response = self._send_request(endpoint, body) File "/config/.local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request raise Exception(message + error) Exception: Server returned HTTP 401: Unauthorized. You must be signed in to perform this operation.

**Describe the bug**
I have this error nowin HA, when I try to retrieve again the token with the initial setup procedure , the filter "browse" in developer tools doesn't return anything

**Version**
last version available in HACS

**To Reproduce**
initial setup procedure

**Additional context**
HA container 2022.11.x and 2022.12.2

Thanks

**Comment by jumping2000** [comment]
HA Container : core-2022.11.x and 2022.12.2

**Comment by maxi1134** [comment]
I am having the same issue getting "Exception: The following entries are missing in your headers: x-goog-authuser, cookie. Please try a different request (such as /browse) and make sure you are logged in."

**Comment by KoljaWindeler** [comment]
Hey guys, this is still working for me .. have you followed the pictures in the readme? 
e.g. take the correct request etc?

**Comment by CeeWeasel** [comment]
I had to redo the cookie in Firefox, rather than Chrome. After doing that, it apparently worked. I may have been able to get it working via Chrome if I had purged my cookies and/or gone through incognito mode. Either way, everything is good for now.

**Comment by terryhonn** [comment]
I was also unable to successfully copy the cookie information and create the integration until I went to an incognito Chrome window and performed the prescribed steps.

**Comment by Wireheadbe** [comment]
New set-up here. Instructions with the Incognito session were spot-on.

**Comment by kwatkins** [comment]
Adding a +1, Incognito mode was required for me to successfully get the token. Of all the integrations, this one is the most unstable... at least once every few weeks I have to go through the process of getting the auth token. That isn't to say mad props for all the work that goes on into even making it happen, just, c'mon Google let's make this easier.

**Comment by tektonnic** [comment]
Same issues as above, think the cookie has expired on my HA config so trying to grab the latest version and filtering on ‘browse’ shows nothing, Firefox and chrome tried, both in private/incognito…

**Comment by sdrapha** [comment]
Long time user of this integration, but I was having issues trying to get a new cookie.

Then I found the cause and the solution, there was an extra key in the middle of everything, `referer:`

I pasted the whole cookie in notepad first, removed the referer line, then it all worked.

**Comment by Underestimated** [comment]
At least for me, this isn't working no matter what I do. the cookie format never shows up like in the screenshot (I've switched browsers, incognito, even two different compters and OS's) it could be either of two things for me: either because I have 2FA enabled the cookie isn't working or they've started omitting parts of the cookie data in a recent update.

**Comment by sdrapha** [comment]
@KoljaWindeler, do you know exactly what are the needed keys on the cookie. So there could be a regex or something to filter out extra stuff , or warning missing ones? 
It seems the cookie format out of the browsers tools is not always consistent. So it would be worth to parse the cookie string a little deeper. extract the values, and rebuilt the cookie string again programatically.

**Comment by jumping2000** [comment]
I will close it, Ytube still working!
