### ISSUE TITLE
Not all required fields are filled in.

### ISSUE THREAD

**Issue by deanfourie1** [KoljaWindeler/ytube_music_player#225]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
Says that not all fields are filled in, however they are?

**Version**
Latest version to date.

**To Reproduce**
1. Install add on in HACS
2. add integration in HA and attempt to configure.

**Additional context**

![Capture3](https://user-images.githubusercontent.com/71812804/212881867-eac2b0e9-87b1-43fb-b956-9d2e7feecf6b.PNG)

Thanks

**Comment by LordBrain** [comment]
I just had the same issue today, but I was trying to add a second account to it. The first one seems to be working fine, but for the life of me I can not figure out how to add a second account like is done in the configuration video.

**Comment by deanfourie1** [comment]
This is first account for me

**Comment by LordBrain** [comment]
I compared between my working settings and the new one, and the only difference that I can see is the `:path:` is slightly different in the new one, it has a longer token. The content-length value is different as well: `content-length: 2041`

I really don't know why this isn't working for me.

**Comment by deanfourie1** [comment]
I tried it again,

This time it seemed to come up with a tick box option, which I didn't get before to select a media player to use. 

After selecting a media player, it worked!

Not sure what happened there

**Comment by LordBrain** [comment]
I tried it again and got it to work as well. No idea what changed.

**Comment by AssenDimitrov** [comment]
Hey guys, I am trying from a couple of weeks now but still no luck. How did you solve this one?

**Comment by AssenDimitrov** [comment]
Ok I figured it out - you need to have a fully working media player first as prerequisite.

**Comment by Ghundi** [comment]
Hey, I got that issue today as well, but Im unsure what you mean with a fully working media player. I can play Media from the Radio Browser, is that enough? My HA instance is just a few days old and doesnt have any media player integrations setup other than the default ones.

**Comment by davidmoreno92** [comment]
Same here.. any solution?
Thanks.

**Comment by deanfourie1** [comment]
The solution was a promised update about a year ago...  
There is no solution, and if you're using premium there is also no solution.


Find something else.

**Comment by davidmoreno92** [comment]
> The solution was a promised update about a year ago... There is no solution, and if you're using premium there is also no solution.
> 
> Find something else.

Yes, my yt account is premium..

**Comment by deanfourie1** [comment]
Yup, there is no solution.

You cannot use premium.

**Comment by KoljaWindeler** [comment]
hi, i assume this is fixed with the updated oAuth method, right?
