### ISSUE TITLE
Player wouldnt turn on.

### ISSUE THREAD

**Issue by alexbell62** [KoljaWindeler/ytube_music_player#23]
Hi,
Im getting following error last couple of days without changing much in the config and the player would not turno on.
Previously it worked just fine.

```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:857
Integration: YouTube Music Player (documentation)
First occurred: 8:56:13 (1 occurrences)
Last logged: 8:56:13

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 410, in _update_playlists self._playlists = self._api.get_library_playlists(limit = 99) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 29, in get_library_playlists results = find_object_by_key(nav(response, SINGLE_COLUMN_TAB + SECTION_LIST), File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 148, in nav raise err File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 142, in nav root = root[k] KeyError: 'contents'

```

When i try to start player im getting this

```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:221
Integration: YouTube Music Player (documentation)
First occurred: 9:23:56 (19 occurrences)
Last logged: 15:00:40

Can't start the player, no header file

```

Im on latest version but this issue was discovered on the previous version of the component

**Comment by KoljaWindeler** [comment]
Please repeat the cookies grabbing process. This really looks like your session ran out. Did you maybe sign out in the browser?

**Comment by alexbell62** [comment]
So strange i do not see the `browse` request anymore. Tries on mac on chrome and firefox, logging out and it.
When was setting it up the first time a couple of weeks or so ago was able to see it right away.

**Comment by KoljaWindeler** [comment]
have you tried the incognito mode?

**Comment by alexbell62** [comment]
yeah, with no luck.

**Comment by alexbell62** [comment]
by now i tried on different macs, google accounts and browsers. Didnt work - cant see the browse request.
 @KoljaWindeler are you sure the method is still working?

**Comment by alexbell62** [comment]
hhmmm it actually work on my other account whrere i dont have playlists. I think the issues may be that on my account i have 2 youtube accounts and can switch between them.
I wonder if this somehow plays in that mystery? 
Is there any other way to get these headers apart from browse?

**Comment by alexbell62** [comment]
or... can it be to do with these errors in console:
```
DevTools failed to load SourceMap: Could not load content for https://music.youtube.com/s/6d6983bc/fast-shim.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://music.youtube.com/s/6d6983bc/webcomponents-sd.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://music.youtube.com/s/6d6983bc/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not parse content for https://music.youtube.com/ytmusic-base-styles.css.map: Unexpected token < in JSON at position 0
```

**Comment by alexbell62** [comment]
bloody hell, for some reason it worked when i went inside playlist..
Phew!

**Comment by KoljaWindeler** [comment]
Honestly .. absolutely no idea. The guys over at the api are working on a better method but that will take some time. It works here fairly reliable ;)

**Comment by KoljaWindeler** [comment]
So did the new cookie help you? Or are you still facing the same problem?

**Comment by ryamber** [comment]
My /browse... didn't show up until I clicked Library in the top menu.

**Comment by alexbell62** [comment]
> So did the new cookie help you? Or are you still facing the same problem?

yeah it fixed the issue! May be worth updating the manual saying that if browse doesn't show up on music home page then try navigating through other pages: library, playlists, etc?

**Comment by alexbell62** [comment]
> My /browse... didn't show up until I clicked Library in the top menu.

Same for me

**Comment by KoljaWindeler** [comment]
> > So did the new cookie help you? Or are you still facing the same problem?
> 
> yeah it fixed the issue! May be worth updating the manual saying that if browse doesn't show up on music home page then try navigating through other pages: library, playlists, etc?

Yep already done yesterday. Great that it works now
