### ISSUE TITLE
Does this plugin use Google Cast for casting?

### ISSUE THREAD

**Issue by MrDodojo** [KoljaWindeler/ytube_music_player#230]
Hi! I wondered if this integration uses actual Google Cast to cast to Chromecasts, as I can't interact with it from YouTube music(takeover the stream) nor control it from an Android network casting notification nor skip songs if the designated chromecast is the default media receiver on a nest hub.
If not, is there any other plugin or addon which does this? In my current setup I want to start a playlist on my chromecast audio with an automation and then be able to take over control with my nest hub, I do see a way for an addon to be able to do this.

**Comment by KoljaWindeler** [comment]
It is not .. it is just forwarding the stream url to the media_player .. bare media_player. I don't thing that running and controlling the ytubeapp is possible.
