### ISSUE TITLE
Change Media Library order or implement a dropdown to be able to select the speaker

### ISSUE THREAD

**Issue by thor9898** [KoljaWindeler/ytube_music_player#235]
**Is your feature request related to a problem?** It kind of is a problem for me, as I end up not using this because it takes so long to be able to play a song and select the speaker I want to play it

**Describe the solution you'd like**
An option to be able to order the different squares in the media library

**Describe alternatives you've considered**
I wouldn't really need it if in the pop up menu of the youtube music entity there was a dropdown with all the available speakers and another with they playlists, although I don't know if thats something Home Assistant would allow

**Comment by KoljaWindeler** [comment]
Hi polr-ytube-media-card implemented exactly that menu
