### ISSUE TITLE
Limit speakers in dropdown

### ISSUE THREAD

**Issue by dnestico** [KoljaWindeler/ytube_music_player#239]
**Is your feature request related to a problem? Please describe.**
In the attached picture you can see there are so many random speakers that I don't want to show.
<img width="256" alt="Screen Shot 2023-03-30 at 5 28 51 PM" src="https://user-images.githubusercontent.com/3034555/228968991-ec63c022-31e3-4f0c-b975-6275b4d27387.png">

**Describe the solution you'd like**
It would help if could filter out certain speakers or just select the speakers we want to show in the dropdown.

**Describe alternatives you've considered**
There doesn't seem to be any alternative solutions so none.

**Additional context**
I attached a screenshot above.

**Comment by regan-a** [comment]
I would really like this feature as well! I don't want my house guests casting to Chromecast-enabled devices in areas of the house that they don't have access to.

**Comment by dnestico** [comment]
I was just wondering, do you think maybe this is a workaround to do this exact thing? Or no, haven't tried it.

<img width="331" alt="Screenshot 2023-08-01 at 2 41 59 PM" src="https://github.com/KoljaWindeler/ytube_music_player/assets/3034555/83b754a0-2255-464d-9cf5-c9d8701cfff4">

**Comment by KoljaWindeler** [comment]
yes :) sorry for the delay .. but yes .. if you select mutiple players in the config it will only shown those in the dropdown
