### ISSUE TITLE
LG TV WebOS "Connect USB Storage for Live Playback" Error

### ISSUE THREAD

**Issue by BaerHub** [KoljaWindeler/ytube_music_player#243]
I cannot play anything on the LG WebOS TV. 

My TV gives me the notification: **Please connect a USB Storage for Live Playback.**

thats what my card looks like:
![image](https://user-images.githubusercontent.com/77196974/234955459-88621f5c-035e-4549-af1f-029d73b2eb7b.png)

is there a known issue with LG TVs ?

**Comment by BaerHub** [comment]
Is this integration even working?? it doesnt support LG Soundbars or LG TVs

i tried both:

`homeassistant.exceptions.HomeAssistantError: Entity media_player.lg_soundbar_6aeab05d_5b80_4573_8e13_535dd2c4126b does not support this service.`

`homeassistant.exceptions.HomeAssistantError: Entity media_player.lg_webos_smart_tv does not support this service.`

**Comment by KoljaWindeler** [comment]
Hi, it works for all media_player that support playing from a URL. 
E.g. all cast devices 

it is possible that it doesn't work for the LG integration
