### ISSUE TITLE
Rate track doesn't respect song_id

### ISSUE THREAD

**Issue by salleq** [KoljaWindeler/ytube_music_player#245]
Testing this from Home Assistant developer tools:

service: ytube_music_player.rate_track
data:
  entity_id: media_player.ytube_music_player
  rating: thumb_toggle_up_middle
  song_id: 5ELInvKW1pU

Running service call toggles  thumb for current playing track instead of the song_id I've specifically mentioned.
Note: there is no such attribute "song_id" in the ytube music player entity attributes. However the videoid seems to be the same.

**Comment by KoljaWindeler** [comment]
Fancy, it was rating the correct song, but it update the UI for the current song .. regardless what ID was passed.
Thanks, fixed in https://github.com/KoljaWindeler/ytube_music_player/commit/900adda81425d3ba9e37efb1cf204e773a1f5c2f
