### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by Welsyntoffie** [KoljaWindeler/ytube_music_player#246]
I'm posting as an issue, because well, its an issue.

"The integration will let you login to your account" (false) does not allow login, its a workaround hack. Same as how Linus got hacked.

Please change your readme file and delete the first 2 sentences. Its not easy and it does not login. You wrote in your setup part yourself that its complex. 

Ohterwise, great effort. But not what I was looking for.

**Comment by KoljaWindeler** [comment]
oAuth added
