### ISSUE TITLE
Unable to play anything from YTMusic library on Home Assistant 2023.6.0

### ISSUE THREAD

**Issue by luvienm** [KoljaWindeler/ytube_music_player#247]
**** EDIT **

I just re-added the integration and now it works. Please disregard.**

Hello,

After updating to the latest release of Home Assistant, this error occurs after selecting an item from the YTMusic library:

This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1586
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 12:07:00 AM (188 occurrences)
Last logged: 12:11:45 AM

- Failed to get URL with YouTube methode
HTTP Error 410: Gone
- Retry with: (3)
- Retry with: (2)
- Retry with: (1)

**Comment by luvienm** [comment]
I just re-added the integration and now it works. Please disregard

**Comment by jurgenweber** [comment]
Let us know if it comes back, it is kinda a known problem this 410 error; https://github.com/KoljaWindeler/ytube_music_player/issues/238
