### ISSUE TITLE
Media player controls not visible

### ISSUE THREAD

**Issue by wildoracle** [KoljaWindeler/ytube_music_player#248]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled

Controls at bottom of media player screen is missing/invisible. I can't select ytube_music_player anymore because that whole bottom UI panel is not accessible. 
I can provide logs, and debug has been enabled for a long time. But this appears to be a system bug not the fault of your add-on. I'm making this bug report in hopes you know someone who knows what's causing the bug. 

**Version**
please provide the version you are using (see HACS)
20230321.01

**To Reproduce**
1. Go to 'media' on sidebar of Home Assistant 
2. See error

**Additional context**

Thanks!!

**Comment by dauden1184** [comment]
It seems the javascript managing the media panel doesn't like media player entities without a unique ID

Here the issue on the homeassistant github
https://github.com/home-assistant/core/issues/94342#issuecomment-1589067248

**Comment by wildoracle** [comment]
ANY new developments on this? There are developments happening at the link below and wondering if this is going to get fixed soon? Thanks!!
https://github.com/home-assistant/core/pull/95175

**Comment by KoljaWindeler** [comment]
Hi, I didn't work on this integration for quite some time .. only fixing it when something breaks .. 
is this issue still valid? it always worked for me
