### ISSUE TITLE
Voice search via home speaker such as google nest

### ISSUE THREAD

**Issue by lichunghk** [KoljaWindeler/ytube_music_player#249]
I would like to be able to search music and get it play on Google Nest by spaying commands like “Hey Google Play xxxx”

currently I can do text search and get the result to be played on google nest view home assistant

**Comment by KoljaWindeler** [comment]
Hi, this needs to be done within homeassistant and the voice engine .. there are service calls available to control the media_player but there won't be any voice processing inside this component
