### ISSUE TITLE
Report track completion back to YouTube Music 

### ISSUE THREAD

**Issue by livemac05** [KoljaWindeler/ytube_music_player#252]
**Is your feature request related to a problem? Please describe.**
Playing music via the integration does not seem to log entries to YouTube Music's history list. 

This causes some of the YouTube Music features/playlists such as the Replay Mix (auto-playlist based on frequent track plays) and the Archive Mix (auto-playlist based on infrequent track plays) to not function properly.

**Describe the solution you'd like**
It would be nice to, maybe optionally, have the integration report completed track playback back to YouTube Music.

**Describe alternatives you've considered**

**Additional context**

**Comment by KoljaWindeler** [comment]
added in https://github.com/KoljaWindeler/ytube_music_player/commit/f7b8488e5092cdf4ccb0a33a628f930bd26c9cb8
thanks for the idea
