### ISSUE TITLE
ESPHome media_player fails to output audio with yTubeMusic

### ISSUE THREAD

**Issue by githubpassera** [KoljaWindeler/ytube_music_player#261]
The ESPHome media_player does not output audio when triggered by the assigned yTubeMusic media player. However, all other media_players work fine with the yTubeMusic player. While the song and image do appear on the media player, the song skips after a few seconds and attempts to play the next song. The ESPHome media_player works fine with standard media players.

ESPHome mediaplayer are working fine with standard mediaplayer.
Code I'm using.
`i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO14 
    i2s_bclk_pin: GPIO27

media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO25
    mode: stereo`

**Version**
20230321.01

[home-assistant_ytube_music_player_2023-09-19T18-00-16.285Z.log](https://github.com/KoljaWindeler/ytube_music_player/files/12665134/home-assistant_ytube_music_player_2023-09-19T18-00-16.285Z.log)

**Comment by KoljaWindeler** [comment]
Hi, sorry for the delay .. Is the player (the ESP) actually playing the song? so do you hear the music? 
It looks like it is going from "playing" to "idle" quite quickly .. (within 500ms)

**Comment by githubpassera** [comment]
> Hi, sorry for the delay .. Is the player (the ESP) actually playing the song? so do you hear the music? It looks like it is going from "playing" to "idle" quite quickly .. (within 500ms)

Hi, no audio is played. Just did a new test, play > idle every time it try to play next song.

**Comment by KoljaWindeler** [comment]
Hi, please try this https://github.com/KoljaWindeler/ytube_music_player?tab=readme-ov-file#method-2-owntone-server-as-proxy

**Comment by KoljaWindeler** [comment]
Hi, please reopen if owntones isn't helping. In general: this integration extracts the streaming URL. Everything after that is to the mediaplayer .. I can't influence that part .. and it sounds like an issue in the ESP code
