### ISSUE TITLE
Extend cookie duration

### ISSUE THREAD

**Issue by hoanglongutc** [KoljaWindeler/ytube_music_player#263]
Hi, Is there any way to extend the cookie life? Every time I update a new cookie, it only lasts a few days and I get the error: Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.
This is really inconvenient. Thanks!

**Comment by wsjunior1985** [comment]
Same problem here. But I have to configure a new cookie every day. This is fucking annoying..

**Comment by KoljaWindeler** [comment]
Why don't you switch to oauth?

**Comment by hoanglongutc** [comment]
This issue persists after reverting back to Cookie version
