### ISSUE TITLE
error since  HA-23.10

### ISSUE THREAD

**Issue by yanirel** [KoljaWindeler/ytube_music_player#265]
i updated HA to 23.10 and the ytube_music_player entity disappered , it show that it has been config bat without any entities or any device , 

Thanks

**Comment by halfskye** [comment]
I'm running into the same behavior after upgrading HA Core to 2023.10.5 :

![image](https://github.com/KoljaWindeler/ytube_music_player/assets/25853589/69ffd239-9a0b-4b93-909f-a0fd8bc7e461)

I tried to remove the integration and then redownload, reinstall, and reconfigure but am still experiencing the same behavior - no entities.

I've reinstalled the Google Cast integration and tinkered with quite a few other things as well after all of this so I'm uncertain if anything else contributed to it working again, but I seem to now still be able to Play Media via the `ytube_music_player` domain. Though I was previously experiencing a number of other errors including the HTTP 410 error "Gone" code.

**Comment by halfskye** [comment]
In response to my last comment, I'm actually very consistently now getting the HTTP 410 "Gone" error code and seem to now only be able to play single songs with any reliability but what ends up happening is I'll browse to the song with the mini player and then it'll repeatedly fail but then seems to cyclically attempt to reload it on loop and eventually it will successfully load and start playing.

The HTTP 410 "Gone" error code and the "Failed to get URL with YouTube methode" error message seem consistent with this other semi-recent open issue:
https://github.com/KoljaWindeler/ytube_music_player/issues/262

**Comment by KoljaWindeler** [comment]
Hey, have you tried the new version with oAuth? This improves the situation for me
