### ISSUE TITLE
Auto Advance error

### ISSUE THREAD

**Issue by nk2261** [KoljaWindeler/ytube_music_player#266]
**Describe the bug**
When i create a automation for [Auto Advance](https://github.com/KoljaWindeler/ytube_music_player#mpd-fix) with the code in the repo i get the error  "Message malformed: extra keys not allowed @ data['0']" I cannot seem to get past this. Am i creating the automation in the correct area? 

**Version**
Home Assistant 2023.10.1

**Comment by KoljaWindeler** [comment]
well .. maybe share your automation .. otherwise it is really hard to tell
