### ISSUE TITLE
Add support for oAuth instead cookies

### ISSUE THREAD

**Issue by xkill** [KoljaWindeler/ytube_music_player#270]
**Is your feature request related to a problem? Please describe.**
Cookies expires and there is another way to get authenticated: oauth.

**Describe the solution you'd like**
ytubemusicapi supports oauth authentication.

An oauth.json is used, it is similar to the following:

```json
{
 "access_token": "[long string]",
 "expires_in": [int - number of seconds to expire],
 "refresh_token": "[another string]",
 "scope": "https://www.googleapis.com/auth/youtube",
 "token_type": "Bearer",
 "expires_at": [unsigned int - epoch time]
}
```

Also there are other HASS integrations that use oAuth to authenticate against Google services, easily and using the HASS web interface when you enable the integration, such as the calendar.

**Describe alternatives you've considered**
Follow the `ytmusicapi oauth` command line to get an updated version of the oauth.json, upload it to HASS and use it instead the creds.json

**Comment by Taomyn** [comment]
The integration is failing on a daily basis for me unless I manually reconfigure it.

```
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.

```
To be able to use a properly authenticated session would be really good.

**Comment by KoljaWindeler** [comment]
I agree .. and it looks reasonably easy to integrate.... I'll give it a shot in the next days ..

**Comment by KoljaWindeler** [comment]
awesome .. where exactly? I've just tried 100 and it loaded 100 tracks by default .. i have to admit that reconfiguring the integration led to the default 25 in the dialog... will check why

**Comment by wildoracle** [comment]
> awesome .. where exactly? I've just tried 100 and it loaded 100 tracks by default .. i have to admit that reconfiguring the integration led to the default 25 in the dialog... will check why


https://github.com/KoljaWindeler/ytube_music_player/assets/18076002/bdce58a9-3eb8-4423-9fbe-213d5bad6d81

Enjoy the xmas music, didn't realize it was recording audio too LOL

**Comment by wildoracle** [comment]
By the way... your integration is one of my primary uses of home assistant, and this recent auth fix is a huge quality of life improvement, thanks!!

**Comment by KoljaWindeler** [comment]
thanks for the xmas music and for the pressure :)
yes that number is wrong .. I'll fit that .. but the 1000 that you've entered should work, only the re-config Dialog is loading the wrong default

**Comment by KoljaWindeler** [comment]
Please try the latest version ..  https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20231117.01

**Comment by wildoracle** [comment]
PERFECT! Thanks. No pressure, mate! You've already exceeded expectations.

**Comment by Taomyn** [comment]
Sorry I'm late for the testing, but just set it up and works perfectly, many thanks.

Be aware, if you're enrolled in Google's, Advanced Security option for your account, this won't work as it's pretty strict as to what can and cannot access your accounts, and the list is tiny. Had to disable it myself but it was also causing me other issues with some old devices so I needed to do it. Why Google doesn't enable a way to permit them manually I don't know, but I don't see Home Assistant or integrations ever being added until they do.

**Comment by wildoracle** [comment]
> Sorry I'm late for the testing, but just set it up and works perfectly, many thanks.
> 
> Be aware, if you're enrolled in Google's, Advanced Security option for your account, this won't work as it's pretty strict as to what can and cannot access your accounts, and the list is tiny. Had to disable it myself but it was also causing me other issues with some old devices so I needed to do it. Why Google doesn't enable a way to permit them manually I don't know, but I don't see Home Assistant or integrations ever being added until they do.

Thanks! I will be sure to never allow myself to be signed up with Google's Advanced Security... at least not on my personal Google account. I have enough trouble with Google devices as it is. In fact, this integration is the only way I've found to play from YTMusic to my Google Home speaker groups consistently and without skipping. It works even better than if I ask the *Google* device to play from a *Google* service... Oh, the irony. I've even sent Google engineers this github project telling them that whatever code this is using to do it right they need to copy from!

**Comment by nawaidrana** [comment]
Your documentation didnt state the cookie has gone away, i kept banging my head on why i dont see cookie entries. I have installed the integration, but dont know where I can find my music, I dont see anything...

**Comment by KoljaWindeler** [comment]
documentation updated

**Comment by KoljaWindeler** [comment]
ah .. there is still an issue .. what do you mean by "I dont see anything"?
Have you read the readme? https://github.com/KoljaWindeler/ytube_music_player#installation-went-fine-what-now
