### ISSUE TITLE
Unable to create new input_select entites for secondary account. 

### ISSUE THREAD

**Issue by rxritalin** [KoljaWindeler/ytube_music_player#277]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
I added a second account and changed the entity name to "ytube_music_player_juan". 
I changed the file path for the header file to "/config/.storage/ytube_header_juan.json"
This does create a second media player and it functions correctly, with the ability to see this accounts library and what not. 

The bug seems to be with the the advanced config section of the setup, where I have fields to change the entity id of the input_select and input_boolean. 
I have set all fields to the default, with a change to the end for example; 
"input_select.ytube_music_player_speakers_juan"
None of these devices are created. I only have the default ones that were created under the primary account, but it changes the data to the second accounts. 

**Version**
input_select.juan_ytube_music_player_speakers

**To Reproduce**
1. Go to integrations > yTubeMediaPlayer 
2. Click on Add Entry
3. Go through the process of setting up a second account with Google
4. Change the name for the entity to something besides the default. 
5. Change the file path for the header to /config/.storage/something_else.json
6. Check the box for show advanced configuration. 
7. Edit the Entity id fields, leave the default and add "_something" to the end of of the entity name.

**Additional context**
Whether I change the name of the entity ID fields or not, it does overwrite the input_select entities and shows the content for the secondary account. 

Thanks

**Comment by KoljaWindeler** [comment]
Hi, what do you mean by 

None of these devices are created

.. to be honest the input setup way is very old fashioned .. I'd strongly recommend mini_media_player or better https://github.com/pathofleastresistor/polr-ytube-media-card
