### ISSUE TITLE
[Request] - Custom Card

### ISSUE THREAD

**Issue by Shaun-Harrison** [KoljaWindeler/ytube_music_player#28]
Hello

I've set up your integration today and it does work! Great work!

I've noticed though with my current setup I'm using the following card - https://github.com/kalkih/mini-media-player 
And there are some issues which may be improved by having your own custom card

For example, switching what speaker it plays too with the input select doesn't change unless the power is switched off and then back on which loses the current song 

It would be really cool (if possible of course) to have the following card

![image](https://user-images.githubusercontent.com/46562010/103081401-c6c0c100-45cf-11eb-8d31-e658fcbe954e.png)

But have the input selects integrated into the actual media player card as buttons where then the functionality can be applied

**Comment by KoljaWindeler** [comment]
Hi the newest release supports shotcuts from the mini-media-player. You can now switch directly the player via a single-click (keeping the playlist) and also add shortcuts for your favourite playlist .. shuffle can be set with the build in "shuffle" button from the mini-media-player. Only Playlist / Playlist radio is so specific that a dedicated dropdown is still required.

This is as close as it get :) I'm not a GUI developer and don't want to build a dedicated card.

**Comment by Shaun-Harrison** [comment]
Just updated and put in the buttons, works perfectly, thank you!

**Comment by ghostrobo282** [comment]
we need the code for this card

**Comment by KoljaWindeler** [comment]
Honestly ..  what for? I mean .. yes, adding those drop-down would be one way (although I highly doubt that someone will design that card) but why not use the shortcuts from the Mini-Media-Player? 

Too many playlists? Too many players?

I have my top 8 playlists (some as playlist, some as playlist radio aka channel) and two main players integrated as shortcuts. Shuffle is an onboard feature of the mini media player ...  That covers 95% of my needs. I still have the drop down on another lovelace tab so in case I need a special setup I can still use them. But that's super rare. 

I have no objections against a drop down card but I think I'd stick with the shortcut setup.
