### ISSUE TITLE
New cards for this component

### ISSUE THREAD

**Issue by pathofleastresistor** [KoljaWindeler/ytube_music_player#284]
I've enjoyed this integration but have found the media browser experience clumsy. I created two cards to help me search and interact with what's currently playing.

https://github.com/pathofleastresistor/polr-ytube-media-card

I wanted to share here since it wouldn't be possible without the hard work here. Thanks!

**Comment by KoljaWindeler** [comment]
Wow .. really impressive!! Great work! Thanks for sharing. Once I'm back from Xmas traveling I'll have a closer look and integrate it into my setup!

**Comment by pathofleastresistor** [comment]
It took me a couple iterations but v1.4.2 has landed with a complete experience.

[full-demo-polr-ytube-media-card.webm](https://github.com/KoljaWindeler/ytube_music_player/assets/91756648/1bb2629e-f8de-4e15-9e3a-8502bb2a9354)

**Comment by KoljaWindeler** [comment]
Man! That's awesome. 

Have you thought about an option to use the artwork as background? I really like that at the mini Media player

**Comment by pathofleastresistor** [comment]
Good idea - I added an initial stab at it in v1.5.0

**Comment by KoljaWindeler** [comment]
Oh oh .. what's the meaning of "completed" ? Will you keep developing it or is it done as is? 
Either way: I love it

**Comment by pathofleastresistor** [comment]
Development will continue! I wanted to thank you for adding this as a suggested card too.

In the interest of issue hygiene I figured we can close this out and open better scoped issues/FRs as needed.
