### ISSUE TITLE
Genres are not browsable by ytmusic api

### ISSUE THREAD

**Issue by pathofleastresistor** [KoljaWindeler/ytube_music_player#287]
https://github.com/KoljaWindeler/ytube_music_player/blob/930b590d007aeb9a744953131c10162238f803d9/custom_components/ytube_music_player/browse_media.py#L445

I tested the ytmusic api and any attempt to get playlists for a Genre results in an error. I figure we need a simple fix here:
```
if cap == "Genres":  # Browsing Genres not supported by ytmusic
    continue
```

**Comment by KoljaWindeler** [comment]
hmm sorry I don't get it .. what "genres" are you talking about here? I can browse all available genres just fine .. 
![image](https://github.com/KoljaWindeler/ytube_music_player/assets/471314/d98b84b7-cfd6-4d1c-bb75-be55f332d0e1)

**Comment by pathofleastresistor** [comment]
Oh interesting - this may be a different issue then. When I query the ytmusic API directly for playlists for a genre, I get an error. I was then also getting errors in the media browser.

I'm not sure why I get errors and you don't though but I can take that to the ytmusic people.
