### ISSUE TITLE
children_media_class expects array size > 0

### ISSUE THREAD

**Issue by pathofleastresistor** [KoljaWindeler/ytube_music_player#288]
https://github.com/KoljaWindeler/ytube_music_player/blob/930b590d007aeb9a744953131c10162238f803d9/custom_components/ytube_music_player/browse_media.py#L568C12-L568C12

We should wrap this call with a check to see if there are children
```
if len(children) > 0:
  response.calculate_children_class()
```

**Comment by KoljaWindeler** [comment]
agreed ..it avoids the error but it leads to no playlist shown in your card .. is is visible in the media_browser.
![image](https://github.com/KoljaWindeler/ytube_music_player/assets/471314/43ced93f-86da-4f24-b2de-184b88d38e56)
vs
![image](https://github.com/KoljaWindeler/ytube_music_player/assets/471314/e222c925-5e8b-4ce0-ba86-5c0a1c4d45a2)
any idea?

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player/commit/c52fd5fe6d523e1c4e30ca30c63ad6db3436cf9b#diff-1a51a4d6f5638578d471fdf07bd4e87d6ffd54bc762ee88a02c4be73d4f3b322L567

**Comment by pathofleastresistor** [comment]
Ha now it's my problem to fix :).

Can you help me repro this? I applied this changed locally but don't see the blank playlist.

**Comment by KoljaWindeler** [comment]
actually no :) can't reproduce it at the moment .. not sure what fixed it .. I've played around quite a lot tonight .. will report once I know how to reproduce it and reopen the issue
