### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by andiukas** [KoljaWindeler/ytube_music_player#289]
Version:
ytube_music_player: 20240101.01
Core: 2024.1.0b3

I get an error when i try to enter media_browser
![Screenshot 2024-01-02 113329](https://github.com/KoljaWindeler/ytube_music_player/assets/44068098/7e79ddc6-6531-47f7-b951-5624d55fdb09)

**Comment by KoljaWindeler** [comment]
hmm strange .. it works fine here .. can you check the log ?

**Comment by chaimchaikin** [comment]
I had the same error. I believe it might have to do with the beta version of home assistant (I am also on 2024.1.0b3)
This was the error in logs:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/media_player/__init__.py:1298
Integration: Home Assistant WebSocket API ([documentation](https://rc.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 7:07:10 PM (1 occurrences)
Last logged: 7:07:10 PM

[547462357568] Error handling message: Unknown error (unknown_error) Name from <<IP ADDRESS>> (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1298, in websocket_browse_media
    if MediaPlayerEntityFeature.BROWSE_MEDIA not in player.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

Looks like it will be fixed with https://github.com/KoljaWindeler/ytube_music_player/commit/e905d3ea19d656d6d15bbc898a3d031bbc1c6d20
Thank you!

**Comment by chaimchaikin** [comment]
I initially reported it here https://github.com/pathofleastresistor/polr-ytube-media-card/issues/3#issuecomment-1874402274 before realizing it was an issue with the component itself. Thank you @pathofleastresistor for pointing me to the correct commit that likely fixes this.

**Comment by andiukas** [comment]
> hmm strange .. it works fine here .. can you check the log ?

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1298, in websocket_browse_media
    if MediaPlayerEntityFeature.BROWSE_MEDIA not in player.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

**Comment by KoljaWindeler** [comment]
Can you try with the latest master commit? 
do you need a release to update via HACS?

I can't access my dev machine as I'm on business travel at the moment and don't run my productive setup on the beta versions, so can't test there.

**Comment by andiukas** [comment]
> Can you try with the latest master commit? do you need a release to update via HACS?
> 
> I can't access my dev machine as I'm on business travel at the moment and don't run my productive setup on the beta versions, so can't test there.

Update Core to 2024.1.0b6

![image](https://github.com/KoljaWindeler/ytube_music_player/assets/44068098/0bf6d65a-a568-4a47-871a-d84b6365d631)

**Comment by chaimchaikin** [comment]
> Can you try with the latest master commit? do you need a release to update via HACS?
> 
> I can't access my dev machine as I'm on business travel at the moment and don't run my productive setup on the beta versions, so can't test there.

I installed the latest commit manually (copying over the files) and it works, thank you!

**Comment by andiukas** [comment]
I installed the latest commit manually (copying over the files) and it works, thank you!
