### ISSUE TITLE
Deprecated constants warnings in 2024.1

### ISSUE THREAD

**Issue by Murianwind** [KoljaWindeler/ytube_music_player#290]
**Is your feature request related to a problem? Please describe.**
Since 2024.1 i get these logs:

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 08:10:44 (28 occurrences)
Last logged: 08:11:24

TEMP_CELSIUS was used from ytube_music_player, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/KoljaWindeler/ytube_music_player/issues

**Describe the solution you'd like**
I think you should use UnitOfTemperature.CELSIUS

**Describe alternatives you've considered**

**Additional context**

**Comment by KoljaWindeler** [comment]
Thanks, its even imported for no reason :) ... some left over from another integration of mine that I used as a starting point.

**Comment by KoljaWindeler** [comment]
Fixed in https://github.com/KoljaWindeler/ytube_music_player/commit/5e02a93dd83b26d77ed128808cc773fadc7d1d73 
Thanks

**Comment by Murianwind** [comment]
Thanks a lot!! Happy new year!!

-----
Murian Song

SW Testing Evangelist & Consultant / TOC Evangelist & Consultant

Blog: http://murianwind.blogspot.com

Twitter: http://twitter.com/murianwind

Facebook: http://www.facebook.com/murianwind


2024년 1월 7일 (일) 16:15, Kolja Windeler ***@***.***>님이 작성:
