### ISSUE TITLE
depreacated ??

### ISSUE THREAD

**Issue by pressurejets** [KoljaWindeler/ytube_music_player#294]
`TEMP_CELSIUS was used from ytube_music_player, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/KoljaWindeler/ytube_music_player/issues`

**Comment by KoljaWindeler** [comment]
Thanks
https://github.com/KoljaWindeler/ytube_music_player/issues/290
