### ISSUE TITLE
Latest update does not load playlists and speakers + replays same songs

### ISSUE THREAD

**Issue by XalaTheShepard** [KoljaWindeler/ytube_music_player#297]
After the latest update the speakers and the playlists can no longer be loaded. 
Reverting back to a previous version did not solve the issue. 
Most likely a change at YouTube self. 

Also, I noticed when selecting my favourite playlist, it always replays the same 60 songs of a playlist of 300 songs. 
I had a look at the advanced options and selected to load more songs, but could not test it. 

Could you please confirm that loading more songs could solve the issue? 

Many thanks and enjoy your weekend. 

Kind regards, 

Robin

**Comment by KoljaWindeler** [comment]
hi, yes the 300 should make it load 300 tracks .. lets look at the other issue here https://github.com/KoljaWindeler/ytube_music_player/issues/297
