### ISSUE TITLE
[Improvement] Use pytubes features to filter and sort for audio feeds

### ISSUE THREAD

**Issue by stboch** [KoljaWindeler/ytube_music_player#3]
Line: 429
`_url = YouTube('https://www.youtube.com/watch?v='+_track['videoId']).streams.filter(only_audio=True).order_by('abr').last().url`

**Comment by KoljaWindeler** [comment]
thx 
https://github.com/KoljaWindeler/ytube_music_player/commit/6b91364ad0132c1dec09d83f05b1c2f5bbd4be72
