### ISSUE TITLE
track my music - no matter which device

### ISSUE THREAD

**Issue by 1mfaasj** [KoljaWindeler/ytube_music_player#302]
Hi, no issue but a quick question:
I need to define "output devices" at the initial configuration. but these are only known in Home Assistant.

What if I want to track which music I listen to and for how long on other devices too, such as my telephone (which I can not add as media device in your configuration).

Do you have a solution for this?
Is there way to track how long I listen to youtube music, no matter what device I'm using? 
For instance the spotify Home assistant integration pulls the Spotify api, do you have a similar setup? 
Is it possible to pull this data from youtube for instance?

Thanks

**Comment by KoljaWindeler** [comment]
hi, there is no such api from ytube as far as i can see .. i guess that would also need to be a feature that you can find on the website right? so sorry, but not possible as of now
