### ISSUE TITLE
After latest update, ytubemusicplayer don't start first song and a lot of stuttering.

### ISSUE THREAD

**Issue by XalaTheShepard** [KoljaWindeler/ytube_music_player#303]
Good afternoon,

After the latest update of the YouTube Media Player, the songs can start again on my Google Home.
However, the first song refuses to play. To play this song, I have to skip manually to the next song and afterwards go back manually to the previous song.
Also the songs are often temporarily paused and continue after some seconds or minutes (stuttering).

Reverting back to the previous version of the integration causes the song not being able to play on my Google Home, so only the latest version of the integration can play YouTube songs, but with a lot of stuttering.

The logs don't give any further information.

Kind regards,

Robin

**Comment by XalaTheShepard** [comment]
The ticket can be closed. Network company was working in the neighbourhood and afterwards a reboot of the router solved the issue

**Comment by plonkis** [comment]
Reverting to previous version (20240112.01) solved the problem for me

**Comment by XalaTheShepard** [comment]
Luckily, I am not the only one with this issue. Wanted to request to keep this issue open as I am still experiencing issues with it ...

**Comment by KoljaWindeler** [comment]
Hi, the first song issue is something I can have a look at, the stuttering not. The integration navigates in Ytube and finds the streaming link. That link is passed to the remote player and everything after that is up to the layer. ... I'll still check the first song issue

**Comment by XalaTheShepard** [comment]
Thanks for looking into the issue. However the stuttering is somehow related to the latest version of the integration. Reverted back to the previous version (20240112.01) and both the autostart issue and the stuttering are gone. So I will temporarily remain on this version of the integration

**Comment by plonkis** [comment]
I alos hade the stuttering

**Comment by KoljaWindeler** [comment]
Regarding the first track: can you create a log for me?
I can't reproduce it.

https://github.com/KoljaWindeler/ytube_music_player#1-reroute-debug-output-to-error-via-service

**Comment by XalaTheShepard** [comment]
Dear KoljaWindeler, I will reinstall the latest update and provide you with the logs tomorrow at latest. However, could you also please have a look at the stuttering issue? Plonkis confirmed the same issues and both of us the issues were resolved by going back to the (20240112.01) version. Could it be an reoccurring authorisation issue as sometimes it stops for multiple minutes and then resumes the song. It became so annoying, that I downgraded the integration and preferred the issue to start on Google home devices. Sometimes even 6 times per minute it stopped the music.

**Comment by XalaTheShepard** [comment]
Dear KoljaWindeler, please find my logs below. Kind regards, Robin
[home-assistant_2024-02-04T21-12-47.285Z.log](https://github.com/KoljaWindeler/ytube_music_player/files/14158500/home-assistant_2024-02-04T21-12-47.285Z.log)

**Comment by KoljaWindeler** [comment]
Hi Robin, please try https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20240205.01b
the advance dialog offers max bandwidth limitations:
![image](https://github.com/KoljaWindeler/ytube_music_player/assets/471314/c98a7b3f-9871-44e6-a38d-b8d04870f1d1)

highest I've seen was 250k, 140k streams are quite common but it goes down to 50k

you will see something like this in the debug log

```
 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] found 6 streams
 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 259458
 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Using stream 0/5, bitrate:147940
 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - self decoded URL via cipher
```

**Comment by maxpd1** [comment]
Just installed HASS only for ytubeplayer feature. I can confirm stuttering in current master version.

**Comment by KoljaWindeler** [comment]
Well if some older devices don't support 250k+ bitrates then this would explain and solve it. Please test the beta

**Comment by plonkis** [comment]
Just filling in with info about my setup. HA is on wired 1 gbit network and my internet connection is 1gibit fiber (900+ mbit/sec up/down). My wifi network is running 11 Ruckus AP:s (no mesh) with no speed problems. My HA is running virtual on a Xeion based server.

I have not tested the beta version you linked yeat. XalaTheShepard is probably faster then me to test it!

**Comment by KoljaWindeler** [comment]
Well I guess your Network is not the limit .. but maybe also an older player? Maybe the hardware was not designed for 250kbps?

**Comment by XalaTheShepard** [comment]
I hope to test it this evening. But it will honestly be a bit trial and error with the bitrate as I have no experience with it. Plonkis definitely has the better network. My network is limited by the network company at 200mbits per second ...

**Comment by KoljaWindeler** [comment]
I don't thing that network speed matters at those ranges. We're talking <1mbps audio. Try 75000 as a low value and see if this works. For now we need to understand if this is a Bitrate issue.

**Comment by XalaTheShepard** [comment]
I will install the beta now and test it the coming hours. My wife is at a work party, so can nobody can raise an issue against my music playing while watching our son :)

**Comment by plonkis** [comment]
I got some unexpected time over so i have done some testing with version 20240205.01b.

Only change I have done from my original setup was to change max bitrate to 192kbps (was unlimited). Results: normal start of music and no stuttering!

I use Google Mini, Mini Nest, Audio Nest and ChromeCast Audio, a total of 9 speakers at the same time. So far it looks like the problem is solved!

**Comment by XalaTheShepard** [comment]
Started with 75K as bitrate and everything works fine again. I really like the idea of the choice of bitrate as it will be useful when I install my speaker in the garden lounge this summer as it has a bad wifi connection over there. Many thanks for the great support 🙂

**Comment by plonkis** [comment]
Everything is still working :)

Many thanks KoljaWindeler for your help with this problem and for this awesome integration!

**Comment by KoljaWindeler** [comment]
I'm working on the "skip first track" issue and will post a beta for that in the coming days .. but great to hear that stuttering is fixed. It need proper documentation still

**Comment by KoljaWindeler** [comment]
Could you please try: https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20240208.01b

**Comment by plonkis** [comment]
Finally i got time to test ;) just a quick report everything works but i am gonna let the player go the rest of the day en report back later to day! (same setup with 192kbps)

**Comment by plonkis** [comment]
After three hours of testing I had zero problems!
