### ISSUE TITLE
no playback possible

### ISSUE THREAD

**Issue by aleksej0307** [KoljaWindeler/ytube_music_player#307]
I have installed and set up the player, unfortunately I can't hear any sound and I always get the following message.

![2024-02-22 14_51_30-Übersicht – Home Assistant](https://github.com/KoljaWindeler/ytube_music_player/assets/154066787/8674babb-4128-430b-8e79-079744e2eb0a)

The time stops regardless of which output source I select

![2024-02-22 14_52_55-Übersicht – Home Assistant](https://github.com/KoljaWindeler/ytube_music_player/assets/154066787/a2e549a6-f1ec-4fe0-8cb3-18eac59bf339)

The following output sources are available, most of which are Alexa Echo, but these include a Macbook, Windows PC, iPhone, TV, etc.

![2024-02-22 14_57_44-Übersicht – Home Assistant](https://github.com/KoljaWindeler/ytube_music_player/assets/154066787/921eb0d8-c2ad-4dfd-b6f1-868ce7fce216)

One question: does the output generally work via Alexa speakers?

I hope you can help me.

**Comment by KoljaWindeler** [comment]
Hi sorry for the delay .. all media player work which can stream from an URL.
MPT, Chromcast, Google Home, Mini, browser mod  work for sure. Alexas can't stream from URL.
So i guess this is not possible to solve ..
