### ISSUE TITLE
Very long buffer time for 1h music

### ISSUE THREAD

**Issue by Jerry0022** [KoljaWindeler/ytube_music_player#312]
I want to play a background music based on my motion sensor. I found a great one, which is about a one hour, so "larger" music piece. I managed to let it play, super thx for the great integration, but it buffers almost half a minute (media type music).
Afterwards it starts playing, which takes in my case way to long.d

Is there any possibility to buffer to the full song but only first seconds?

Alternatively, if I can find another piece with less minutes / smaller, is there a loop function? So after it stops that it starts it again?

Btw, Google Home Nest Audio

**Comment by KoljaWindeler** [comment]
Hi @Jerry0022 the buffer time is up to the Google home. 
My integration "just" send the URL to the device. 
You can try lower bitrates (in the settings of the integration). E.g. 64000 bps.
Yes you can create a playlist with just one track and set the repeat mode to single .. that will loop the track
Greets

**Comment by Jerry0022** [comment]
Ok, thanks! I just used a shorter soundtrack with loop, works fine. 
Btw, I could not find the setting of the bitrate :/

**Comment by KoljaWindeler** [comment]
Go to settings - devices - ytubemusicplayer - configure (make Sure to select "show advance options") - next .... Tata
