### ISSUE TITLE
As an output device Echo Show

### ISSUE THREAD

**Issue by Toolmaster30** [KoljaWindeler/ytube_music_player#314]
I'm not sure if it's a bug or just not supported.
But when I use my Echo Show as the output device I get the following error message:

`Logger: custom_components.alexa_media.media_player
Quelle: custom_components/alexa_media/media_player.py:1395
Integration: Alexa Media Player (Dokumentation, Probleme)
Erstmals aufgetreten: 22:25:50 (1 Vorkommnisse)
Zuletzt protokolliert: 22:25:50

To send TTS, please set Announce=true. Music can't be played this way.`

I hope someone can help me.
Greetings Toolmaster

**Comment by KoljaWindeler** [comment]
Jep, Alexa doesn't support streaming from urls.
No bug.
