### ISSUE TITLE
I can not see the media_player entity in lovelace

### ISSUE THREAD

**Issue by yorchtf** [KoljaWindeler/ytube_music_player#32]
**Information:**
Home Assistant 2020.12.1
Home Assistant OS 5.9
Supervisor | 2020.12.7

Steps:
1. Add repository in HACS
2. Open Configuration -> Integrations -> "add integration" -> "YouTube Music Player"
3. Paste the cookie into the indicated field
3.1 Extract cookie youtube music and paste the following text in the installation HACS.
<img width="908" alt="Captura de pantalla 2020-12-28 a las 11 37 59" src="https://user-images.githubusercontent.com/8900958/103212437-aa3fc400-4902-11eb-88f6-9c37fbb621d9.png">

```accept-encoding: gzip, deflate, br
accept-language: es-ES,es;q=0.9,en;q=0.8,th;q=0.7,pt;q=0.6
authorization: SAPISIDHASH <STRING>
content-length: 967
content-type: application/json
cookie: VISITOR_INFO1_LIVE<STRING>
origin: https://music.youtube.com
referer: https://music.youtube.com/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Mobile Safari/537.36
x-client-data: CI<STRING>
Decoded:
message ClientVariations {
  // Active client experiment variation IDs.
  repeated int32 variation_id = [3300106, 3300133, 3300164, 3313321, 3318700, 3318774, 3319460, 3320540, 3329132, 3329546, 3329602];
}
x-goog-authuser: 0
x-goog-visitor-id: CgtzaWFyTEROM3RhSSid36b_BQ%3D%3D
x-origin: https://music.youtube.com
x-youtube-ad-signals: dt=1609<STRING>
x-youtube-client-name: 67
x-youtube-client-version: 0.1
x-youtube-device: cbr=Chrome+Mobile&cbrand=google&cbrver=<STRING>
x-youtube-identity-token: <STRING>
x-youtube-page-cl: <STRING>
x-youtube-page-label: youtube.music.web.client_<STRING>
x-youtube-time-zone: Atlantic/Canary
x-youtube-utc-offset: 0
```

4. Restart Hassio

5. Copy the entity definition in configuration.yaml

```
media_player:
  - platform: ytube_music_player
    speakers:
      - cuarto_de_estar
      - en_toda_la_casa
      - mibox3
```

6. Restart HAssio

7. Now, I want to add the media_player entity in lovelace, but I don't see the entity.

8. Go to Home assistsnat Logs
<img width="985" alt="Captura de pantalla 2020-12-28 a las 11 31 53" src="https://user-images.githubusercontent.com/8900958/103212752-a3658100-4903-11eb-9de4-2302aae427d6.png">

Can you help me?

**Comment by KoljaWindeler** [comment]
Did you filter for browse or did you just take any request header?
The guide from the api says it has to be the browse filter ... I've never tried another request ..

**Comment by yorchtf** [comment]
<img width="1198" alt="Captura de pantalla 2020-12-28 a las 17 58 04" src="https://user-images.githubusercontent.com/8900958/103234322-4edbf900-4937-11eb-8621-65b2b7a95684.png">
Excuse me, is it correct?

**Comment by KoljaWindeler** [comment]
Yes that looks exactly right, copy at least the cookie and the x-goog-visitor-id ... If that doesn't work, try again in an incognito session

**Comment by yorchtf** [comment]
Great!!! Now, it is working!!! Thanks a lot!!!

**Comment by KoljaWindeler** [comment]
Out of curiosity, what part did the trick? The incognito session?

**Comment by yorchtf** [comment]
Normal session.... I think I did not filter correctly.

**Comment by KoljaWindeler** [comment]
Alright, glad that its working now
