### ISSUE TITLE
Enhance the behavior of changing play mode during playback.

### ISSUE THREAD

**Issue by mang1985** [KoljaWindeler/ytube_music_player#320]
When music is playing and I use the dropdown to change the play mode, or press the random button on the player panel, the current music stops and the playlist restarts from the beginning. This behavior differs from other players and is not a good user experienc.
So I suggest modifying this behavior pattern.

Press the button on the panel:
Toggle random mode,do not interrupt the playback.If the random mode is on,the next song will be played randomly,otherwise,just play the next track in the list.

Use the dropdown:
Shuffle -> Random: Turn on random mode.
Shuffle -> Shuffle Random: Turn on random mode.
Shuffle -> Direct: Keep the current behavior.
Random -> Shuffle: Keep the current behavior.
Random -> Shuffle Random: Keep the current behavior.(or do noting?)
Random -> Direct: Turn off random mode.
Shuffle Random -> Shuffle: Turn off random mode.
Shuffle Random -> Random: Keep the current behavior.(or do noting?)
Shuffle Random -> Direct: Keep the current behavior.(or turn off random mode?)
Direct -> Shuffle: Keep the current behavior.
Direct -> Random: Turn on random mode.
Direct -> Shuffle Random:  Keep the current behavior.

**Comment by KoljaWindeler** [comment]
I'm not a big fan of the dropdowns anyway and haven't used them in my installation, but the improvments that you've made in the pull request improve them quite a bit. 

I'm not sure how many users are using the dropdowns but the suggested changes make also a lot of sense for me.

**Comment by mang1985** [comment]
Perhaps we can add an option in the config flow to enable/disable dropdowns, similar to the extra sensor. This way, users who do not want to use dropdowns will not have unnecessary entities in their system.
