### ISSUE TITLE
media_player.turn_off results in "AttributeError: 'list' object has no attribute 'lower'"

### ISSUE THREAD

**Issue by merdely** [KoljaWindeler/ytube_music_player#33]
I'm not sure when this started, but when I call the 'media_player.turn_off' service with 'media_player.ytube_music_player', I get the following in my log file:
```
2020-12-29 00:12:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139751139782368] 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 558, in async_turn_off
    await self.hass.async_add_executor_job(self.turn_off)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 319, in turn_off
    _player = self.hass.states.get(self._remote_player)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1048, in get
    return self._states.get(entity_id.lower())
AttributeError: 'list' object has no attribute 'lower'
```

I believe it's because hass.states.get() is expecting a single entity_id and it's being passed a list of entity_ids.

**Comment by KoljaWindeler** [comment]
hmm ok, so your _remote_player is a list .. that variable is initialized as list (for whatever reason) but should be overridden in the _update_remote_player function. 

That happens if you have a) a dropdown field for the media_player selection or b)  if you provide exactly ONE speaker as configuration argument. 

Could you copy your configuration so we can work this out?

**Comment by merdely** [comment]
What configuration are you looking for specifically?  All of my .yaml files for Home Assistant?

Thanks.

**Comment by KoljaWindeler** [comment]
Only the stuff that you've added for the component

**Comment by merdely** [comment]
In my configuration.yaml:
```
media_player:               
  - platform: ytube_music_player
    speakers:
      - all_speakers
```

In my input_selects.yaml:
```
ytube_music_player_source:
  name: Source
  icon: mdi:music-box-multiple
  options: # don't change
  - "Playlist Radio"
  - "Playlist"

ytube_music_player_speakers:
  name: Speakers
  icon: mdi:speaker
  options: # don't change
  - "loading"

ytube_music_player_playlist:
  name: Playlist
  icon: mdi:playlist-music
  options: # don't change
  - "loading"

ytube_music_player_playmode:
  name: Playmode
  icon: mdi:playlist-music
  options: ## don't change
  - "Shuffle"
  - "Random"
  - "Shuffle Random"
  - "Direct"
```

Let me know if you need anything else.

**Comment by KoljaWindeler** [comment]
Thanks, very strange. 
Could you activate the debug Infos and copy the output into this ticket?
https://github.com/KoljaWindeler/ytube_music_player#debug-information
Might be a lot but would certainly help .. 
Just to get it right: is only turning off an issue? 
Kolja

**Comment by merdely** [comment]
I tried to reproduce it today and cannot.  It seems to be working.

I'll try to get it to fail again and if I do, I'll do as you requested with debug-information.  Thank you for your help.

**Comment by merdely** [comment]
Yeah.  I'm still having this problem.  I wonder if the problem is that I'm calling the media_player.turn_off without it ever having been turned on.  I just tried enabling debug, playing some music, and calling the turn_off service.  It worked.  Then I called it again (and again) without playing any music.  I get a "STOP command requested but no session is active." but no errors.

I reenabled the logging and will try calling turn_off without using ytube and see if I get anything useful.

As I suspected, if I never use ytube, I get the error when calling the turn_off service.  But if I use it once and then call the turn_off service, even if it is already off, there is no problem.

I need to go through the log files I captured and make sure there isn't anything private in it.  Then I'll attach them tomorrow.

**Comment by KoljaWindeler** [comment]
Hi, no need to filter the log. Your description was perfect. I was able to reproduce and fix it 
https://github.com/KoljaWindeler/ytube_music_player/commit/9ac9a608dc1a252c780379f1efbd8e8a6c3a43e6
Thanks for raising this and tracking it down!

**Comment by merdely** [comment]
Awesome.  Thank you for fixing it and thank you for this cool software.
