### ISSUE TITLE
can't find header file at `/config/.storage/header_`

### ISSUE THREAD

**Issue by felipecrs** [KoljaWindeler/ytube_music_player#330]
**Enable DEBUG Output**

[error_log.txt](https://github.com/KoljaWindeler/ytube_music_player/files/15052937/error_log.txt)

**Describe the bug**
I have been receiving this notification every time HA starts:

![image](https://github.com/KoljaWindeler/ytube_music_player/assets/29582865/06ead482-834e-41e2-806e-e604ec0c6ed2)

**Version**
20240420.02

**To Reproduce**
Restart HA.

**Additional context**
```
This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:377
integration: yTubeMediaPlayer (documentation, issues)
First occurred: 2:46:13 PM (1 occurrences)
Last logged: 2:46:13 PM

can't find header file at /config/.storage/header_
```

Maybe not related, but I also receive this:

```
This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:276
integration: yTubeMediaPlayer (documentation, issues)
First occurred: 2:46:13 PM (1 occurrences)
Last logged: 2:46:13 PM

async_update_selects failed
```

**Comment by KoljaWindeler** [comment]
hi, i guess you need to rerun the setup .. it look like the entity has no name .. did you rename it afterwards?

**Comment by felipecrs** [comment]
Hm... I'm actually not sure anymore. But anyway, I'm not having this issue any longer. I'm closing it, but if someone faces the same issue and want be to reopen it, I can.
