### ISSUE TITLE
Clarification about the loaded tracks limit

### ISSUE THREAD

**Issue by OmerTu** [KoljaWindeler/ytube_music_player#333]
Hey,

What happens if I have a playlist with 1,000 songs and I set the 'Limit of simultaneously loaded tracks' to 100?
Will it always load the first 100 songs and shuffle between them?
Or will it load a random sample of 100 songs and then shuffle between them (until I call Stop and Play again)?

Thanks!

**Comment by KoljaWindeler** [comment]
Hi, the first .. the limit will be passed on to the API and only load the first xx tracks .. after that it will shuffle the list .. so yes you need to set it to a high number and risk that it loads longer ..
