### ISSUE TITLE
Please select a player before start playing, e.g. via the 'media_player.select_source' method or in the settings/config_flow

### ISSUE THREAD

**Issue by kyokusa** [KoljaWindeler/ytube_music_player#340]
Homeassistant:
Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

After updating to Homeasstant 2024.5.1, even selecting the media_player.ytube_music_player source still gives me the same error. The same thing if I play from media too.

**Comment by KoljaWindeler** [comment]
I didn't mean to close it .. but probably fixed it in the current release .. can you please try

**Comment by herrgismo** [comment]
I've tryed, same. Since 2024.5.1 no mediaplayer works.

**Comment by kyokusa** [comment]
Thanks yes.I solved it after the last update.

**Comment by KoljaWindeler** [comment]
> I've tryed, same. Since 2024.5.1 no mediaplayer works. 20240505.01

Hi, what do you mean with that? Are you getting the same error message? What players do you have installed?

**Comment by madskruger** [comment]
Unfortunately I'm having the same error
