### ISSUE TITLE
No matching entities found even though I have my usb audio connected and recognized by home assistant

### ISSUE THREAD

**Issue by moswald14** [KoljaWindeler/ytube_music_player#344]
can someone help me out? my google-fu did not succeed. I'm using a le potato with the prebuilt supervised image.

![halp](https://github.com/KoljaWindeler/ytube_music_player/assets/131550857/da5d492a-1b9c-43bb-9c65-d93f626ca61d)

**Comment by mang1985** [comment]
You need to install and configure either the VLC or MPD add-on, and then configure the corresponding integration, to have usable media_player entities appear in Home Assistant.

**Comment by moswald14** [comment]
awesome, I got down the right path thanks to you. tried to install vlc with ssh but adding it to the ha config would throw some errors that the only help for I got said to install vlc, which I did. so I thought i remembered vlc in the ha addon page, and so I added it there and after realizing my usb to audio card is jank and replacing it, it is now working great. thanks again.
