### ISSUE TITLE
Unfortunately we hit an error, please open a ticket - Integration no Longer Working

### ISSUE THREAD

**Issue by zachgoold** [KoljaWindeler/ytube_music_player#345]
**Enable DEBUG Output**
Enabled.

**Describe the bug**
No longer able to use the integration. Music just starts and stops immediately. Browsing only works until I get to the song itself then it says error.

Speaker turns off right after it tries to play any music (I have tried playing from albums/songs/menu/service calls etc):
![image](https://github.com/KoljaWindeler/ytube_music_player/assets/50751647/b6233774-e3ed-49f7-8a92-9b0e4494218d)

I can view playlists, but once I try and open a playlist or album it crashes with below:
![image](https://github.com/KoljaWindeler/ytube_music_player/assets/50751647/d4c091e0-fcfc-478d-a72f-50d1af460cd5)

Get this in the logs:
 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2024-05-11 17:43:21.855 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2024-05-11 17:43:21.855 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2024-05-11 17:43:21.855 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2024-05-11 17:43:21.860 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ytmusicapi/navigation.py", line 101, in nav
    root = root[k]

**Version**
20240505.01

**To Reproduce**
Use any part of the Integration such as browsing or trying to play.

**Additional context**
I have completely removed everything, restarted, reinstalled from HACS, and then restarted again, and added back the device. Same issue. The logs below are me adding a device with a freshly installed integration -> trying to browse -> error -> trying to play music -> turns on (I hear the ding from google) then turns off. 

[home-assistant_ytube_music_player_2024-05-12T04-57-27.289Z.log](https://github.com/KoljaWindeler/ytube_music_player/files/15285137/home-assistant_ytube_music_player_2024-05-12T04-57-27.289Z.log)

Any help is appreciated, I have grown to love this plugin and use it frequently, without it I am back to being a plebian using my voice to request songs.

**Comment by KoljaWindeler** [comment]
hi, could you try with the latest release? This is an error on the ytube side and I think it was fixed with the new version of the underlaying api lib that we're using

**Comment by oll-zacharygoold** [comment]
Yes this seems to have fixed it, thank you!
