### ISSUE TITLE
Échec de l'appel du service media_player/turn_on. 'NoneType' object has no attribute 'state'

### ISSUE THREAD

**Issue by SebastienMrc** [KoljaWindeler/ytube_music_player#346]
**Enable DEBUG Output**
[home-assistant_ytube_music_player_2024-05-12T18-06-48.757Z.log](https://github.com/KoljaWindeler/ytube_music_player/files/15287257/home-assistant_ytube_music_player_2024-05-12T18-06-48.757Z.log)

**Describe the bug**
I don’t know why but since a few months I can not use the integration and I have this error message that appears: 
Échec de l'appel du service media_player/turn_on. 'NoneType' object has no attribute 'state'

**Version**
HACS Version : 1.34.0

**To Reproduce**
1. Go to 'ytube_music_player recording'
2. Click on 'start'
3. See error : "Échec de l'appel du service media_player/turn_on. 'NoneType' object has no attribute 'state'"

Thanks

**Comment by KoljaWindeler** [comment]
hmm the part of '''Exception: Server returned HTTP 401: Unauthorized.''' concerns me.
Did it work for you before? I'd recommend to rerun the setup

**Comment by KoljaWindeler** [comment]
What version are you running that has this error?

**Comment by SebastienMrc** [comment]
For "ytube_music_player", I running 20240704.01 version. And for Home Assistant : 
<img width="587" alt="Capture d’écran 2024-07-12 à 19 15 45" src="https://github.com/user-attachments/assets/dc43143a-88d9-48ae-a347-1ae415c1e7f0">
