### ISSUE TITLE
Songs stop playing after one track + media picture not shown

### ISSUE THREAD

**Issue by XalaTheShepard** [KoljaWindeler/ytube_music_player#347]
Dear, 

When using the Ytube Music Player, the playlist stops after one song. 
Also, on the media players with a screen, the media picture is no longer shown. 
I have noticed that every time a song ends and you select the next one, the duration in the screen gets increased with the duration of the song. 
In my picture below, the song is only 3 to 4 minutes long, but since I manually selected play next song (after Ytube music player stopped at the end of the track without starting the next track), the total duration is more than 3,5 hours according to the player. 

If you have any more questions or comments, please do not hesitate to reply. 

Kind regards, 

Robin 
![Schermafbeelding 2024-05-20 004059](https://github.com/KoljaWindeler/ytube_music_player/assets/69390987/6cc4c668-3eda-42aa-8123-45ce40de9c26)

**Comment by KoljaWindeler** [comment]
hi, what player to you use as remote player .. like a chromecast or vlc etc

**Comment by XalaTheShepard** [comment]
Hi, I use Google mini and Google Nest Hub as devices

**Comment by KoljaWindeler** [comment]
hmm that should work .. I'm also using those .. can you create a log file with debug enabled? 
Please see the readme how to do it

**Comment by XalaTheShepard** [comment]
Logs show nothing out of the ordinary. Rebooted the Google devices and the issue is resolved for the Google mini's. However the issue is still there for the Google Nest Hub. Seems like an issue with Pychromecast. The media player of the Hub refuses to show the media image and stops playing after one song. Even my 7 year old Google Home does not have this issue

**Comment by XalaTheShepard** [comment]
[Uploading error_log-20.txt…]()

**Comment by XalaTheShepard** [comment]
Apologies, the errors appeared with a delay. Please find the logs above

**Comment by XalaTheShepard** [comment]
Dear KoljaWindeler, if you need any additional information, please do not hesitate to contact me. If I can help somehow, please also contact me. The issue seems only to occur with Google Nest Hub and not the other Google devices. Also, it is only an issue for the Ytubemediaplayer and not for other integrations as Spotcast and radio browser. Kind regards, Robin

**Comment by XalaTheShepard** [comment]
This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:277
integration: yTubeMediaPlayer (documentation, issues)
First occurred: 12:11:53 PM (52 occurrences)
Last logged: 5:14:07 PM

signature not found, decoding
- self decoded url return 403 status code, attempt 60/60

**Comment by XalaTheShepard** [comment]
Dear KoljaWindeler, 

I have done some digging and the issue has arisen since version 20240505.01 . I have returned to version 20240420.02 and the issue is no longer happening. Could this issue be the result of the new API? 

Kind regards, 

Robin

**Comment by KoljaWindeler** [comment]
Hi Robin, this is complicated to debug. 
One option is to remove the integration and readd it .. that will recreate a cookie and might work better.

403 -> means that youtube returs no access to the requested track and usually has something to do with the cookie

can you try that?

**Comment by XalaTheShepard** [comment]
Dear KoljaWindeler, 

Many thanks for looking into the issue. 
I have deleted the integration and added it again. However, still no luck with my Google Nest Hub (see image).
The playlist stops playing only on this device after one song and I still have to manually select after each song to play the next song. 
Also the media images are still not shown on the screen. 
I will add below any logs related to the integration, if available. 

Please note that this issue is resolved if I delete the integration and add it again with version 20240420.02 . 
So somewhere after this release the issue occured. 

Kind regards, 

Robin 

![Schermafbeelding 2024-06-07 160603](https://github.com/KoljaWindeler/ytube_music_player/assets/69390987/6948d212-4f20-442f-a24b-55ef94c909f4)

**Comment by XalaTheShepard** [comment]
Dear KoljaWindeler, 

Still the same error in the log: 

This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:277
integration: yTubeMediaPlayer (documentation, issues)
First occurred: 4:05:01 PM (4 occurrences)
Last logged: 4:05:07 PM

signature not found, decoding
- self decoded url return 403 status code, attempt 60/60

Kind regards, 

Robin

**Comment by XalaTheShepard** [comment]
Maybe a strange question, but might a factory reset of my Google Nest Hub solve the issue?

Kind regards,

Robin
