### ISSUE TITLE
Start playing music with integration, control via phone apps?

### ISSUE THREAD

**Issue by jockebq** [KoljaWindeler/ytube_music_player#348]
When I start playing music through my Nest Mini for example, I will be able to pull up my phone and open Youtube Music on iOS, it will show what's playing and let me control it.
But if I start playing with this integration, it seems like it does not pickup that my Youtube Music account is playing music. I have to use the phone app, start casting to the speakers again to then be able to control it.

Is there a way to do this?

**Comment by KoljaWindeler** [comment]
nope unfortunately not possible. there is no API from Youtube that Homeassistant can connect to .. at least not that I'm aware of it .. sorry. would be great, i know.
