### ISSUE TITLE
New Update Error Uploaded Artists

### ISSUE THREAD

**Issue by kyokusa** [KoljaWindeler/ytube_music_player#349]
Homeassistant:
Core 2024.5.5
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

Unfortunately after the last update 2024.5.5 it only plays online playlists all my uploads don't work. "It seems to load then freezes".

![Schermata del 2024-05-26 18-24-46](https://github.com/KoljaWindeler/ytube_music_player/assets/17881061/41f7e8b6-e4fe-4742-a5fe-861a71576885)

**Comment by KoljaWindeler** [comment]
fixed in https://github.com/KoljaWindeler/ytube_music_player/commit/112f6cbac97e3d7204f74669c2f461eadf11a464
