### ISSUE TITLE
Several bugs in logs

### ISSUE THREAD

**Issue by alexandrechoske** [KoljaWindeler/ytube_music_player#35]
Hi, i am having several bugs in logs, already tried to update my cookies, it was working properly, last week.

![image](https://user-images.githubusercontent.com/47279355/103443432-00cc3b80-4c3e-11eb-9ac5-05d906ffc8e6.png)

![image](https://user-images.githubusercontent.com/47279355/103443452-31ac7080-4c3e-11eb-8dd3-f9f3659dfb0b.png)

**Comment by KoljaWindeler** [comment]
Hmm did you link the header file explicitly in the config or do you have the "header_file" Option left out?

**Comment by alexandrechoske** [comment]
Hi folk, thanks for the quickly answer, what do you mean in **"header_file" option left out?**

I linked it correctly I guess because it was working last week, somehow it is not working anymore and also I noticed a change in my cookies.

do you know what this "VISITOR_INFO" means, in the cookies itself?
![image](https://user-images.githubusercontent.com/47279355/103443597-b21fa100-4c3f-11eb-9bbb-46ab11c092bf.png)
Last cookies was not with this information, dont know if maybe this may be cause of the problem.

The component is not loading anything, it is weird.

![image](https://user-images.githubusercontent.com/47279355/103443622-e5fac680-4c3f-11eb-8406-7c4a3bbf5e30.png)

**Comment by KoljaWindeler** [comment]
You're right. Doesn't look correct. Have you tried to grab a cookie from an incognito session?

**Comment by KoljaWindeler** [comment]
I mean that you CAN define the header_file and let it point to a filename ... If you do that you have to make sure that it is pointing to a correct header file ... That's all ...

**Comment by alexandrechoske** [comment]
> 
> 
> You're right. Doesn't look correct. Have you tried to grab a cookie from an incognito session?

For some reason mozilla shows cookies like that
I am doing some tests on chrome's cookie.

**Comment by KoljaWindeler** [comment]
Do you see the mentioned character somewhere in your file?
https://www.fileformat.info/info/unicode/char/2027/index.htm
By the way: this is a problem with the api and you should raise the bug at there issue tracker https://github.com/sigma67/ytmusicapi ..it would improve the code for everyone

**Comment by alexandrechoske** [comment]
> 
> 
> Do you see the mentioned character somewhere in your file?
> https://www.fileformat.info/info/unicode/char/2027/index.htm
> By the way: this is a problem with the api and you should raise the bug at there issue tracker https://github.com/sigma67/ytmusicapi ..it would improve the code for everyone

Hey man, i figured out.

The cookie was wrong.

As I said, mozilla shows the cookie wrong(dont know why).

Must be copied and paste Chrome's cookie to get it working properly.

Stays as a attention point to who else have this problem in the future.

**Comment by alexandrechoske** [comment]
> 
> 
> Do you see the mentioned character somewhere in your file?
> https://www.fileformat.info/info/unicode/char/2027/index.htm
> By the way: this is a problem with the api and you should raise the bug at there issue tracker https://github.com/sigma67/ytmusicapi ..it would improve the code for everyone

thank you so much for your attention and help.

happy 2021 =)
