### ISSUE TITLE
pytube.exceptions.RegexMatchError: map_functions: could not find match for multiple

### ISSUE THREAD

**Issue by jurgenweber** [KoljaWindeler/ytube_music_player#353]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
I can not play any music this morning, error in HASS;

```
2024-08-09 08:36:40.536 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140469009725136] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1623, in async_play_media
    if(not(await self.async_prepare_play())):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 617, in async_prepare_play
    await self.async_get_cipher('BB2mjBuAtiQ')
  File "/config/custom_components/ytube_music_player/media_player.py", line 735, in async_get_cipher
    self._cipher = pytube.cipher.Cipher(js=self._js)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 48, in patched__init__
    self.transform_map = pytube.cipher.get_transform_map(js, var)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytube/cipher.py", line 250, in get_transform_map
    fn = map_functions(function)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytube/cipher.py", line 697, in map_functions
    raise RegexMatchError(caller="map_functions", pattern="multiple")
pytube.exceptions.RegexMatchError: map_functions: could not find match for multiple
```

**Version**
20240709.01

**To Reproduce**
just try and play a song

**Additional context**
This was happening on the latest 2024.07 release and I restarted and upgraded HASS and I still have the problem.

Thanks

**Comment by zachgoold** [comment]
Same issue. I updated the latest version of hass and that's most likely caused the problem

**Comment by jurgenweber** [comment]
Well, I had it on 2024.07.4 and 2024.08.0

**Comment by jurgenweber** [comment]
Here, I picked it; https://github.com/pytube/pytube/issues/2005

**Comment by michguy2000** [comment]
I have the same issue.  I'm on the current release.  Uninstalled and re-installed the integration, but still have the same issue for youtube albums and playlists.  Thanks and regards.

**Comment by Zuvuya42** [comment]
Exact same issue here

**Comment by aliakseis** [comment]
For me, this modification of the def get_transform_map of cipher.py seems to improve the situation:

 
    transform_object = get_transform_object(js, var)
    mapper = {}
    for obj in transform_object:
        # AJ:function(a){a.reverse()} => AJ, function(a){a.reverse()}
        name, function = obj.split(":", 1)
        if function == '"jspb"':
            continue
        fn = map_functions(function)
        mapper[name] = fn
    return mapper

**Comment by rugal7699** [comment]
> For me, this modification of the def get_transform_map of cipher.py seems to improve the situation:
> 
> ```
> transform_object = get_transform_object(js, var)
> mapper = {}
> for obj in transform_object:
>     # AJ:function(a){a.reverse()} => AJ, function(a){a.reverse()}
>     name, function = obj.split(":", 1)
>     if function == '"jspb"':
>         continue
>     fn = map_functions(function)
>     mapper[name] = fn
> return mapper
> ```

Where can I get cipher.py and modify it?

**Comment by aliakseis** [comment]
[rugal7699](https://github.com/rugal7699) Exact place depends on your OS, but it is going to be somewhere in something like  ../Lib/site-packages/pytube/ folder. You only need to add the two lines to the cipher.py file placed like above:

    if function == '"jspb"':
        continue

and bear in mind that Python is sensitive to formatting.

**Comment by dennisracine** [comment]
Having is issue as well.

**Comment by liangleslie** [comment]
https://github.com/pytube/pytube/issues/2005#issuecomment-2278163017

This worked for me. On my HA Core 2024.8.0, the file was at `/usr/local/lib/python3.12/site-packages/pytube/cipher.py`

> [rugal7699](https://github.com/rugal7699) Exact place depends on your OS, but it is going to be somewhere in something like ../Lib/site-packages/pytube/ folder. You only need to add the two lines to the cipher.py file placed like above:
> 
> ```
> if function == '"jspb"':
>     continue
> ```
> 
> and bear in mind that Python is sensitive to formatting.

**Comment by DravenSA** [comment]
I have the same problem and I cannot find any path to cipher.py
HA Installed on a NUC

Core 2024.8.0
Supervisor 2024.08.0
Operating System 12.4
Frontend 20240806.1

**Comment by teo-luc** [comment]
It's not the **ytube_music_player**'s issue, it's related to **pytube** lib.

### [How to fix]

1. First, please use the [SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh) and install it on your HA
2. Goto the **Settings/Addon/SSH & Web Terminal:** Disable the protection and restart the addon
3. Open the **SSH & Web Terminal** and enter this command to access the core:
` docker exec -it homeassistant bash`
4. After that, access to the python folder by the command: (it depends on your python version, on my side, it's  'python3.12'
`cd /usr/local/lib/python3.12/site-packages/pytube`
5. Continuing with this command to modify the 'cipher.py' file
`vi cipher.py`
6. Follow the instruction [here](https://github.com/pytube/pytube/issues/2005#issuecomment-2278163017) to modify the line: 274, 232
7. Pressing the `ESC` and `:wq` and `ENTER` to save the change
8. Restart your HA if you are still getting the error after adding the `if function == '"jspb"':` (Optional)

Hope this will help you guys.

**Comment by KoljaWindeler** [comment]
fixed as temporary workaround https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20240810.01 until this will be fixed by pytube

**Comment by michguy2000** [comment]
> I have the same problem and I cannot find any path to cipher.py HA Installed on a NUC
> 
> Core 2024.8.0 Supervisor 2024.08.0 Operating System 12.4 Frontend 20240806.1

Same Here except I'm on Raspberry Pi 4

**Comment by jurgenweber** [comment]
Thanks for rolling the temp fix out, appreciated.
