### ISSUE TITLE
Lost connection with youtube music

### ISSUE THREAD

**Issue by Idaho947** [KoljaWindeler/ytube_music_player#360]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
My youtube media playeur stop working this morning. It can't load my playeur and playlist
**Version**
2024.08.10.1
**To Reproduce**
1. Go to intergration
2. Click on nothing
4. See blank space :

![image](https://github.com/user-attachments/assets/5b10b7ab-3957-4aa7-aaf0-1afa4bb33a85)

see that inlog when I want to change the player :
```
Enregistreur: homeassistant.components.automation.interrupteur_youtube_sdb
Source: components/automation/__init__.py:776
intégration: Automatisation (documentation, problèmes)
S'est produit pour la première fois: 06:51:44 (2 occurrences)
Dernier enregistrement: 06:52:01

Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:333
intégration: yTubeMediaPlayer (documentation, problèmes)
S'est produit pour la première fois: 09:40:54 (3 occurrences)
Dernier enregistrement: 09:40:56

[S] async_update
[S] async_get_cipher [E]
[S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 1.8.0 [E]
```

Seems it lost the connection with youtube music. I don't when where I can reload it?

Error while executing automation automation.interrupteur_youtube_sdb: Option Nest mini salle de bain is not valid for entity select.ytube_music_player_speaker, valid options are:

Thanks

**Comment by Idaho947** [comment]
I have this bug again after a reboot. Someone know what I have to do ? IIt's not very fun to reset an other time all my automatisation.

**Comment by KoljaWindeler** [comment]
Honestly No idea.. still works here. Have you tried to reconfigure the integration?

**Comment by Idaho947** [comment]
How can I do that ? 
I juste have this when I click on valider nothing change :
![Uploading Screenshot_20240923-220906.png…]()

**Comment by Idaho947** [comment]
An other time this week end... How can I reload the integraiton ?

**Comment by KoljaWindeler** [comment]
I don't know... If restarting Homeassistent doesn't work then I'd delete the integration and redo the setup m. Homeassistent will assign the same entity id and all the other parts should keep working I guess .. honest .. never had that issue so I'm just guessing

**Comment by Idaho947** [comment]
I already try to delete and reinstall the intégration and I have to reset all my automatisation.

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20241125.01

**Comment by Idaho947** [comment]
Seems to be ok with cookie authentification
