### ISSUE TITLE
Can't play album after 20241027.1 upgrade

### ISSUE THREAD

**Issue by chicagoandy** [KoljaWindeler/ytube_music_player#363]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information
[home-assistant_ytube_music_player_2024-10-27T21-21-00.830Z.log](https://github.com/user-attachments/files/17535480/home-assistant_ytube_music_player_2024-10-27T21-21-00.830Z.log)

Debug logs are attached.
**Describe the bug**
After upgrading to 20241027.1 I am still unable to play an album.    Playing individual songs does work, but the album will not play.

**Version**
20241027.1

**To Reproduce**
Playing albumb via Custom Mini Play button:
  buttons:
    - icon: mdi:moon-waxing-crescent
      type: album
      id: OLAK5uy_mIG6ZEKJI7OyoOxiYTPTkAaJiMGA-5wh0

Thanks

**Comment by KoljaWindeler** [comment]
I don't think that this is a valid album id.
Try MPREb_FxTG7aVEzCT

**Comment by chicagoandy** [comment]
Started working today.   Very odd.
