### ISSUE TITLE
Impossible de start Music after first configuration 

### ISSUE THREAD

**Issue by juliiod** [KoljaWindeler/ytube_music_player#379]
**Enable DEBUG Output**
I got the followin error :

pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js

**Describe the bug**

After configuration, I can select music or playlist, but I try to start music I got the following error:

pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js 

**Version**
20241125.01

**To Reproduce**
1. Go to media player
2. search a music or playlist, click on play
3. See error : "pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js"

**Additional context**

Thanks

**Comment by KoljaWindeler** [comment]
please try https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20241210.01

**Comment by juliiod** [comment]
Thank you, it s working now
