### ISSUE TITLE
Sonos intergration?

### ISSUE THREAD

**Issue by 18084AZ** [KoljaWindeler/ytube_music_player#38]
Hi! I wonder if it’s able to play the music through Sonos speaker? I have the options to choose my sonos speakers and it starts to play but there is no sound coming out of the speaker. 
Is this just compatibility issue or should I be able to play music through my Sonos speaker? Google devices works great to play music through.

**Comment by KoljaWindeler** [comment]
Hi, we had that issue before and as of now it seams like sonos isn working.

 I'd bet that it is possible to solve this, as it is simply a mp3 stream .. but I don't have a sonos and it would require to debug the sonos python api. 

So for now: not supported

**Comment by 18084AZ** [comment]
Alright, too bad.. If there is anything I can do or provide with to solve the issue just tell me ;)

**Comment by KoljaWindeler** [comment]
Have a look at https://community.home-assistant.io/t/youtube-music-media-browser/226367/190?u=jkw

There are still unanswered points/tasks

**Comment by KoljaWindeler** [comment]
Hi,

please try adding the two config values **proxy_path** and **proxy_url** to your configuration.
The proxy path has to point to your www folder, if you are using a docker image "/config/www" should be correct.
Proxy url has to point to the local url. 

The integration will download the ytube stream and store it at the proxy_path. Once the download finished 
the sonos will receive the link from proxy_url and play the local file

```yaml
media_player:
  - platform: ytube_music_player
    speakers: 
       - media_player.jkw_cast2
    proxy_path: "/config/www"
    proxy_url: "http://192.168.2.43:8123/local"
```

This is highly experimental and NOT tested. (I don't have a Sonos).
Nothing will change if the two parameter aren't provided.

**Comment by 18084AZ** [comment]
I am using HA on a raspberry pi 4 so I guess the proxy path should be “/local” only?

Skickat från min iPhone

6 jan. 2021 kl. 22:07 skrev Kolja Windeler <notifications@github.com>:

﻿

Hi,

please try adding the two config values proxy_path and proxy_url to your configuration.
The proxy path has to point to your www folder, if you are using a docker image "/config/www" should be correct.
Proxy url has to point to the local url.

The integration will download the ytube stream and store it at the proxy_path. Once the download finished
the sonos will receive the link from proxy_url and play the local file

media_player:
  - platform: ytube_music_player
    speakers:
       - media_player.jkw_cast2
    proxy_path: "/config/www"
    proxy_url: "http://192.168.2.43:8123/local"

This is highly experimental and NOT tested. (I don't have a Sonos).
Nothing will change if the two parameter aren't provided.

**Comment by KoljaWindeler** [comment]
Wherever the data is stored the you can access via the web url, from inside the container.
Just "/local/" seams strange, but it's possible. I don't run a pi imagine. Sorry can't help

**Comment by denvers** [comment]
Tested it. No sound unfortunately.

My config:

```
media_player:
  - platform: ytube_music_player
    speakers:
      - media_player.sonos_connect_amp
    proxy_path: "/config/www"
    proxy_url: "https://drsnuggles.local:8123/local"
```

Error messages:

```
Logger: homeassistant.components.sonos.media_player
Source: components/sonos/media_player.py:481
Integration: Sonos (documentation, issues)
First occurred: 9:59:18 (5 occurrences)
Last logged: 10:00:44

Error on play_media with UPnP Error 701 received: Transition not available from 192.168.1.30
```

```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:306
Integration: YouTube Music Player (documentation, issues)
First occurred: 9:59:14 (2 occurrences)
Last logged: 9:59:49

self._state is: (playing).
```

**Comment by KoljaWindeler** [comment]
Please try your local ip instead of https://drsnuggles.local:8123/local
Something like http://192.168.1.3:8123/local .. something the sonos can connect to

**Comment by denvers** [comment]
Tried several options (https/http/local ip/external ip/etc), but for now same issue.

**Comment by wuism** [comment]
I have sonos integration and this works for me.

i used for the proxy path the following:

http://192.168.1.xxx:8123/local
/config/www

running hassos on NUC

**Comment by KoljaWindeler** [comment]
THANK YOU 
very nice to hear back that it is working!

**Comment by kingzize** [comment]
> I have sonos integration and this works for me.
> i used for the proxy path the following:
> http://192.168.1.xxx:8123/local
> /config/www
> 
> running hassos on NUC

Sorry for being a noob, but where do you put this code? In the configuration.yaml?

**Comment by KoljaWindeler** [comment]
you can now add this during the config flow

**Comment by kingzize** [comment]
> you can now add this during the config flow

Thank you so much - its working now :)

Just a small suggestion would be to differentiate the description of the two fields to indicate     proxy_path/proxy_url

![Udklip](https://user-images.githubusercontent.com/79306514/109142103-c626e100-775e-11eb-8715-0266c7c13533.PNG)

**Comment by KoljaWindeler** [comment]
Agreed :)
https://github.com/KoljaWindeler/ytube_music_player/commit/08d528aa7ecf9b966b0de03fe29f150f6cd811b1#diff-770a83331b0d7769c98ac72bfd4c3b62e984977322f69ef08b5c67cf3b70b043

**Comment by baldarn** [comment]
I can confirm that is working on sonos bookshelf ikea symfonisk!! thanks!

**Comment by tomfool1985** [comment]
> I can confirm that is working on sonos bookshelf ikea symfonisk!! thanks!

How???

**Comment by KoljaWindeler** [comment]
I'd assume like this https://github.com/KoljaWindeler/ytube_music_player#sonos-fix

**Comment by tomfool1985** [comment]
Thanks i did it, but it doesn't work.

I think Is something related to the local path, what did you put?

Thanks

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jurgenweber** [comment]
The proxy thing seems to work fine, how can I send it to a group?

**Comment by gmarcc** [comment]
Would someone kindly post a step-by-step on how to get this working for Sonos?

**Comment by KoljaWindeler** [comment]
It's not possible anymore.

**Comment by Backslashh** [comment]
> It's not possible anymore.

So Sonos speakers don't work with YouTube Music Player anymore?
