### ISSUE TITLE
hi there is a issue with intergration

### ISSUE THREAD

**Issue by ghostrobo282** [KoljaWindeler/ytube_music_player#40]
hi i am having a issue where my one keeps i select a playlist and forever keeps looping on the loading then cancels forever i dont know how to fix and would greatly appricate some help

Thanks

ghost

**Comment by KoljaWindeler** [comment]
I don't understand the question

**Comment by ghostrobo282** [comment]
do you want me to attach a video to show you

**Comment by ghostrobo282** [comment]
Fixed it thanks
