### ISSUE TITLE
Song progression when speaker is a chromecast?

### ISSUE THREAD

**Issue by kebel87** [KoljaWindeler/ytube_music_player#41]
Hi, 

thank you for your excellent work, it's truly awesome!

I might simply be dumb, but I haven't find how to show the progression of the currently playing song when speaker is a chrome cast device. Is it expected behaviour or have I did something wrong?

EDIT : using the media-mini-player from kalkih.

Thanks!

**Comment by KoljaWindeler** [comment]
That is expected.. the real playback will be on a different player .. that is advancing .. that should have a media position but the ytubeplayer itself .. I'll keep this open just to see if it can be synchronized somehow .. but as of now .. nope

**Comment by KoljaWindeler** [comment]
turns out that it is in fact possible .. and fairly easy. 
implemented in https://github.com/KoljaWindeler/ytube_music_player/commit/f4219bd5c2643a839ff030ffd90c415d244397ec
Will test for a while and release a new version if it works flawless here
