### ISSUE TITLE
Buy you a coffee or beer

### ISSUE THREAD

**Issue by tprelog** [KoljaWindeler/ytube_music_player#43]
**Is your feature request related to a problem? Please describe.**

I really like what you're doing here. I appreciate all the work you have already done and I'm looking forward to some of the future improvements you have mentioned in the forum.  I know this is a lot of work and I want to help, however I am unable to contribute quality code so I would like to have another way I can contribute.

**Describe the solution you'd like**

I would like a  link to buy you a coffee or something similar

**Describe alternatives you've considered**

Becoming GitHub sponsor

**Additional context**

NA

**Comment by KoljaWindeler** [comment]
Hi, thanks for your ongoing support in the forum.  And thanks for raising this idea. 
https://github.com/KoljaWindeler/ytube_music_player#support

**Comment by tprelog** [comment]
Thanks for the link! I just tried it out :wink:

**Comment by KoljaWindeler** [comment]
wow! Thanks a lot! really appreciate it!
