### ISSUE TITLE
cookie issue on latest release 20200110

### ISSUE THREAD

**Issue by v-alvex** [KoljaWindeler/ytube_music_player#48]
Hello,
the integration fails to set up via the config flow, due to cookie error (on v. 20200110).
Error says 'Something with your cookie wasn't right. Format and fields are ok but the login failed'.

Previous version worked fine.
Tried different browsers, different PCs and log out - log in.

Raising this issue to see if it is something wrong with my cookie or a more general problem.

Thanks for your work.

**Comment by KoljaWindeler** [comment]
Hi, I'm really not sure how to help here. 
Have you tried getting that cookie in an incognito session? 

There should also be a error in your log that is raised by the sub api every time you hit "send" , that might help as well.

**Comment by v-alvex** [comment]
Incognito doesn't work either.
Here's the log output.

`Traceback (most recent call last): File "C:\Users\Administrator\AppData\Roaming\.homeassistant\custom_components\ytube_music_player\const.py", line 245, in check_data api = YTMusic(user_input[CONF_HEADER_PATH]) File "c:\users\administrator\homeassistant\lib\site-packages\ytmusicapi\ytmusic.py", line 97, in __init__ response = self._send_request('guide', {}) File "c:\users\administrator\homeassistant\lib\site-packages\ytmusicapi\ytmusic.py", line 108, in _send_request response = requests.post(base_url + endpoint + params + additionalParams, File "c:\users\administrator\homeassistant\lib\site-packages\requests\api.py", line 119, in post return request('post', url, data=data, json=json, **kwargs) File "c:\users\administrator\homeassistant\lib\site-packages\requests\api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "c:\users\administrator\homeassistant\lib\site-packages\requests\sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "c:\users\administrator\homeassistant\lib\site-packages\requests\sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "c:\users\administrator\homeassistant\lib\site-packages\requests\adapters.py", line 439, in send resp = conn.urlopen( File "c:\users\administrator\homeassistant\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen httplib_response = self._make_request( File "c:\users\administrator\homeassistant\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request conn.request(method, url, **httplib_request_kw) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1255, in request self._send_request(method, url, body, headers, encode_chunked) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1266, in _send_request self.putrequest(method, url, **skips) File "c:\users\administrator\homeassistant\lib\site-packages\urllib3\connection.py", line 199, in putrequest return _HTTPConnection.putrequest(self, method, url, *args, **kwargs) File "c:\users\administrator\homeassistant\lib\site-packages\homeassistant\util\async_.py", line 120, in protected_loop_func check_loop() File "c:\users\administrator\homeassistant\lib\site-packages\homeassistant\util\async_.py", line 91, in check_loop raise RuntimeError( RuntimeError: Detected I/O inside the event loop. This is causing stability issues. Please report issue`

**Comment by KoljaWindeler** [comment]
i've just added pictures to the setup 
https://github.com/KoljaWindeler/ytube_music_player#setup
could you double check if this is exactly what you do.

**Comment by v-alvex** [comment]
Sure these are the steps that I've followed. 
Also, the previous version worked fine with the same steps and the cookie was accepted.

**Comment by KoljaWindeler** [comment]
well you could remove the two lines:

api = YTMusic(user_input[CONF_HEADER_PATH])
api.get_library_songs()

from the const.py here 

https://github.com/KoljaWindeler/ytube_music_player/blob/5fc321ba0a157f387838d3bd6faa111ec4cc1125/custom_components/ytube_music_player/const.py#L245

and see if it work for real .. honestly I don't see how it could work inside the component if it fails during the setup

**Comment by sigma67** [comment]
Sorry, have not seen anything similar. Seems related to your implementation

**Comment by v-alvex** [comment]
I've removed the lines, the integration loads but then the player doesn't work.

Anyway, I switched back to the old version with the yaml configuration.
The same cookie works in that case, so I'll stick to thar for now.

Thanks!

**Comment by KoljaWindeler** [comment]
fair enough .. I'll keep thinking about it :)
