### ISSUE TITLE
Error: Cookie wasn't right while setting up integration. 

### ISSUE THREAD

**Issue by JoeAverge9** [KoljaWindeler/ytube_music_player#49]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled

**Version**
please provide the version you are using (see HACS)

**To Reproduce**
1. Go to 'Open Configuration -> Integrations -> "add integration" -> "YouTube Music Player".'
2. Paste Cookie
2. Click on 'Submit'
3. See error
Something with your cookie wasn't right. Format and fields are ok but the login failed
**Additional context**
Something with your cookie wasn't right. Format and fields are ok but the login failed

I am using Google 2 factor authentication

Thanks

**Comment by KoljaWindeler** [comment]
Thanks for reporting, I'm really not sure how to help here.
Have you tried getting that cookie in an incognito session?

There should also be a error in your log that is raised by the sub api every time you hit "send" , that might help as well.

Is this the very same cookie that you've used in previous version?

**Comment by JoeAverge9** [comment]
Thanks, Seems using incognito mode allowed the integration to now install
________________________________

**Comment by KoljaWindeler** [comment]
Perfect
