### ISSUE TITLE
HA detected I/O inside the event loop

### ISSUE THREAD

**Issue by dreimer1986** [KoljaWindeler/ytube_music_player#51]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled

Two Log entries from HA asking me to send them to you.
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ytube_music_player doing I/O at custom_components/ytube_music_player/const.py, line 245: api = YTMusic(user_input[CONF_HEADER_PATH])
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ytube_music_player doing I/O at custom_components/ytube_music_player/const.py, line 246: api.get_library_songs()

**Version**
please provide the version you are using (see HACS)
20200110

**To Reproduce**
Just start HA with the addin installed. (Used the new way btw aka removed all remnants of the former way from configuration.yaml and cleanly reinstalled it)

**Additional context**

Thanks

**Comment by KoljaWindeler** [comment]
Yep, thanks. That is only happening during the installation. During that phase I can't figure out a way to get the test working async, later on, everything should run in async manner .. so i guess this is ... acceptable :) 
Thanks for reporting anyway, but for now I won't work on it.
