### ISSUE TITLE
Stops after one song

### ISSUE THREAD

**Issue by Stephan296** [KoljaWindeler/ytube_music_player#53]
Stop with playing music after one song, with albums and playlists

**Comment by KoljaWindeler** [comment]
Is this the same?
https://github.com/KoljaWindeler/ytube_music_player/issues/47

**Comment by Stephan296** [comment]
i use sonos as output, but i have update the files as you ask in that threat and i added an automation. After a restart there is nothing changed.

**Comment by KoljaWindeler** [comment]
Oh interesting .. so you have a working sonos setup. Neat. 
Let's see it we can get auto track advance working. 

Please enable debug (see readme) and copy as much from the log as possible. Most important: please cover the time when your sonos stops playing (and please mention when that approximately is)

**Comment by Stephan296** [comment]
this is what the log gaves:

```
2021-01-12 21:48:07 DEBUG (SyncWorker_20) [custom_components.ytube_music_player.media_player] _sync_player
2021-01-12 21:48:07 DEBUG (SyncWorker_20) [custom_components.ytube_music_player.media_player] media_player.zolder: playing -> paused ```

**Comment by KoljaWindeler** [comment]
So a sonos changes at the end of a track from playing to paused?
And that happens exactly at the end of a track?

**Comment by Stephan296** [comment]
Yes, exactly at the end of the track.
________________________________

**Comment by KoljaWindeler** [comment]
Ok, I'll add a "pause_to_idle" command tomorrow. Basically the same that we needed for the mpd with off_to_idle. Can you test that without a release? All you have to do is to download two files and replace them the one in your installation ..  I'll post the links here when I'm done

**Comment by Stephan296** [comment]
Perfect, no problem!
________________________________

**Comment by KoljaWindeler** [comment]
https://raw.githubusercontent.com/KoljaWindeler/ytube_music_player/main/custom_components/ytube_music_player/const.py
https://raw.githubusercontent.com/KoljaWindeler/ytube_music_player/main/custom_components/ytube_music_player/media_player.py

also please call 
`ytube_music_player.call_method` with 
**entity_id: media_player.ytube_music_player**
**command: paused_is_idle**

**Comment by KoljaWindeler** [comment]
I've published a new package .. so you don't have to download the files individually

**Comment by Stephan296** [comment]
thx a lot! I have still add this with an automation:
entity_id: media_player.ytube_music_player
command: paused_is_idle

**Comment by KoljaWindeler** [comment]
so i guess it is working for you and you can now listen on your sonos  continuously ?

**Comment by Stephan296** [comment]
Perfect!! It works!

**Comment by KoljaWindeler** [comment]
Sweet, enjoy your music.. i'll close this.
