### ISSUE TITLE
Playlists not coming through, also clarification on usage

### ISSUE THREAD

**Issue by Alfiegerner** [KoljaWindeler/ytube_music_player#54]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled

Great work on this, thank you very much.  I have playlists in youtube music that aren't coming through either to the media browser or the input_select.

**Version**
please provide the version you are using (see HACS) latest from HACS

**To Reproduce**

I've added some playlists, and can play them from ytube fine if I specify the id, but I can't see them in homeassistant.

![image](https://user-images.githubusercontent.com/596188/105022410-9d9c2f00-5aae-11eb-884b-526d3192671b.png)

Only 'Your Likes' is available.

![image](https://user-images.githubusercontent.com/596188/105022540-c290a200-5aae-11eb-9937-757dc3261de4.png)

**Additional context**

Thanks

**Comment by Alfiegerner** [comment]
Also, for clarification, I'm wondering how to use the select list options.

Can we use them to set up how we want to play, and then hit 'play' somewhere to start from those settings?  Or is the idea to use them to change things once streaming?

Thanks for you all your effort on this, looking really good so far.

**Comment by KoljaWindeler** [comment]
Hi, so the first part is really a new bug .. your Liked Music playlist works?
Interesting that you only see one list .. 

can you please enable debug output and copy it into this ticket.

The idea about the dropdowns is to set the up as liked (choose the playlist, random mode etc) and turn_on the player.
But you can also use the media browser... basically a second independent path.

**Comment by sigma67** [comment]
Please ensure that the correct account is selected. I remember another user that eventually found a "lost" account which was being used instead (the one who sent me his cookie). The symptoms look much the same here.

**Comment by KoljaWindeler** [comment]
Exactly, please read https://github.com/sigma67/ytmusicapi/issues/141 @Alfiegerner

**Comment by KoljaWindeler** [comment]
Hey @Alfiegerner is this still an issue?
