### ISSUE TITLE
Integration not showing up

### ISSUE THREAD

**Issue by mark1foley** [KoljaWindeler/ytube_music_player#55]
Hi,

The integration never shows up for me under Configuration -> Integrations -> Add Integration.  I have tried several different browsers, cleared the browser cache, restarted HA all to no avail.

Any ideas?

Thanks,

Mark

**Comment by KoljaWindeler** [comment]
Did you refresh the integration page? Simply F5

**Comment by mark1foley** [comment]
Yes, many times and in different browsers, as well as using the mobile HA client.  

Also, if it is an approved HA integration (as opposed to a HACS one) I think it would be shown on the website (https://www.home-assistant.io/integrations/) but it doesn't seem to be.

**Comment by KoljaWindeler** [comment]
Correct, it's a custom component. Did you install it via hacs?

**Comment by KoljaWindeler** [comment]
is this still an issue?

**Comment by mark1foley** [comment]
No, as I worked out how to install it via HACS.  I am very appreciative of all the effort you have gone to to provide this functionality.  As a relatively new user to HA I would like to suggest adding a little more detail on how to install it using HACS to the install section of the readme file could help others.

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player/blob/main/README.md#installation-via-hacs
