### ISSUE TITLE
Sonos doesn't play the next song

### ISSUE THREAD

**Issue by Stephan296** [KoljaWindeler/ytube_music_player#58]
When i use your mediaplayer with my sonos it doens't play the next song. The player is showing playing as state but there is no sound.
Also both automations in your wiki doesn't fix the problem.

**Comment by KoljaWindeler** [comment]
I kind of have a deja vu
https://github.com/KoljaWindeler/ytube_music_player/issues/53
Isn't this the same?

**Comment by Stephan296** [comment]
I have also a deja vu 😉
After the last update, it doesn’t work anymore. He state goes now to “off” after a song.

Van: Kolja Windeler <notifications@github.com>
Verzonden: zaterdag 23 januari 2021 21:55
Aan: KoljaWindeler/ytube_music_player <ytube_music_player@noreply.github.com>
CC: Stephan296 <stephan296@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [KoljaWindeler/ytube_music_player] Sonos doesn't play the next song (#58)


I kind of have a deja vu
#53<https://github.com/KoljaWindeler/ytube_music_player/issues/53>
Isn't this the same?

**Comment by KoljaWindeler** [comment]
So the debug shows that it changes to off? 
Can you copy a bit of the log into this ticket?

**Comment by Stephan296** [comment]
You can closed this issue, the sonos fix is not necessary anymore! He plays perfect!
