### ISSUE TITLE
[Warning]: Detected I/O inside the event loop

### ISSUE THREAD

**Issue by prithvi1974** [KoljaWindeler/ytube_music_player#59]
**Warning**
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 2:11:34 (4 occurrences)
Last logged: 2:12:07

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ytube_music_player doing I/O at custom_components/ytube_music_player/const.py, line 265: api = YTMusic(path)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ytube_music_player doing I/O at custom_components/ytube_music_player/const.py, line 299: api.get_library_songs()

**Version**
1.10.1

**To Reproduce**
1. Toggle the player

**Comment by KoljaWindeler** [comment]
Duplicate  https://github.com/KoljaWindeler/ytube_music_player/issues/51
