### ISSUE TITLE
support for kodi ? 

### ISSUE THREAD

**Issue by henrikhjelm** [KoljaWindeler/ytube_music_player#6]
will it be support for kodi ?

**Comment by KoljaWindeler** [comment]
Please specify what you mean.
This is a custom component for home assistant. Not for kodi.
So I tend to say no

**Comment by henrikhjelm** [comment]
did get it to work whid chrome cast in home assistant. 
but not whid kodi media player in home assistant. 

get error like : 
Unable to find referenced entities media_player.henke_kontor <-- chrome cast
Unable to find referenced entities media_player.henke_libreelec <-- kodi

yea it is the correct name.

**Comment by henrikhjelm** [comment]
when i try to play music the keyboard is showing on the screen. and not starting
to kodi media player in ha

**Comment by KoljaWindeler** [comment]
Hmm I guess this is really an issue with the media_player component. 
I see a similar behavior with the yamaha component. I'd assume that the super long URLs might be the issue. Those are easily 100+ chars long

**Comment by KoljaWindeler** [comment]
Hi, I've just looked at the kodi integration and it doesn't have a play media service that works with an url, or am I just not seeing it?

**Comment by henrikhjelm** [comment]
media_player.play_media

entity_id: media_player.kodi_8c3e8a3f19f9476d615ec83768e0d6e3
media_content_id: https://sverigesradio.se/topsy/direkt/216-hi-mp3.m3u
media_content_type: audio/mp3

is working

**Comment by KoljaWindeler** [comment]
Interesting option. Have you tried to put a youtube link into a m3u list that is store in the www folder and send the link to kodi?

**Comment by henrikhjelm** [comment]
can check, in your script. how does the url look like in there ?

**Comment by KoljaWindeler** [comment]
Please send me a mail to kkoolljjaa@gmail.com so I can send you direct instructions ;)

**Comment by KoljaWindeler** [comment]
added with https://github.com/KoljaWindeler/ytube_music_player/commit/57874872a97bfdfdc0f925c5678048352283ee66
