### ISSUE TITLE
Disables Google Home Playback Control

### ISSUE THREAD

**Issue by Myztillx** [KoljaWindeler/ytube_music_player#61]
When playing music through this integration, I can no longer use some Google Home (the player I'm casting to) to control playback (skip does not work, but play and pause seem to). Not sure if this is a limitation of how the integration works, or a limitation of the ytubemusic API.

Just wondering if this is working as intended?

Thanks.

**Comment by KoljaWindeler** [comment]
Hi, well the issue is that the integration is only sending one track to the google home at the time. 
so it can't skip to the next track. Sorry that's just the way it works.
