### ISSUE TITLE
[FR] Youtube video library?

### ISSUE THREAD

**Issue by AalianKhan** [KoljaWindeler/ytube_music_player#63]
**Is your feature request related to a problem? Please describe.**

Currently, you can cast youtube videos to your Chromecast, etc using the play_media service. 
With this component, I can see my playlists saved on my youtube account that contains music which is a useful feature as I can just save or create a playlist in my youtube account and it will dynamically update HA. Sometimes my playlists contain videos and it will give an error when attempting to play it as the component is using the wrong media_content_id (cus its made for music only). 
This got me wondering if it will be possible to dynamically import the youtube video library using this. This will make it possible to easily choose and play playlists such as web series easily. 

**Describe the solution you'd like**

A similar component like yt_music_player for youtube videos. 

**Describe alternatives you've considered**

You can currently play playlists using automation and such but I like the media browser and will like to use it as it's more user-friendly and easy to set up (for the end-user). 

**Additional context**

I do realize this might be a bit too far off from the goal of this project.

**Comment by KoljaWindeler** [comment]
Hi, I'm sorry, but this isn't possible within the API that is currently used.
