### ISSUE TITLE
Music seek bar not working

### ISSUE THREAD

**Issue by prithvi1974** [KoljaWindeler/ytube_music_player#64]
1. Create 2 media player cards, one for ytube_music_player and one for actual speaker
2. Start some track/playlist on ytube_music_player
3. Use seek bar on ytube_music_player (doesn't work)
4. Use seek bar on actual speaker media player (it works)

Issue visible on these speakers: Google Home Mini, Google Nest Mini (2nd gen)

**Comment by KoljaWindeler** [comment]
hi, please check https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210207
Kolja
