### ISSUE TITLE
Repeat play list?

### ISSUE THREAD

**Issue by ignacio82** [KoljaWindeler/ytube_music_player#65]
Is there a way to add a repeat feature? My use case is that I want to have a playlist with white noise that plays on a loop while I sleep.  This is how the button looks like on youtube music:

![image](https://user-images.githubusercontent.com/1833309/107151773-3c32e780-6919-11eb-92e0-dff4b8cdec32.png)

Thanks for your excelent work!

**Comment by KoljaWindeler** [comment]
Isn't this already working? 'media_player.repeat_set' is the service ..

**Comment by KoljaWindeler** [comment]
is this still an issue?

**Comment by ignacio82** [comment]
thank you for your answer. I tested it last night and I can confirm that it works as expected.

**Comment by KoljaWindeler** [comment]
Great
