### ISSUE TITLE
Only gets playlist created by me.

### ISSUE THREAD

**Issue by castorinop** [KoljaWindeler/ytube_music_player#67]
See in the screenshots of media library, show "My Supermix" playlist but in my instance only show playlists that I have created.

**Comment by KoljaWindeler** [comment]
Hi, aber you refreshed the playlists after adding a new list on youtube? Or restarted Homeassistent?

**Comment by castorinop** [comment]
Restarted Homeassistant: Yes
Crate playlist on youtube: Yes. and appears on ytube playlist. 
But keep without my supermix playlist.

**Comment by KoljaWindeler** [comment]
Ok, so only that one playlist missing, correct?
Please enable debug logs and post the output here

**Comment by castorinop** [comment]
on youtube => "my supermix" tree dots => add playlist to library. and appears on ytube playlists.

**Comment by KoljaWindeler** [comment]
Please enable debug logs and post the output here

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player/blob/main/README.md#debug-information
closed due to inactivity
