### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by alexandrechoske** [KoljaWindeler/ytube_music_player#69]
![image](https://user-images.githubusercontent.com/47279355/108933388-d38e7f00-7629-11eb-82e1-122f25afd9c9.png)

im gettin this red message when trying to integrate.

all infos are ok

**Comment by KoljaWindeler** [comment]
please enabled debug information, restart HA, try again and 
copy the homeassistant log into this ticket, Thanks

**Comment by alexandrechoske** [comment]
Hi my friend, actually I figured it out.
The cookies I had to paste was from "accept encoding" to "youtube off-set".
You may want to fix the instructions on your print screen :)
Thanks in advance!
