### ISSUE TITLE
Multiple channel setup

### ISSUE THREAD

**Issue by kaizersoje** [KoljaWindeler/ytube_music_player#74]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I have a YouTube Premium account. However, I have 2 channels - A and B. A is the primary channel of the account - which contains music for my son. B is a channel I created to access my music. It looks like the cookie data is the same for both the channels. It would be good if the music player can be set up for each channel.

![account](https://user-images.githubusercontent.com/54566217/111151102-1ddc9d80-85e3-11eb-8b02-45c904d12b35.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by KoljaWindeler** [comment]
Is a channel the same as a brand Id?

**Comment by kaizersoje** [comment]
> Is a channel the same as a brand Id?

I am not too sure. What exactly is a brand id?

**Comment by KoljaWindeler** [comment]
Please google ... I haven't spent much time reading but i guess it could solve your issue

**Comment by kaizersoje** [comment]
I have done some reading. I have still not been able to conclude if channels are the same as brand ids.

However, let's assume it is the same. If so, how do I find the brand id?

**Comment by KoljaWindeler** [comment]
Honestly ... No idea. I just saw that it is an important parameter for some who have a brand id

**Comment by KoljaWindeler** [comment]
Ok I did a bit of research. Channel and brands are not the same. Channels are not supported by the current api. Please ask if this can be added. https://github.com/sigma67/ytmusicapi
Once that's in the api please re-open this ticket and I'll try to add it here as well.

**Comment by kaizersoje** [comment]
Thanks for looking into this.
