### ISSUE TITLE
help

### ISSUE THREAD

**Issue by litianyu0707** [KoljaWindeler/ytube_music_player#75]
hello ,  when i run yt_music,  it is wrong. and it said :
![111111111111111111111111111111](https://user-images.githubusercontent.com/22993989/111161065-aeac7c80-85d5-11eb-8494-b3c8026f5d38.png)
and i can't find this
![image](https://user-images.githubusercontent.com/22993989/111161322-ff23da00-85d5-11eb-8b0b-7c74293acd82.png)

please help me , thank you!

**Comment by KoljaWindeler** [comment]
You have to set the output, so the hardware that should playback the music

**Comment by litianyu0707** [comment]
so ,  the media_player.keller is the hardware ? such as  tv or soundbar  ?

**Comment by KoljaWindeler** [comment]
Yep, you have to tell the ytuve_music_player where it is supposed to play ... As you said: tv / Soundbar / Laptop / google mini ..

**Comment by litianyu0707** [comment]
can i play it by my computer?   thank you~

**Comment by KoljaWindeler** [comment]
Yes, via browser mod .. that's another custom component

**Comment by KoljaWindeler** [comment]
Did this work for you? Is this still an issue or can we close it?

**Comment by litianyu0707** [comment]
> Did this work for you? Is this still an issue or can we close it?

Okay！ thanks！
