### ISSUE TITLE
Channels/brands setup

### ISSUE THREAD

**Issue by kaizersoje** [KoljaWindeler/ytube_music_player#76]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled
Creating another ticket reference to [#74](https://github.com/KoljaWindeler/ytube_music_player/issues/74). I created issue [#177](https://github.com/sigma67/ytmusicapi/issues/177). I was able to get the brand id number based on the documentation and set up the integration. However, I get an error `(unavailable) is not a valid media player.` in the logs.

I added an entry to the header json as well

`"onBehalfOfUser": "123456789123456789123"`

However, after setting up the integration with the brand id, this line disappears from the json.

**Version**
please provide the version you are using (see HACS)

**To Reproduce**

**Additional context**

Thanks

**Comment by KoljaWindeler** [comment]
hi, when do you get the "is not a valid media player." error?

**Comment by kaizersoje** [comment]
Not sure what happened. It seems to be working fine now.
