### ISSUE TITLE
An easier way to refresh the cookie

### ISSUE THREAD

**Issue by samhed** [KoljaWindeler/ytube_music_player#77]
**Is your feature request related to a problem? Please describe.**
After a while (it feels like maybe ~2 months?) I have to get a new cookie from music.youtube.com and update the one used by this integration, this is a bit bothersome.

**Describe the solution you'd like**
Perhaps we could log in using our google accounts somehow, and the cookie could be automatically be extracted from the integration config flow?

**Describe alternatives you've considered**
If it isn't possible to accomplish this from the integration itself, perhaps a companion helper app that could be installed on the HA host could do the trick?

**Additional context**
I don't know anything about the limitations that apply here.

**Comment by KoljaWindeler** [comment]
Hi, please see https://github.com/sigma67/ytmusicapi/issues/10
Once that's possible I'll try to add this here as well
