### ISSUE TITLE
Autoload all Mediaplayer

### ISSUE THREAD

**Issue by KoljaWindeler** [KoljaWindeler/ytube_music_player#8]
Try to get ALL Mediaplayer and autofill the list with them
If one mediaplayer is provided as configuration: preselect this one on load

Also add this option to the config flow

**Comment by stboch** [comment]
Spotify media player component has many of the features we might want. To include the list all media players I believe (don't use Spotify so not sure)

**Comment by KoljaWindeler** [comment]
Added in https://github.com/KoljaWindeler/ytube_music_player/commit/6a4fd98b4b338fa7734dcfb8d9c8f0a8a2f05c54
