### ISSUE TITLE
ytube_music_player Missing?

### ISSUE THREAD

**Issue by RyanWoirol** [KoljaWindeler/ytube_music_player#80]
I had been using the player on an almost daily basis for the last week or so and I had just set up a script for my wife to activate yoga music.  She said that it didn't work today, it was her first time using it.  I tried and noticed that the player seemed to be missing from my dashboard.  I looked further and the entity is just, gone.  It's fully updated in HACS, the integration shows that it's installed but shows no connected entity.  I've tried resetting HA with no success, so decided to redo it all.  I tried to remove the integration and it just, doesn't.  

So now I have no idea where it is or how to get it back.

**Comment by KoljaWindeler** [comment]
HI, very strange. Nothing changed.
is the integration still in the list -> configuration -> integration?

**Comment by stboch** [comment]
@KoljaWindeler I was working on some testing with the google_home custom component and noticed when I tried to do a fresh install youtube music player no longer shows in the config flow no errors I can find just 👻 I can still configure via yaml but not sure what's going on need to see how far back I need to go before it starts working. 2021.3.4 of HA

**Comment by RyanWoirol** [comment]
> HI, very strange. Nothing changed.
> is the integration still in the list -> configuration -> integration? 

Yeah its still in the list.  I did nothing on my end.

**Comment by KoljaWindeler** [comment]
I've just retested the installation procedure and stumbled a couple times:
1. after the installation of HACS to took quite some time until all repositories were loaded (3min?)
2. after the installation in HACS (and the reboot) the ytmusicplayer didn't show up in the list of integrations (settings -> integrations) ... a simple refresh of the page helped 
I guess there is nothing that I can change from my side so I'll close this
