### ISSUE TITLE
Won't register the cookie

### ISSUE THREAD

**Issue by tripplehelix** [KoljaWindeler/ytube_music_player#82]
Keep getting the error: Format of cookie is NOT OK, likely missing '__Secure-3PAPISID' or '__Secure-3PSID'

I have checked the details I pasted following the guide and it includes both of these details.

**Comment by tripplehelix** [comment]
What details can I give for more information without giving out something sensitive?

**Comment by KoljaWindeler** [comment]
Hehe .. tough question ... I guess you could copy your cookie in here and change some of the values ..

**Comment by tripplehelix** [comment]
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en;q=0.9
authorization: SAPISIDHASH 1617797670_13785a74bfa2faf4efr34543etee32d2d305
content-length: 911
content-type: application/json
cookie: VISITOR_INFO1_LIVE=ranI_8zdGVw; PREF=f6=400&volume=100&tz=Europe.London&f5=30000; NID=208=r3yOircNLy2uLhb2z7ZtBPVhW71Dn2McTk8t7jgcjt71ExSS_VS62I1AtzG2hdbvAjUw7m-Mzl8NOZg_C9mxOD5asdCO2rZKBXtMzvx8d1CEm3PrK5IDsqb-na8QoaHh6LA6xsNXy10urk4nUrjok8GM0cA3tgSJhLk7d13j5SY; SID=7gdcDHNjCTeOvOftRNTelcYQjVUekmaHOedank7aBo9f9kCDO6tP4YYacszQe1xZwjtYVw.; __Secure-3PSID=7gdcDHNjCTeOvOftRNTelcYQjVUdfsfsHOedank7aBo9f9kDFn8NT0qy9mL6gjMqUbGEm2w.; HSID=Azd09vjrhFtBDF3YWH; SSID=AyHKQSZMjo7kaDQq6; APISID=N-c942KOKhIuFz0h/ACDf-mYUitdAKZ5yX; SAPISID=d-bQCLaAaMRPYoEX/AKDOU4Kl3PqHWo8b6; __Secure-3PAPISID=d-bQCLaAaMRPYoEX/AKDOU4Kl3PqHWo8b6; YSC=p2PXitj7L8s; LOGIN_INFO=AFmmF2swRQIgByUDvj8Z7KIm7M-WvLuJk4cMTwPdWXSf4L4E41JYIdICIQCfYKv66cwef3qMqeDCXnq5ycI74OFE3FEFEORLkFRQp9WYA:QUQ3MjNmeUJjcnBHLXQwc2hlOWhpSUVTcXRqc0lPZ1NSOWFDemNRcHk3NUlCdU5sSFhWSUJVamw3Y2pFDcV2cwTWFiNnZ3cDZjcDllbm5NUzl2WHZncTRMa1kyZjZidG1rcmhjWjlHTHEyMml3dm51QlhxS1pJMmJidzlQczVPTHpyUTJqd3hwX1VRVzB1Ri1IeG9kdDVrdDdGRU9lWl9Ka1BfesnNpUGdIWk1YRXk3Z2l3aC1F; SIDCC=AJi4QfGoPhc_oGFA9ChmyMLkb10FCtoauydqU7yiYABvX6YbHEX7JTBEqVdONtQBEeJh92jxe4g; __Secure-3PSIDCC=AJi4QfF1iolA8TWsO9iZIamTRZXkvG6FqSwtxsi8ToQAlugs5yW6dSbVYcfTqGaxpfrfphXBCRxc
dnt: 1
origin: https://music.youtube.com
referer: https://music.youtube.com/tasteprofile
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (X11; CrOS aarch64 13816.34.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.51 Safari/537.36
x-client-data: CIW2yQEIpbbJAQfeaoBCM24ygEIhLnKAQj4x8oBCPHIygEI78/KAQjhgfeBCL6aywEI2ZzLAQjjnMsBCIudywEIlZ3LAQifadfBCNKdywEI6J3LAQjan8sBCODtywEI4O/LAQi43MsBGNa9ygEYl8DKARjowMoBGNyaywEYip7LARjV78sBGOKjkAI=
Decoded:
message ClientVariations {
  // Active client experiment variation IDs.
  repeated int32 variation_id = [3300101, 3300133, 33443322, 3316814, 3312868, 3318776, 3334897, 3319791, 3326177, 33295342, 3329625, 3329635, 3329325, 3329685, 3329702, 3329746, 3329768, 3330010, 3340000, 3340256, 3340347];
  // Active client experiment variation IDs that trigger server-side behavior.
  repeated int32 trigger_variation_id = [3317462, 3317783, 3317864, 3329372, 3329802, 3340245, 4461026];
}
x-goog-authuser: 0
x-goog-pageid: undefined
x-goog-visitor-id: CgtyYW5JXzh6ZEdWdyiFxLaDBg%3D%3D

**Comment by tripplehelix** [comment]
yes that's the error

**Comment by KoljaWindeler** [comment]
Did you copy the complete cookie as shown In The video Guide?
I'm honestly not an expert. Not sure what cookie data the sub api need , maybe @sigma67 knows what's causing this. (It usually works ;))

**Comment by tripplehelix** [comment]
I'll try the entire cookie, I've tried trimming it just to what teh screenshot shows and that still errored.

**Comment by tripplehelix** [comment]
I have the old google account for youtube that lets you use a nickname... which is my default youtube account, but I use my personal account, using my real name for my music.

**Comment by KoljaWindeler** [comment]
have a look at https://www.youtube.com/watch?v=_UQv7fc3h5s .. around 2:18 ... that way usually works ..

**Comment by tripplehelix** [comment]
Same issue following his tutorial...

**Comment by KoljaWindeler** [comment]
Have you tried using a incognito session?

**Comment by tripplehelix** [comment]
I've only tried using incognito.

**Comment by tripplehelix** [comment]
:'( This is the last thing I want lol There's always a stopping point. Switched from running a python vm to haos to get my thermostat working.

**Comment by KoljaWindeler** [comment]
Let's see if sigma has an idea .. this isn't my code so let's see if he can help

**Comment by sigma67** [comment]
The cookie seems correct, although I'm getting 403 so @tripplehelix must have signed out again.

The error message seems unrelated to ytmusicapi, it's just a check performed by your project @KoljaWindeler ?

**Comment by tripplehelix** [comment]
It's edited @sigma67 

This gets added to the json file: media_player.home

**Comment by tripplehelix** [comment]
@sigma67 it's edited, but it creates the json file...

**Comment by tripplehelix** [comment]
ok no, the details in the json file are different to what I added

**Comment by KoljaWindeler** [comment]
> The cookie seems correct, although I'm getting 403 so @tripplehelix must have signed out again.
> 
> The error message seems unrelated to ytmusicapi, it's just a check performed by your project @KoljaWindeler ?

yes, thats a error that I throw once the user entered the credentials.
https://github.com/KoljaWindeler/ytube_music_player/blob/cc98b8cd29bc3f9563aa68c76e5fd2301f01e4ab/custom_components/ytube_music_player/const.py#L254
the try_login() routine tries to ... well ... login and reformats the error a bit nicer for the user .. sort of ...

**Comment by tripplehelix** [comment]
Is there a way to narrow down what it's not liking? I'm from the UK, the json file it creates switches the encoding to us if that's a problem.

**Comment by KoljaWindeler** [comment]
there is a fairly annoying part in my code that reformats the user input. 
https://github.com/KoljaWindeler/ytube_music_player/blob/cc98b8cd29bc3f9563aa68c76e5fd2301f01e4ab/custom_components/ytube_music_player/const.py#L214
this is needed because the system won't allow to paste a multiline text... so everything will be one line. I try to "readd" the line breaks .. that COULD be an issue ...


alternative solution: could your code accept a single-line cookie @sigma67 ?

**Comment by KoljaWindeler** [comment]
> Is there a way to narrow down what it's not liking? I'm from the UK, the json file it creates switches the encoding to us if that's a problem.

what you COULD do .. is to install the package from sigma67 and try to generate the json file yourself.
https://github.com/sigma67/ytmusicapi
once that works simply copy it in the storage folder and restart homeassistant ..

**Comment by KoljaWindeler** [comment]
hmm i've just realized that it won't work .. if you can finish the procedure it won't create an config von homeassistant .. 

ok .. still ... could you manually create the file and see if that works without an error ... and compare it to the file that the integration is creating?

**Comment by tripplehelix** [comment]
no idea how to use @sigma67 's script but I can manually create the file

**Comment by KoljaWindeler** [comment]
well .. 
1. run pip install ytmusicapi
2. create a python file e.g. test.py
```
from ytmusicapi import YTMusic
YTMusic.setup(filepath=headers_auth.json)

```
3. run it python3 test.py

it should ask you for the same data, paste them and compare the generated file (headers_auth.json) with the on in your homeassistant .storage folder

**Comment by tripplehelix** [comment]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from ytmusicapi import YTMusic
  File "/home/tom/test/ytmusicapi/ytmusicapi/__init__.py", line 2, in <module>
    from ytmusicapi.ytmusic import YTMusic
  File "/home/tom/test/ytmusicapi/ytmusicapi/ytmusic.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by tripplehelix** [comment]
sorry within the folder it creates installing via pip the error is:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from ytmusicapi import YTMusic
ModuleNotFoundError: No module named 'ytmusicapi'

**Comment by KoljaWindeler** [comment]
meh .. ok .. different idea .. would you send me your cookie data via email to Kolja.Windeler@gmail.com so I can give it a try? 
Yes that would grant me access to your YouTube music account, but once I've figured out what is causing it you can logout again and thus make the cookie invalid?

**Comment by tripplehelix** [comment]
sent

**Comment by KoljaWindeler** [comment]
ok .. honestly .. I don't get that .. it works without any issues here

**Comment by tripplehelix** [comment]
What are you doing different?

**Comment by tripplehelix** [comment]
running haos beta?

**Comment by tripplehelix** [comment]
64bit

**Comment by KoljaWindeler** [comment]
i've copied the complete text for your mail, pasted it without any magic into the 2nd field (enter cookie text, copied from browser), hit enter .. done .. i guess you've done the same .. 
I'm running on a docker container but I don't thing that it matters .. 
are you running the latest version (although I haven't changed anything in the login for a looong time)

**Comment by tripplehelix** [comment]
I keep reinstalling the plugin from hacs and keep hitting the same wall

**Comment by tripplehelix** [comment]
```Format of cookie is NOT OK, likely missing '__Secure-3PAPISID' or '__Secure-3PSID'```

**Comment by tripplehelix** [comment]
It just doesn't like me for some reason

**Comment by KoljaWindeler** [comment]
jep ... that seems to be the reason :D 
I'll send you the created json file via mail .. copy that into the .storage folder and add this to your configuration.yaml
```
media_player:
  - platform: ytube_music_player
    name: test_4_tom
    header_path: ytube_header_tom.json
````

**Comment by tripplehelix** [comment]
ok thanks

**Comment by KoljaWindeler** [comment]
sent

**Comment by tripplehelix** [comment]
should it show now as an integration or just a new entity?

**Comment by tripplehelix** [comment]
got it ;) you gave it a nickname lol, thanks <3

**Comment by tripplehelix** [comment]
What do I add to configuration.yaml to select the source ?

**Comment by tripplehelix** [comment]
How do I set the default media source now? It seems to connect to my account fine, but always errors and says "Please select a player before start playing, e.g. via the 'media_player.select_source' method or in the settings/config_flow"

I can't seem to guess the right way to do this.

**Comment by KoljaWindeler** [comment]
... right ... 
add 
```speakers: media_player.some_player```
to your config

**Comment by KoljaWindeler** [comment]
or was it 
speakers:
   - media_player.some_player 
thats something to test .. not sure :D

**Comment by tripplehelix** [comment]
It's just
```speakers: media_player.some_player```

What do I miss out on doing it like this? This method seems worthy enough to go in the installation method as 'manual'. Formatting the cookie data is just copy pasting certain data.

**Comment by tripplehelix** [comment]
My final Q and I'll leave you alone... Can I search for music or play random music or do I need to have a saved playlist?

**Comment by KoljaWindeler** [comment]
Everything that's in your library should be there.
But yes, the best way is to generate some playlists.
I'll close this although I don't get why it worked for me but not for you

**Comment by KoljaWindeler** [comment]
Random: yes, you can play a 'channel' basted on a 'playlistId' have a look in the readme

**Comment by KoljaWindeler** [comment]
hey: turns out to be a 2021.04 issue
please try https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210409b1

**Comment by tripplehelix** [comment]
Im too scared to start again!

**Comment by KoljaWindeler** [comment]
:D

**Comment by b1rken** [comment]
You did a great job on this plugin, thanks alot @KoljaWindeler. I had the same issue with my cookie, worked fine with the beta release :) 

I used wget from ssh to download the beta, and move/replace the 4 files that was changed in the beta release. 
Is it a easier way to install the beta release? It didnt show up when the show beta releases switch was on in home assitant/HACS.

**Comment by KoljaWindeler** [comment]
Hmm have you clicked "update information" in hacs?
Works here..

**Comment by b1rken** [comment]
I think so. Installed hacs for the first time last night anyways, so the information should be up to date. 
Couldnt find any beta versions tbh after clicking the switch.
