### ISSUE TITLE
Cookie is NOT OK - Can't  add yt integration

### ISSUE THREAD

**Issue by JayChun** [KoljaWindeler/ytube_music_player#83]
I've checked #60 , and i'm trying to grab a cookie several times in chrome. but I failed.
I have 2 HA machine (=Old and New), and an old HA has no problem like this. but the problem is came up from New HA.

**Old HA** : Raspberry 4B 4GB 32bit Pi OS with HA Supervised, Core 2021.3.0, Supervisor 2021.03.9, HACS integration version 1.11.3
**New HA** : Raspberry 4B 8GB 64bit Pi OS with HA Supervised, Core 2021.4.2, Supervisor 2021.03.9, HACS integration version 1.11.3

I tried many times to copy the cookie from existed cookie in old HA, and from new cookie of ytmusic in chrome.
But I can't pass a below stage.

![image](https://user-images.githubusercontent.com/71179304/114275550-efc17080-9a5d-11eb-9d0b-f19dbab7ec38.png)
 
Please let me know what is the problem.

**Comment by KoljaWindeler** [comment]
Hey, yes I'm aware of the problem. You can install the release beta .. that should work (completely?).... Or wait a few days until we figure out all the remaining issues

**Comment by JayChun** [comment]
> Hey, yes I'm aware of the problem. You can install the release beta .. that should work (completely?).... Or wait a few days until we figure out all the remaining issues
