### ISSUE TITLE
Playlist showing with the X past songs and the future X songs

### ISSUE THREAD

**Issue by WHagenauw** [KoljaWindeler/ytube_music_player#86]
Currently with your overview you can see the playlist completely. So with a lot of songs it is a long overview and after a while not able to see on the screen anymore where the playlist is. Is it possible to have a scrolling playlist where you can decide how many songs you want to see from the past (so which songs just played) and the X (decide yourself) amount of songs will be playing in the future. (e.g. the current playing song will than always be in the middle of the card). This way you can make a nice dashboard with it so that the amount space needed for the card is always the same.

**Comment by KoljaWindeler** [comment]
hi, i guess that should be possible .. look at the way the markdown card is displaying the playlist 
```
{% if is_state('media_player.ytube_music_player','playing') %}{%
for i in range(0,state_attr("media_player.ytube_music_player",
"total_tracks")) %}
 {% if i == state_attr("media_player.ytube_music_player",
"current_track") %}**{% endif %}\[{{i+1}}] {{
state_attr("media_player.ytube_music_player", "tracks")[i] }}{% if
i == state_attr("media_player.ytube_music_player",
"current_track") %}**{% endif %}
{%- endfor %}{% else %}Player off{% endif %}
```
so instead of `range(0,state_attr("media_player.ytube_music_player","total_tracks")` one could loop over +/- X tracks around `state_attr("media_player.ytube_music_player","current_track")` ...
You get the idea ?

**Comment by WHagenauw** [comment]
Hello,

Thanks for the reply. I get the idea that it should work with the current
just by changing the code but I just start with this and am not so good in
coding at this moment. I need to learn from examples :) If you would be so
kind to show me how I would really appreciate it.

Thanks in advance

Kind regards

Wim Hagenauw,


Op di 13 apr. 2021 om 13:10 schreef Kolja Windeler ***@***.***

**Comment by WHagenauw** [comment]
The + part I figured it out:
{% if is_state('media_player.ytube_music_player','playing') %}{% for i in range(0,state_attr("media_player.ytube_music_player","current_track")+11) %}
This way 10 tracks after the current stay in the view. But the X numbers before I can't get it working. Tried several things but without satisfying result.

**Comment by KoljaWindeler** [comment]
What about max(current_track-11,0) .. instead of the 0 in the range statement

**Comment by WHagenauw** [comment]
Sadly not working

Op di 13 apr. 2021 om 22:14 schreef Kolja Windeler ***@***.***

**Comment by KoljaWindeler** [comment]
```
{% if is_state('media_player.ytube_music_player','playing') %}
{% for i in range(([0,state_attr("media_player.ytube_music_player",
"current_track")-3]|max),([state_attr("media_player.ytube_music_player",
"total_tracks"),state_attr("media_player.ytube_music_player",
"current_track")+3]|min)) %}
{% if i == state_attr("media_player.ytube_music_player",
"current_track") %}**{% endif %}\[{{i+1}}] {{
state_attr("media_player.ytube_music_player", "tracks")[i] }}{% if
i == state_attr("media_player.ytube_music_player",
"current_track") %}**{% endif %}
{%- endfor %}
{% else %}Player off{% endif %}
```
you might have to adjust the +/- 3
JKW

**Comment by WHagenauw** [comment]
Thanks, this works!

Op wo 14 apr. 2021 om 07:36 schreef Kolja Windeler ***@***.***
