### ISSUE TITLE
No player selected or the selected player isn't available

### ISSUE THREAD

**Issue by wuism** [KoljaWindeler/ytube_music_player#87]
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:156 
Integration: yTubeMediaPlayer (documentation, issues) 
First occurred: 9:39:07 PM (13 occurrences) 
Last logged: 9:44:54 PM

No player selected or the selected player isn't available (media_player.unavailable/), you will not be able to play music, please set the default player in the settings/config_flow or call media_player.select_source

Seem to be getting this error recently after the update. Was working fine before. I copied the cookies again, deleted the integration and reconfigured via integrations but still the same error.

**Version**
20210412

Thanks

**Comment by KoljaWindeler** [comment]
Hi, the log says the media player you are using is called "media_player.unavailable" is that really your media_player?

**Comment by wuism** [comment]
<img width="503" alt="Screen Shot 2021-04-13 at 8 28 51 pm" src="https://user-images.githubusercontent.com/56300982/114683410-96e62680-9d42-11eb-8c22-b7193b976119.png">

media player as per the config flow is media_player.kitchen.

This does work when i do Text to Speech

**Comment by KoljaWindeler** [comment]
hi, i can reproduce the issue now .. this is a race condition between the chromcast integration being ready and my integration checking the media_player .. will publish a fix in a few days .. have to do a little more debugging

**Comment by KoljaWindeler** [comment]
Please test https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210414 and reopen if the error still occures

**Comment by Murtoe** [comment]
Hey, I seem to have the same issue:
Here´s the log entry:

_Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:161
Integration: YouTube Music Player (documentation, issues)
First occurred: 17:09:38 (9 occurrences)
Last logged: 19:55:01

No player selected or the selected player isn't available (/), you will not be able to play music, please set the default player in the settings/config_flow or call media_player.select_source_

I try to cast music to my Google Home Speaker. The Playlists etc. all show up, but as I hit play an error is displayed in the notifications for each action. TTS is not working as well, stating the same error / issue. 
I have tried an internet radio card, to make sure the Google Home Speaker is working which plays the radio stations without any issues. 

Any ideas?

**Comment by Murtoe** [comment]
> Hey, I seem to have the same issue:
> Here´s the log entry:
> 
> _Logger: custom_components.ytube_music_player.media_player
> Source: custom_components/ytube_music_player/media_player.py:161
> Integration: YouTube Music Player (documentation, issues)
> First occurred: 17:09:38 (9 occurrences)
> Last logged: 19:55:01
> 
> No player selected or the selected player isn't available (/), you will not be able to play music, please set the default player in the settings/config_flow or call media_player.select_source_
> 
> I try to cast music to my Google Home Speaker. The Playlists etc. all show up, but as I hit play an error is displayed in the notifications for each action. TTS is not working as well, stating the same error / issue.
> I have tried an internet radio card, to make sure the Google Home Speaker is working which plays the radio stations without any issues.
> 
> Any ideas?

Fixed it by using mini-media player ;-)
