### ISSUE TITLE
YT generated playlists

### ISSUE THREAD

**Issue by fr4nk2342** [KoljaWindeler/ytube_music_player#93]
I mostly use the YT generated playlists "My Mix 1-5". But these are not always available in ytube_music_player. Only after I have called the mixes individually on the YTM website and then reload the dropdowns they are available. Maybe there is an API call to update these mixes regularly?

Steps to reproduce:
1. check dropdowns, mixes "My Mix 1-5" not available
2. open each mix on YTM website
3. call ytube_music_player method: reload_dropdowns
4. mixes opened in step 2 are available
 
The PlaylistID remains the same, but the mixes are not available until you open them on the website. I'll activate the debug logs, maybe I can provide some more info next time.

**Comment by KoljaWindeler** [comment]
I've checkt the API and there is sadly no way to get those playlist .. I guess I have to close this here but you could open a ticket at the API https://github.com/sigma67/ytmusicapi and once it is integrated there re-open this issue. I'd be happy to add it
