### ISSUE TITLE
Sonos playback don't go to next song

### ISSUE THREAD

**Issue by Stephan296** [KoljaWindeler/ytube_music_player#94]
When i use a sonos to play some music he don't go to the next song. I see the time of every song at 2:30 but he goes further after 2:30 minutes.

**Comment by KoljaWindeler** [comment]
Did you use the sonos fix?
Kolja

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player#sonos-fix

**Comment by Stephan296** [comment]
Yes i use the sonof fix.
