### ISSUE TITLE
Support playlists > 100 songs

### ISSUE THREAD

**Issue by bducha** [KoljaWindeler/ytube_music_player#95]
Hello, and thanks for you hard work on this integration !

### What is the problem ?

I have a quite big playlist (~800 songs) that i like to play as background music, and I noticed that only the first few songs are played.
After searching a bit in the code, I've found that the `get_playlist` method of the ytmusicapi has a `limit` parameter which is not set, but has a default value of 100. So I imagine that the problem comes from here.

### Solutions
I think there is multiple solutions to this:
- Set a higher fixed value (1000 for example) in the code (not the cleanest, but the easiest)
- Add a playlist length parameter in the integration config
- Fetch the playlist length and then set the `limit` parameter of the `get_playlist` accordingly

**Comment by KoljaWindeler** [comment]
added to https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210510
please reopen if its not working
