### ISSUE TITLE
no sound output

### ISSUE THREAD

**Issue by Yonny24** [KoljaWindeler/ytube_music_player#98]
Hi,

Great integration btw.

All set up and running. Can enter my playlists and find the media player (sony SRX77).

But I can't get any sound output at all. Very odd. 
Running HA supervised on Debian buster.
Also tried another HA instance I have on another machine with HyperV VM. Again no sound through my player.

I chose card - media player and added the youtube integration with the sony as the entity.

Any suggestions?

Thanks

**Comment by KoljaWindeler** [comment]
Can you send a link to your Mediaplayer in general?

**Comment by Yonny24** [comment]
Just got it to work. Instead of using the songpal sony endpoint I used google chromecast and selected my online sony device SRS-X77.

All good now and sounds great!

Thanks

**Comment by Yonny24** [comment]
Sorry how can I show the volume controls? I'm using the mini media player.

Adding the Media player card:

type: media-control
entity: media_player.ytube_music_player

**Comment by Quentin-Cloos** [comment]
Same issue here on all my media_player, I have some Google Mini and a Denon AVR, what am I doing wrong? I have the last build from HACS and I'm on Home Assistant 2021.3.4.

**Comment by KoljaWindeler** [comment]
I don't think that the Denon integration support direct url playback

**Comment by Quentin-Cloos** [comment]
> I don't think that the Denon integration support direct url playback

Yes it should : https://www.home-assistant.io/integrations/heos/

Thats the integration I'm using.

**Comment by feinadam** [comment]
Same issue on my Denon AVR-X2700H.
I'm able to play URL, example from the HA built in radio collection, but not with the youtube music player.
Has anyone found a solution since then?

**Comment by 3deeee** [comment]
Can this be fixed? The issue also exists on Denon AVR-X1800H.

Please reopen issue :)
