### ISSUE TITLE
Cookie expire?

### ISSUE THREAD

**Issue by Yonny24** [KoljaWindeler/ytube_music_player#99]
Can the cookies expire? The playlists that were present when I added the cookie yesterday work fine.

But if I open my youtube account and add a new playlist, even though it does appear in the media browser, will not play.
Is this a cookie/permission issue I wonder?

Thanks

**Comment by KoljaWindeler** [comment]
We're currently facing serious playback issues due to some changes in the ytube api .. I'll publish a new version as soon as the changes are implemented ..

**Comment by Yonny24** [comment]
Awesome!

Sorry another question. I cannot get the volume bar to show on the youtube player card (media control card).

I have to add a second card with the mini-media-player to show the volume slider.

Not sure where I'm going wrong.

Many thanks for the fast responses.

**Comment by KoljaWindeler** [comment]
Start the playlist via mediabrowssr and copy the Id from the attributes while playing

**Comment by Yonny24** [comment]
Sorry, are you referring to values in header request in developer mode (F12)?

**Comment by KoljaWindeler** [comment]
Nope, the attributes on the development tab

Yonny24 ***@***.***> schrieb am Di., 18. Mai 2021, 15:50:

**Comment by Yonny24** [comment]
Really sorry I'm not following yet - could you kindly attach a screenshot?

Thanks

**Comment by samhed** [comment]
Is this API issue you mentioned @KoljaWindeler the reason I get "User input malformed" when I try to grab a new cookie text from the browser? I've done this several times before, I'm fairly certain I'm doing this correctly

**Comment by KoljaWindeler** [comment]
Hi, yes I had that before as well .. simply remove the integration (just on the integration page, no need to reinstall in hacs) and it will work again .. No idea what is causing this .. but be aware that nothing is really working at the moment .. the ytube api changes

**Comment by KoljaWindeler** [comment]
@Yonny24 : http://your-ip:8123/developer-tools/state

**Comment by samhed** [comment]
Thanks @KoljaWindeler

**Comment by Yonny24** [comment]
> 
> 
> @Yonny24 : http://your-ip:8123/developer-tools/state

For this part which card do I need to use? Tried the manual and media player pasting in my code:

`
![image](https://user-images.githubusercontent.com/64428686/118676000-6f66fb80-b7d1-11eb-97cd-daddaf57727e.png)
`

`alias: ytube morning routine
sequence:
  - service: media_player.select_source
    data:
      source: ytube_music_player
      entity_id: media_player.ytube_music_player
  - service: media_player.shuffle_set
    data:
      shuffle: true
      entity_id: media_player.ytube_music_player
  - service: media_player.play_media
    data:
      entity_id: media_player.ytube_music_player
      media_content_id: PLBGKi73v8aO04xcvvOG1JsvIwRc6J9GMY
      media_content_type: playlist
mode: single
`

**Comment by KoljaWindeler** [comment]
Hi, lets start over .. what are you trying to do? 
My understanding was that you want to use shortcut buttons on the mini-media-player to directly start a playlist / album / etc, is that correct?

**Comment by Yonny24** [comment]
Some drop downs like this would be awesome where I can select my playlist/albums/tracks etc.
Yes either as dropdowns on the media player or on another card.


![image](https://user-images.githubusercontent.com/64428686/118685781-c1138400-b7d9-11eb-9473-167f3fe188e7.png)


Also would like to show the songs in a list like this.
Look like all these are in their own card entities and customized. 

![image](https://user-images.githubusercontent.com/64428686/118685946-ebfdd800-b7d9-11eb-9067-fe52e3e64692.png)

**Comment by Yonny24** [comment]
Not sure how these entities are created or come from though:

`

              - entity: input_select.ytube_music_player_playlist
      
      
                      - entity: input_select.ytube_music_player_source
      
      
                      - entity: input_select.ytube_music_player_speakers
      
      
                      - <span class="pl-ent">entity</span>: <span class="pl-s">input_select.ytube_music_player_playmode</span>

`

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player#dropdowns-buttons-and-marksdowns

Yonny24 ***@***.***> schrieb am Di., 18. Mai 2021, 18:42:

**Comment by Yonny24** [comment]
Getting there slowly.
Haven't got the dropdowns yet.
But the links to these sources work and shuffle. 


![image](https://user-images.githubusercontent.com/64428686/118698567-f2df1780-b7e6-11eb-85ed-7380add69dc2.png)

**Comment by Yonny24** [comment]
Love it!!

![image](https://user-images.githubusercontent.com/64428686/118699463-f3c47900-b7e7-11eb-84bb-2f4d7603a3b5.png)

**Comment by Yonny24** [comment]
well deserved beer!

**Comment by Yonny24** [comment]
Any way of adding these playlists to a dropdown instead of buttons like this?

![image](https://user-images.githubusercontent.com/64428686/118708012-946b6680-b7f1-11eb-8eab-4c31dbf899b4.png)

**Comment by KoljaWindeler** [comment]
hi, yes  ... simply add the content of https://github.com/KoljaWindeler/ytube_music_player/blob/main/package/default.yaml to your configuration .. I have to write this clearer to the readme I guess :D

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player#faq

**Comment by Yonny24** [comment]
Great thanks.
Added to config without any changes. rebooted.

But:

![image](https://user-images.githubusercontent.com/64428686/118715656-43ac3b80-b7fa-11eb-9f66-0ce137976014.png)

Where is the missing info/code?
hmmm

**Comment by Yonny24** [comment]
Working now after another restart!! awesome!

**Comment by Yonny24** [comment]
always a but..


The playlist has no dependency on my media player yet.
How can I add a dropdown directly onto the player card? 

![image](https://user-images.githubusercontent.com/64428686/118718359-84598400-b7fd-11eb-80a6-16a45d66b337.png)

**Comment by KoljaWindeler** [comment]
When you simply "turn on" the player (hit power on) it should use the playlist ... No idea how to combine cards, please ask in the forum

**Comment by Yonny24** [comment]
Any idea if you can choose your own phone as an audio output device? Just crossed my mind.

**Comment by KoljaWindeler** [comment]
Let's please move this to the forum .. and yes: browsermod can do it
